### ISSUE TITLE
Elaborar banner para destacar oportunidade de trabalho como Analista de sistemas desenvolvedor

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/artes-graficas#10]
@marcioalvessilva por favor, baseando-se no que foi feito para o DeCS, usar a frase "Oportunidade de trabalho na BIREME com análise e desenvolvimento de sistemas web"

@marcoslmori assim que o Márcio elaborar o banner, por favor, pode publicá-lo na homepage da RedDes apontando para o link

https://reddes.bvsalud.org/vaga-analista-sistema-desenvolvedor-2021/

**Comment by marcioalvessilva** [comment]
@renatomurasaki e @marcoslmori 

Segue imagem 
https://github.com/bireme/artes-graficas/blob/main/banners-sites/reddes/jpg/vaga-analista-sistema-web.jpg

![image](https://user-images.githubusercontent.com/48724136/130107266-21e2fa31-24da-4d1f-8c03-68057a07c784.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva excelente. Aprovado
@marcoslmori pode utilizar, por favor, para colocar no portal da RedDes

**Comment by marcoslmori** [comment]
feito em reddes.bvsalud.org
