### ISSUE TITLE
Material gráfico comemorativo de 1 milhão de registros da LILACS

### ISSUE THREAD

**Issue by suelisuga** [bireme/artes-graficas#102]
Solicito criação de material gráfico para comemorar 1 milhão de registros da LILACS.
A demanda anteriormente havia sido solicitada para a Marina.

Muito obrigada

**Comment by marcioalvessilva** [comment]
@suelisuga , pode me dar mais informações:
- textos que deseja
- idiomas
- onde vai usar (twitter, site...)
Aguardo

**Comment by suelisuga** [comment]
@marcioalvessilva respondendo:

- 1 imagem para compartilhar nas redes sociais (perfis de Twitter e Facebook e grupos de WhatsApp) com texto comemorativo dos 1 milhão de publicações

- 1 imagem para incluir no banner do Portal Regional da BVS com o mesmo texto comemorativo dos 1 milhão de publicações

Desse tamanho: ![image](https://user-images.githubusercontent.com/13105683/177418152-522cd187-638c-4129-8c95-eebfe8eeb80a.png)

Texto em aprovação com a gerência:
LILACS (incluir logo)

1 millón de publicaciones

Evidencias científicas sobre Salud producidas por los países de Latinoamerica y el Caribe

Teremos a versão em português e inglês. Por enqto:
LILACS (logo)
1 milhão de publicações
Evidências científicas sobre Saúde produzidas pelos países da América Latina e Caribe

LILACS (logo)
1 million publications
Scientific evidence on Health produced by Latin American and Caribbean countries

- 1 infográfico com dados atuais da LILACS que iremos enviar por email e publicar matéria no Boletim BIREME.

Estamos revisando conteúdo para atualizar neste chamado.

Também será nos 3 idiomas.

Obrigada!

**Comment by marcioalvessilva** [comment]
Boa tarde, por favor validar

**Banners portal regional** - https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/lilacs/JPG
Ex:
![image](https://user-images.githubusercontent.com/48724136/177608082-88b3f74b-3f1b-479d-b488-46c6d6ab88fa.png)



**Facebook e Twitter** - https://github.com/bireme/artes-graficas/tree/main/lilacs/1mi/JPG
Ex:
![image](https://user-images.githubusercontent.com/48724136/177608293-a1dfd9e5-fea1-451a-8883-02c4dbe09efb.png)
