### ISSUE TITLE
Infográfico LILACS 1 milhão

### ISSUE THREAD

**Issue by suelisuga** [bireme/artes-graficas#104]
Solicito criação de um infográfico sobre LILACS é 1 milhão.

Para inspiração envio esse folder que agradou a nós.

Externo:
![image](https://user-images.githubusercontent.com/13105683/178848938-c87e5b01-d526-44b1-aaef-c76f11bd6979.png)

Interno:
![image](https://user-images.githubusercontent.com/13105683/178848984-31cf5d17-0d12-4e4e-bee1-fb69203c61a7.png)

O texto estamos revisando mas vai algo parecido com:

LILACS é um milhão

**Infográfico:**

Texto de inspiração para o infográfico, mas ainda estamos trabalhado nele.

Números em relação à LILACS

- Mais de 1 milhão de publicações
- 28 países
- Fonte de informação para X mapas de evidência e X vitrines do conhecimento
- Cerca de 900 revistas indexadas
- + de 12 mil revisões sistemáticas
- + de 14 mil revisões
- + de 55 mil guias de prática clínica
- + 6 mil novos termos em cinco categorias do DeCS/MeSH

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Mensagem Sueli

Márcio,
Segue documento detalhado sobre lilacs é um milhão.
A partir da página 6 fala sobre o infográfico.
Obrigada
[LILACS é um milhão.docx](https://github.com/bireme/artes-graficas/files/9253285/LILACS.e.um.milhao.docx)

**Comment by suelisuga** [comment]
oi @marcioalvessilva alguma novidade?
Será melhor marcar nova reunião?

**Comment by marcioalvessilva** [comment]
Olá @suelisuga  e @veronicaabdala 
Segue primeira proposta para o infográfico.

![image](https://user-images.githubusercontent.com/48724136/186492046-db63b5a1-44c7-4fdf-b740-3cd1702106be.png)

**Comment by veronicaabdala** [comment]
Exlcuir o de depois do + e usar o mil no lugar do .000

**+50mil
+100mil
+800
+550mil
+800mil
+1Milhão**

Para tipos de estudos, considerar estes:

**+56mil Guias de Prática Clínica
+18mil Ensaios Clínicos Controlados
+9mil Revisões Sistemáticas
+19mil Avaliações Econômicas
+2mil Avaliações de Tecnologias Sanitárias**

**Comment by veronicaabdala** [comment]
Poderia tentar uma outra cor para as linhas em amarelo? Para ter uma outra opção?  Achei um pouco estranho a combinação.

**Comment by suelisuga** [comment]
@marcioalvessilva Minhas observações:
![image](https://user-images.githubusercontent.com/13105683/186735729-c39653f5-a950-436e-9155-ac5bea762efd.png)

**Comment by suelisuga** [comment]
@marcioalvessilva  ![image](https://user-images.githubusercontent.com/13105683/186744922-ed22700f-9db3-4d52-a2bf-2eabb526b77d.png)

**Comment by marcioalvessilva** [comment]
Olá segue atualizações

![image](https://user-images.githubusercontent.com/48724136/186926082-2bd10b04-c1b6-4d95-80b3-828982b9fccb.png)

**Comment by marcioalvessilva** [comment]
Atualizado!

![image](https://user-images.githubusercontent.com/48724136/186938011-8c8a6986-55b9-40cd-a646-e25b4d814f33.png)

**Comment by veronicaabdala** [comment]
Acho melhor excluir os números a frente dos tipos de estudos, está um pouco poluído. Deixa somente os tipos de estudos.

Guias de Prática Clínica
Ensaios Clínicos Controlados
Revisões Sistemáticas
....

Sueli, confere o número de períodicos, está +800, eu acho que é 900 ??

E acho que podemos excluir o + na frente de todos os números, deixa tudo direto:

1 Milhão
800 Mil
550 Mil
...

**Comment by suelisuga** [comment]
@veronicaabdala o número baixou mesmo. Não temos 900 revistas mais. São 890

**Comment by marcioalvessilva** [comment]
Atualizado!
![image](https://user-images.githubusercontent.com/48724136/186965139-4c890f7e-7280-467c-bac7-18c900a2f641.png)

**Comment by marcioalvessilva** [comment]
Bom dia!
@suelisuga pode por favor me passar os textos em Espanhol e Inglês.
Vou fazer essas versões. abraço!

**Comment by suelisuga** [comment]
@marcioalvessilva 
ES

Literatura Latinoamericana y del Caribe en Ciencias de la Salud
Registros (igual PT)
Artículos de revistas
Textos completos (igual PT)
Libros y documentos gubernamentales
Revistas científicas

1 millón
Todos outros números iguais

LILACS (igual PT)
37 años

26 países cooperantes
39 países de publicación
800 centros cooperantes

Tipos de estudios
Guías de Práctica Clínica
Ensayos Clínicos Controlados
Revisiones Sistemáticas
Evaluaciones Económicas
Evaluaciones de Tecnologías Sanitarias

**Comment by suelisuga** [comment]
@marcioalvessilva 
Pensando agora... acho que eu já tinha traduzido no doc que enviei... mas traduzi tudo novamente.

EN


Latin American and Caribbean Health Sciences Literature
Records
Journal articles
Full texts
Books and Government documents
Scientific journals

1 million
800 k
550 k
100 k
50 k
800

LILACS
37 years

26 cooperating countries
39 countries of publication
800 cooperating centers

Types of studies
Clinical Practice Guidelines
Controlled Clinical Trials
Systematic Reviews
Economic Evaluations
Health Technology Assessments

**Comment by suelisuga** [comment]
Obrigada @marcioalvessilva !!
