### ISSUE TITLE
Destaque para o Portal Regional!

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#105]
Qual a importância do DeCS? 
Saiba mais sobre atualizações e recursos, uso na indexação e aplicação na pesquisa
27 jul  /12:00 hora de Brasília (GMT -3)
Participe: https://bit.ly/acceso-uso-informacion

¿Qué tan importante es DeCS?
Obtenga más información sobre las actualizaciones y las funciones, el uso en la indexación y la aplicación en la búsqueda
27 jul  /12:00 hora de Brasília (GMT -3)
Únete: https://bit.ly/acceso-uso-informacion

How important is DeCS?
Learn more about upgrades and features, use in indexing and application for search
Jul 27  /12:00 pm Brasília (GMT -3)
Take part! https://bit.ly/acceso-uso-informacion

**Comment by marcioalvessilva** [comment]
Por favor validar!
Publicados no GitHur
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/decs/JPG

**PT**
![image](https://user-images.githubusercontent.com/48724136/180830846-1be29af9-eedf-4d73-9afe-72b262bd88a4.png)

**ES**
![image](https://user-images.githubusercontent.com/48724136/180830926-a108d150-478c-4af6-acb3-b33cc7ff7680.png)

**ES**
![image](https://user-images.githubusercontent.com/48724136/180830979-41071b77-f25a-4c60-8b20-0134c74cad42.png)

**Comment by pintoros** [comment]
Oi Márcio, por favor substitua:
no es - Obtenga por Sepa
no en - features por resources.  Incluir um asterisco com letras menores  *presentation in spanish
Sei que o clique vai para o link, mas nesse caso gosto de colocar aberto também.

Obrigada, já pode publicar após as correções/inclusões.

**Comment by marcioalvessilva** [comment]
**En**
![image](https://user-images.githubusercontent.com/48724136/180841735-9541bf79-30f2-4495-b716-0023ff173103.png)

**Es**
![image](https://user-images.githubusercontent.com/48724136/180841807-3f138ac3-ccfb-4aa9-ab11-0a0baf50d5ec.png)

Atualizado
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/decs/JPG

**- Sei que o clique vai para o link, mas nesse caso gosto de colocar aberto também.**
Não entendi pode me explicar melhor

**Comment by pintoros** [comment]
Obrigada Márcio, é sobre a inclusão da ultima frase com o link na arte, mas pode deixar assim, já vou tentar publicar logo ;-)

**Comment by marcioalvessilva** [comment]
Perfeito, fico à disposição!
