### ISSUE TITLE
Traducción del conocimiento - Destaque da reunião de 4a feira no portal regional

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#107]
Tradução do conhecimento: conceitos, recursos e ferramentas
Reunião aberta para o Fortalecimento das Redes de Informação em Saúde na AL&C
03 ago /12:00 hora de Brasília (GMT -3)
Participe: https://bit.ly/traduccion-del-conocimiento

Traducción del conocimiento: conceptos, recursos y herramientas
Reunión abierta para el Fortalecimiento de Redes de Información en Salud en AL&C
03 ago /12:00 hora de Brasília (GMT -3)
Únate: https://bit.ly/traduccion-del-conocimiento

Knowledge translation: concept, resources and tools
Open meeting to Strengthening of Health Information Networks in LA&C
Aug 3th /12:00 pm Brasília (GMT -3)
Take part! https://bit.ly/traduccion-del-conocimiento

Obrigada

**Comment by marcioalvessilva** [comment]
Segue propostas

**Pt**
![traducao-do-conhecimento-pt](https://user-images.githubusercontent.com/48724136/182438466-382fb3a5-8a9d-48b2-bd03-c02ff2b461c6.jpg)

**En**
![traducao-do-conhecimento-en](https://user-images.githubusercontent.com/48724136/182438473-193ee302-ae96-498d-b2e9-e9af27a0af4d.jpg)

**Es**
![traducao-do-conhecimento-es](https://user-images.githubusercontent.com/48724136/182438475-b02e823a-26a7-4a73-bbb4-fdb905c0a48e.jpg)

**Comment by pintoros** [comment]
Aprovado
