### ISSUE TITLE
Vitrines 1 e 2 - Projeto Saúde Indígena

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#109]
Marcio, vamos criar essas 2 vitrines com wordpress para ter mais flexibilidade na inclusão de novos conteúdos.
Abaixo a instância para essa criação:
https://saudeindigena.teste.bvs.br/vitrinas/
Aguardo sua disponibilidade para explicar melhor em uma reunião.

[Vitrine_do_Conhecimento_Alcoolismo.pdf](https://github.com/bireme/artes-graficas/files/9255150/Vitrine_do_Conhecimento_Alcoolismo.pdf)
[Vitrine_do_Conhecimento_IST.pdf](https://github.com/bireme/artes-graficas/files/9255151/Vitrine_do_Conhecimento_IST.pdf)
- variações de tom de vermelho para as de IST; e
- variações de tom de amarelo para alcoolismo.

**Comment by marcioalvessilva** [comment]
Bom dia!
Por favor avaliar as proposta
sobre a vitrine de Infecções Sexualmente Transmissíveis, não encontrei imagens que represente os títulos, peço ajuda nesse sentido. fico à disposição para ajustes se necessários

**Comment by pintoros** [comment]
Márcio, solicitei ao consultor uma ideia para vitrine IST e mandei as imagens para ele avaliar.

**Comment by marcioalvessilva** [comment]
Ok fico no aguardo, para dar continuidade!

**Comment by pintoros** [comment]
Bom dia Márcio, o consultor gostou das vitrines e não sugeriu imagem. A minha sugestão é busca no banco da OPAS os tópicos relacionados, por exemplo:
DST - imagem genérica dos virus, com o nome DST estilizado	

HIV, Hepatite e AIDS - uma imagem das mãos de um agente de saúde furando o dedo de um paciente para fazer o teste. Usar imagens de mãos mais simples e 'brasileiras' sem joias, aneis, pulseiras, esmalte...como se fosse uma mãos de indígenas. Envio uma imagem de exemplo.

Saude da mulher e gestação - Seria legal se encontrasse uma indigena brasileira grávida ou uma mulher indígena em atendimento

Educação em saúde - um indígena brasileiro estudando http://obind.eco.br/2018/08/22/sesai-agentes-de-saude-recebem-capacitacao-em-areas-indigenas/
![WhatsApp_Image_2021-07-15_at_15 24 27_(1)](https://user-images.githubusercontent.com/29313904/185648015-926bb25d-3994-4de8-8ba1-303c5993c912.jpg)

![sae-realiza-testes-rapidos-de-hiv-sifilis-e-hepatites-b-e-c-2](https://user-images.githubusercontent.com/29313904/185648019-b47d0805-ec3c-4aa7-9db3-6a762df9f55f.jpg)

**Comment by marcioalvessilva** [comment]
Ok Rose, assim que possível vou dar continuidade e aviso você.
Abraço!

**Comment by marcioalvessilva** [comment]
Imagens cadastradas, fico à disposição, abraço!

**Comment by pintoros** [comment]
Márcio pode me passar a url de teste das vitrines? Não estou conseguindo acessar com a geral. Obrigada

**Comment by marcioalvessilva** [comment]
https://saudeindigena.teste.bvs.br/vitrinas/post_vitrines/infeccoes-sexualmente-transmissiveis/
https://saudeindigena.teste.bvs.br/vitrinas/post_vitrines/alcoolismo-em-comunidades-indigenas/

**Comment by pintoros** [comment]
Bom dia!
Ficaram ótimas as imagens!!!
Podemos sincronizar com a produção?
Obrigada

**Comment by marcioalvessilva** [comment]
Bom dia Rose, existe alguma plano de home Page ou posso likar para o portal de vitrines?

**Comment by pintoros** [comment]
Vai ter uma home sim Márcio. https://saudeindigena.bvs.br
Como ainda não tem a página, assim que for para produção eu registro no portal Vitrines para que seja promovida.

Obrigada


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:d30018d6-e6a3-4aba-ae09-22e158d8d36f]

________________________________
De: Márcio Alves ***@***.***>
Enviado: quinta-feira, 25 de agosto de 2022 09:33
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Vitrines 1 e 2 - Projeto Saúde Indígena (Issue #109)


Bom dia Rose, existe alguma plano de home Page ou posso likar para o portal de vitrines?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F109%23issuecomment-1227196406&data=05%7C01%7Cpintoros%40paho.org%7C3b1692d4bcb1421c575908da8695f778%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637970275921575878%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EqceisdQwBPF2fNYL8vAV4ZpFwB9pA03FhS8DMOuVXc%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4CE6PBLGUIOCPHSC63V25RYJANCNFSM55QJVNAQ&data=05%7C01%7Cpintoros%40paho.org%7C3b1692d4bcb1421c575908da8695f778%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637970275921575878%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hTqkPs1PA7jSHQoGEm2jozqJDt542DTvzlDgq0HH60E%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pintoros** [comment]
Marcio, boa tarde
Foi solicitado um ajuste no texto do botão [Link] para [Documentação]
Obrigada

**Comment by pintoros** [comment]
Obrigada!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:789035c8-e5dc-4147-ba47-3d08c883359d]

________________________________
De: Márcio Alves ***@***.***>
Enviado: sexta-feira, 2 de setembro de 2022 11:30
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Vitrines 1 e 2 - Projeto Saúde Indígena (Issue #109)


Atualizado!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F109%23issuecomment-1235575071&data=05%7C01%7Cpintoros%40paho.org%7Cd883f852457349f2656f08da8cefb86e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637977258481547589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7img5%2Bjk%2BELD6aQiMNovHoHFaWC5i7tUpdasWMs5BKY%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4DK7XZYBVFOTJ74IHDV4IFRJANCNFSM55QJVNAQ&data=05%7C01%7Cpintoros%40paho.org%7Cd883f852457349f2656f08da8cefb86e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637977258481547589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ob%2BV4s9raPjIdLtz0usPAeb43Mg99gjn6ZrExq1oXHk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Finalizado!!!
