### ISSUE TITLE
Ajuste layout - Vitrine da SMS-SP

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#110]
Márcio, por favor poderia fazer os seguintes ajustes na Vitrine COVID-19 na Cidade de São Paulo disponível em: https://sms.sp.bvs.br/vitrinas/wp-admin
1) Diminuir a letra dos labels Veja mais e Links relacionados para que fique mais harmônico em relação aos conteúdos.
2) incluir o rodapé da BVSSMS-SP
![Outlook-pfeb1p2x](https://user-images.githubusercontent.com/29313904/183766959-74b9568d-996e-4601-bb1c-7954ec8c5ff9.png)

**Comment by marcioalvessilva** [comment]
Olá Rose, por favor validar!

**Comment by pintoros** [comment]
Márcio, faltaram alguns elementos no rodapé, como as redes sociais da SMS-SP, é possível seguir o mesmo padrão da página principal para todas as vitrines criadas nessa instância?
Obrigada

**Comment by marcioalvessilva** [comment]
Rose, podem me passar o link das redes sociais e o link da pagina de exemplo, para evitar que eu copie o errado, Grato!

**Comment by pintoros** [comment]
Segue o link da página Márcio.

https://sms.sp.bvs.br/

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:202b11a0-48ee-472b-afec-c2c3df07cc10]

________________________________
De: Márcio Alves ***@***.***>
Enviado: sexta-feira, 12 de agosto de 2022 09:28
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Ajuste layout - Vitrine da SMS-SP (Issue #110)


Rose, podem me passar o link das redes sociais e o link da pagina de exemplo, para evitar que eu copie o errado, Grato!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F110%23issuecomment-1213060289&data=05%7C01%7Cpintoros%40paho.org%7C2a37ebf7f5f944f8912808da7c5e238c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637959041011889381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LGzAj%2BvuyValqNLeC7VQFdmaQU0bHyLoJyEcUcXv8LA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BI7V3HBPGI454K2JLVYY7OFANCNFSM56CI3E5A&data=05%7C01%7Cpintoros%40paho.org%7C2a37ebf7f5f944f8912808da7c5e238c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637959041011889381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ILLdUk1pvGLzN298BUI1kO38k8TiWL%2FC6rIfP3Jc0A4%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Pronto por favor validar!

**Comment by pintoros** [comment]
Boa tarde Márcio,

É possível manter os links no mesmo padrão da página original (e azul)?  E, se possível, o logo BVS no banner remeter para a BVS https://sms.sp.bvs.br/

Obrigada


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:8a550527-2969-44c4-b7cf-f75d2add2b51]

________________________________
De: Márcio Alves ***@***.***>
Enviado: sexta-feira, 12 de agosto de 2022 13:38
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Ajuste layout - Vitrine da SMS-SP (Issue #110)


Pronto por favor validar!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F110%23issuecomment-1213310261&data=05%7C01%7Cpintoros%40paho.org%7Ca2862df6ecd84b7cb8f108da7c810564%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637959190830844153%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9OgHjuNz0JRHz2KiNNZZVm48DGf%2BGy3hpl0eKz%2BKnOk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4AQBDIFNYTHCBM3QRDVYZ4WRANCNFSM56CI3E5A&data=05%7C01%7Cpintoros%40paho.org%7Ca2862df6ecd84b7cb8f108da7c810564%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637959190831000381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gRYNKu%2FmLh70EH7xZsZyUE3o1WbHu97ATH8VmI2G5Ms%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by sousajul** [comment]
@marcioalvessilva e @pintoros só uma observação, que o Banner da vitrine também tem que seguir o padrão do banner da BVS.

Abraços,

**Comment by pintoros** [comment]
Perfeito!
Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:2b421e66-621f-4ab9-81e6-6fb13bbebdf2]

________________________________
De: sousajul ***@***.***>
Enviado: sexta-feira, 12 de agosto de 2022 15:49
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/artes-graficas] Ajuste layout - Vitrine da SMS-SP (Issue #110)


@marcioalvessilva<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcioalvessilva&data=05%7C01%7Cpintoros%40paho.org%7Cb743434775a64a36031008da7c9359fe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637959269565580008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NqSVz7Mgu5OAnXDk6wEaAYhsbaTufpqxUf2hLiGT7EU%3D&reserved=0> e @pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=05%7C01%7Cpintoros%40paho.org%7Cb743434775a64a36031008da7c9359fe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637959269565736252%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fHVT69rvYTxDtZx05KVnPuc5ze4S2Hsgkuy1sEoCnxk%3D&reserved=0> só uma observação, que o Banner da vitrine também tem que seguir o padrão do banner da BVS.

Abraços,

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F110%23issuecomment-1213417488&data=05%7C01%7Cpintoros%40paho.org%7Cb743434775a64a36031008da7c9359fe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637959269565736252%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fth%2B38U%2FZslsRuR6eLXe02oi7E1MVziTBzzyFMx2RsQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4H22VZCQGVAEZLKMYDVY2MCRANCNFSM56CI3E5A&data=05%7C01%7Cpintoros%40paho.org%7Cb743434775a64a36031008da7c9359fe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637959269565736252%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hVo6togiMFQ6qIMz43b9Xaw9OS59pN1h%2FKCw7bZ%2BxvU%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pintoros** [comment]
Listo!
