### ISSUE TITLE
Criar material gráfico - lançamento BIGG-REC e COVID-Therapy 

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/artes-graficas#111]
Lucas, 

Segue o texto da programação nos 3 idiomas (em anexo)  já revisados por mim. Vamos tentar fazer um flyer para poder usar como destaque no portal regional e nas redes sociais. 

Já estou copiando @da Silva, Marcio (BIR) para que nos ajude neste material.  

obrigada, 

Verônica

__________
Segue uma versão completa com os links de acesso aos novos recursos na BVS. Sugiro um material gráfico mais curto chamando atenção para o lançamento dos dois novos recursos: BIGG-REC e COVID-Therapy.

[Webinar BIGG-REC e COVID-Therapy 23 agosto V3.docx](https://github.com/bireme/artes-graficas/files/9339003/Webinar.BIGG-REC.e.COVID-Therapy.23.agosto.V3.docx)

**Comment by pintoros** [comment]
Márcio, solicito ainda um banner para destaque no Portal Regional.
Obrigada
