### ISSUE TITLE
Gerar QR code - Vitrine e Mapa Nutrição

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#112]
Solicito gerar QR code para acesso a:

Vitrine
https://brasil.bvs.br/vitrinas/post_vitrines/alimentacao-e-nutricao-em-saude-publica/

Mapa de evidências
https://public.tableau.com/app/profile/bireme/viz/ma-nutricao-aps-pt/evidence-map

Vamos usar em um vídeo que está sendo produzido - Modelo no final desse vídeo - https://drive.google.com/drive/folders/1M7vMtsKnvnuM7ws1cxSjOyLfgjrwpVk6

**Comment by marcioalvessilva** [comment]
Boa tarde Rose
Segue pasta com os QR-Codes  em dois formatos SVG e JPG
[qr code.zip](https://github.com/bireme/artes-graficas/files/9353041/qr.code.zip)


Caso precise criar novos eu compartilho com você esse link, só inserir a URL que da certo
https://qrd.by/qr-code-generator-svg

**Comment by marcioalvessilva** [comment]
Enviado!
