### ISSUE TITLE
Criar flyer divulgação Lançamento BVS Bolívia

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#114]
Solicito criar flyer divulgação para o Lançamento da BVS Bolívia. https://bolivia.teste.bvsalud.org/

Informações:

Título: Lanzamiento de la BVS Bolivia Nacional
30/08 a las 14h de Bolivia / 15h de Brasilia

Evento será presencial e online
Presencial em: Biblioteca Central de la Universidad Mayor de San Andrés, Monob
lock Central Av. Villazon Nro. 1995

**Comment by marcioalvessilva** [comment]
Bom dia!
Me compartilha o link da versão online

Abraço!

**Comment by marcioalvessilva** [comment]
Boa tarde!
Por favor validar!

![image](https://user-images.githubusercontent.com/48724136/186005398-46fb749e-7c11-4526-97e9-e1b524ab8fd5.png)

**Comment by sousajul** [comment]
Márcio, seguem considerações:

1. Gostei do estilo da arte do destaque para o evento que será realizado hoje, poderia seguir algo parecido utilizando as cores da bandeira do país. ![WhatsApp Image 2022-08-23 at 11 40 52](https://user-images.githubusercontent.com/13439949/186189561-b5cb0927-88e7-4f03-b921-906913e37fee.jpeg)
2. A faixa preta onde está "Evento presencial e online" está ganhando mais destaque do que o próprio titulo, poderia coloca-la como uma nota e fonte menorzinha e o título parece que está fora da imagem, parece que está solto.
3. Usar os logos da BVS e BIREME em espanhol
4. No lugar da URL colocar o QRcode para acessar o evento.

**Comment by marcioalvessilva** [comment]
Segue nova versão, aguardo aprovação para avançar disponibiliza formato de publicação.
![image](https://user-images.githubusercontent.com/48724136/186210685-9fe7f7ef-dad0-429c-b4cb-f12423929bb9.png)

**Comment by sousajul** [comment]
Marcio, segue comentários
- no topo use apenas as faixas com as cores da bandeira sem o brasão
- Colocar a frase "evento presencial e online" em espanhol [evento presencial y online] e colocar essa informação abaixo do endereço e do QRcode com uma fonte menor do que a que está
- Diminuir o espaço onde está o logo da BVS e BIREME, deixar como uma faixa menor como na primeira versão
- O fundo não necessariamente precisava ser verde, o exemplo que coloquei foi o "estilo", fonte, bordas, conteúdos em destaque, etc.

**Comment by marcioalvessilva** [comment]
Alterações!
![image](https://user-images.githubusercontent.com/48724136/186220580-3c46bdf6-7c2e-4c76-8f20-568855d4f77e.png)

**Comment by marcioalvessilva** [comment]
Imagens atualizadas!
https://github.com/bireme/artes-graficas/tree/main/bvs-bolivia/JPG

**Facebook**
![image](https://user-images.githubusercontent.com/48724136/186252597-070dbb6a-2007-4bd2-85b5-aa49c3796e12.png)


**Twiiter**
![image](https://user-images.githubusercontent.com/48724136/186252664-e167ee90-5e4a-4e28-b57d-a9be441b5ef6.png)

**Comment by marcioalvessilva** [comment]
Concluído!
