### ISSUE TITLE
Vitrine do conhecimento DCDSS

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#115]
Boa tarde Marcio, 

Preciso atualizar um conteúdo que está atrás de uma imagem da Vitrine DCDSS - https://bvsalud.org/vitrinas/wp-admin/edit.php?s=dcdss&post_status=all&post_type=post_vitrines&action=-1&m=0&paged=1&action2=-1

É a imagem de Vídeos/Webinar. O link para atualizar é https://bit.ly/3Adt4Lq 

Caso seja simples para eu mesma fazer, pode me ensinar.

Obrigada

**Comment by marcioalvessilva** [comment]
Eu fiz mas deixo aqui um tutorial para as próximas vezes que desejar atualizar

**Passo  1** - Menu Imagem Hove  - Oxilab Addons
![image](https://user-images.githubusercontent.com/48724136/186508028-b19bf36e-3dca-4094-a0fc-10b507c30d7c.png)

**Passo 2** - Aba Shortcode  - Escolher galeria que deseja atualizar - Neste caso DCDSS
![image](https://user-images.githubusercontent.com/48724136/186508378-91db8b85-c0a4-44e1-a99a-4e9966f10a19.png)

**Passo 3** - Colocar o mouse sobre a imagem que deseja alterar e escolher Editar
![image](https://user-images.githubusercontent.com/48724136/186508431-26f93ff4-eea6-425d-9b01-a68f3065962e.png)

**Passo 4** - Localizar campo link, alterar e clicar em Submit
![image](https://user-images.githubusercontent.com/48724136/186508498-3fece090-c234-401e-b2b2-808560db7d15.png)

Concluído
![image](https://user-images.githubusercontent.com/48724136/186508769-7128e255-3f7a-49b4-a3cd-9518af817bbf.png)

Espero ter ajudado!!!

**Comment by pintoros** [comment]
Ajustado!
