### ISSUE TITLE
Criar arte gráfica Modelo Instancia BVS

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#116]
Marcio, solicito seu apoio para criar uma imagem personalizada seguindo o modelo.

Titulo: Ecosistema del Modelo de la BVS 

![image](https://user-images.githubusercontent.com/13439949/187753684-78d98661-4e60-4a17-b130-0314492e61f5.png)

**Comment by sousajul** [comment]
Link do instrumento de maturidade: https://red.bvsalud.org/modelo-bvs/pt/instrumento-de-maturidade-da-bvs/

**Comment by marcioalvessilva** [comment]
Boa tarde @sousajul segue uma versão simplificada para o Ecossistema do modelo BVS, aguardo o seu feeback, abraço!

### **Link no GitHub**
https://github.com/bireme/artes-graficas/blob/main/bvs/JPG/modelo-instancia-bvs.jpg

### **Exemplo**
![image](https://user-images.githubusercontent.com/48724136/190225237-d6ae7e6f-fd94-46ee-b9b1-10284bd639a3.png)

**Comment by sousajul** [comment]
@marcioalvessilva, seguem alguns comentários:

- o nome instancia está escrito errado
- Identiquei que o desenho Instituciones/Usuários/Contenidos e o que está no círculo são praticamente a mesma coisa, talvez teríamos que repensar
- o circulo laranja não deve receber o título "usuarios"
-

**Comment by marcioalvessilva** [comment]
![image](https://user-images.githubusercontent.com/48724136/192001490-918f09da-6293-47f0-899b-917542032b29.png)

**Fico no aguardo de sugestões** - Identiquei que o desenho Instituciones/Usuários/Contenidos e o que está no círculo são praticamente a mesma coisa, talvez teríamos que repensar

**Comment by marcioalvessilva** [comment]
De acordo com a última conversa, foi decidido que o modelo seria repensado, quando houver avanço nesse sentido reabre o issue novamente para que possamos dar continuidade.
Continuo à disposição.
