### ISSUE TITLE
Criar imagem personalizada sobre Redes das Redes

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#117]
Podemos separar por redes nacionais, temáticas, institucionais...

![image](https://user-images.githubusercontent.com/13439949/187754527-bbfdcd6f-c2c7-45cf-b455-c2a409b36cdc.png)

Modelos de inspiração:

![image](https://user-images.githubusercontent.com/13439949/187757490-c59299ab-b156-41da-b9ea-b52b41822714.png)

![image](https://user-images.githubusercontent.com/13439949/187760460-dce67fc6-d1b8-4dac-9809-89534f6e7127.png)

![image](https://user-images.githubusercontent.com/13439949/187755716-1cd52512-0f89-4bad-ba27-2b9b0ada3cb1.png)

![image](https://user-images.githubusercontent.com/13439949/187755919-0a0fc3ba-5d74-4b49-baaa-c7fd0c22e636.png)

![image](https://user-images.githubusercontent.com/13439949/187756714-81777c1e-bd21-463d-b663-dd37c539a330.png)

**Comment by marcioalvessilva** [comment]
Boa tarde @sousajul segue primeiras imagens, aguardo feedback para decidir se criamos outro modelo ou modificações

### **Exemplo 1**
![image](https://user-images.githubusercontent.com/48724136/190479454-2f6969ca-47d8-4d03-a423-6c16922315ed.png)

### **Exemplo 2**
![image](https://user-images.githubusercontent.com/48724136/190479490-f3f89e2a-b704-46bc-be5d-728d8ee69b9f.png)

**Comment by marcioalvessilva** [comment]
Quando houver avanço nessa demanda, por favor reabrir esse issue.
Continuo à disposição.
