### ISSUE TITLE
Desenvolver um infográfico sobre o DeCS/MeSH

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#118]
@marcioalvessilva por favor,
Para ser incluído no vídeo do canal do DeCs no YT.
Algo assim:
![image](https://user-images.githubusercontent.com/35345406/187986060-7ff6fb5e-eaa7-4ac3-af82-bbbf48256ba9.png)

Obrigada!

**Comment by acecampos** [comment]
![image](https://user-images.githubusercontent.com/35345406/188713030-a3f3e5cd-6775-47c8-b7ab-a9211b84602b.png)

**Comment by acecampos** [comment]
categorias MeSH:
Anatomia
Organismos
Doenças
Compostos Químicos
Técnicas e Equipamentos
Psiquiatria e Psicologia
Fenômenos e Processos
Antropologia e Fenômenos Sociais
Indústria e Agricultura

**Comment by acecampos** [comment]
Outros recursos:
- Imagem de logo para avatar

**Comment by marcioalvessilva** [comment]
Boa tarde! @acecampos @lucianaPRB @marcoslmori 
Seguem sugestões para infográfico 

### **Exemplo 1**
![image](https://user-images.githubusercontent.com/48724136/189721810-8f2f6476-46b3-47dd-84d3-641d5d45ec05.png)

### **Exemplo 2**
![image](https://user-images.githubusercontent.com/48724136/189721847-024e6bbb-1e2c-420e-8d4d-471dfd32a059.png)

**Comment by acecampos** [comment]
@marcioalvessilva, ótimo!! Voto pelo exemplo 1.

**Comment by marcioalvessilva** [comment]
Finalizado!
