### ISSUE TITLE
Desenvolver um banner para o canal do YouTube do DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#119]
Favor desenvolver um banner para o canal do YouTube do DeCS.
Grata!

**Comment by marcioalvessilva** [comment]
Olá @acecampos @lucianaPRB @marcoslmori desenvolvi 3 propostas para banners e coloquei como exemplo abaixo


### **Exemplo 1**
![exemplo1](https://user-images.githubusercontent.com/48724136/189424254-d7b1705c-c183-4443-aa41-10ed1a7c3353.jpg)



### **Exemplo 2**
![exemplo2](https://user-images.githubusercontent.com/48724136/189424249-4fe30a83-6b27-4555-a2d0-3ad8014d18c4.jpg)



### **Exemplo 3**
![exemplo3](https://user-images.githubusercontent.com/48724136/189425558-caa20c1f-0949-4664-be13-e32241849ad6.jpg)

**Comment by acecampos** [comment]
Show, @marcioalvessilva! Se for para votar, voto no exemplo 2.

**Comment by lucianaPRB** [comment]
@marcioalvessilva Ficaram muito bons, parabéns pelo trabalho!!! Minha preferência é pela segunda opção. Obrigada

**Comment by marcioalvessilva** [comment]
Finalizado!
