### ISSUE TITLE
Desenvolver animação / vinheta para o canal do DeCS no YT

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#120]

**Comment by marcioalvessilva** [comment]
@acecampos @lucianaPRB @marcoslmori 
Seguem dois exemplos de intro para vídeos no Canal DeCS no Youtube

### **Exemplo 1**
https://user-images.githubusercontent.com/48724136/189955468-8b337b28-3386-45d8-a969-24ec84d24c31.mp4

### **Exemplo 2**
https://user-images.githubusercontent.com/48724136/189955476-0552c4e8-2307-4875-a723-79c47e4b7e03.mp4

**Comment by acecampos** [comment]
@marcioalvessilva Adorei o logo rotativo! Parabéns! Meu voto é pelo exemplo 2.

**Comment by lucianaPRB** [comment]
Muito bom @marcioalvessilva Fico com o exemplo 2 também!

**Comment by marcioalvessilva** [comment]
Finalizado!
