### ISSUE TITLE
Criar ícones para nova seção BVS MTCI

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#122]
Criar ícones para nova seção BVS MTCI. Veja a BVS para ter referencia de cores, layout, etc: https://mtci.bvsalud.org/

Titulos:
Vitrinas del Conocimiento / Vitrines do Conhecimento / Windows of Knowledge
Mapas de Evidencia / Mapas de Evidência / Evidence Maps
Multimedia / Multimídia / Multimedia 
Webinars / Webinários / Webinars

Seguem algumas ideias, não precisa ser exatamente igual, e o ícone não necessariamente precisa ser uma imagem que represente o conteúdo...
- Queremos imagem e texto

![image](https://user-images.githubusercontent.com/13439949/190732154-5de1ce5b-8d60-4188-a4ee-a4e0efcda6fb.png)

![image](https://user-images.githubusercontent.com/13439949/190732332-c9e40afb-2abb-4654-bb4c-cd35979022fb.png)

![image](https://user-images.githubusercontent.com/13439949/190732957-c26cf3ff-bf50-49fe-8eaa-4d731d1f4137.png)

**Comment by marcioalvessilva** [comment]
Bom dia @sousajul 
Segue primeiros ícones, caso não seja aprovado me indique o que vc mais gosta que eu faço uma versão semelhante.

![image](https://user-images.githubusercontent.com/48724136/191979191-8566d05f-d5fa-4a19-be52-0882facb7699.png)

**Comment by sousajul** [comment]
@marcioalvessilva a equipe da BVS MTCI aprovou o modelo 2 (os botões vazados).

Algumas considerações:
1. A cor predominante da BVS é verde, você acha que esse azul está combinando?
2. Alterar os ícones dos botões "mapa de evidencias" e "vitrines do conhecimento", estamos usando os seguintes ícones para essas fontes, no entanto, dentro do modelo que vc propôs veja se tem algum mais próximo dessas opções:

![image](https://user-images.githubusercontent.com/13439949/192009628-8a787ce8-7f0b-4740-aad2-fed0df087ecf.png)

**Comment by marcioalvessilva** [comment]
**Link no GitHub**
https://github.com/bireme/artes-graficas/tree/main/bvs-mtci/JPG

**Exemplo**
![image](https://user-images.githubusercontent.com/48724136/192296268-753e755b-7470-4975-a2e3-129f6de71cef.png)

Por favor validar!

**Comment by sousajul** [comment]
@marcioalvessilva A coordenadora da BVS MTCI solicitou "suavizar" os ícones dos botões Vitrines do conhecimento e Mapas de Evidência pois estão diferentes do estilo dos outros dois e ela achou que ficou poluído, acho que não precisa usar exatamente esses ícones, como eu havia colocado no comments anterior "dentro do modelo que vc propôs veja se tem algum mais próximo dessas opções".

Consegue nos enviar uma nova proposta?

**Comment by marcioalvessilva** [comment]
Olá Juliana, desculpe a demora, estou avançando nos chamados aberto, encontrei esse que faltou finalizar, estou a disposição para concluír.
![image](https://user-images.githubusercontent.com/48724136/198045893-e1eedc67-f91d-4a97-85ee-012738eeb7f1.png)

**Comment by marcioalvessilva** [comment]
Em caso de modificações por favor reabrir o issue, continuo à disposição.
