### ISSUE TITLE
Criar imagem para fonte de informação da BVS SMS-SP

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#123]
Solicito criar imagem (card) para disponibilizar uma nova fonte de informação da BVS SMS-SP (https://sms.sp.bvs.br/).

Titulo: Segunda Opinião Formativa (SOF)

Seguir o modelo visual dos ícones já disponíveis:

![image](https://user-images.githubusercontent.com/13439949/191525521-bb2f3b5e-abab-4cd4-88ab-4126f38b101a.png)

**Comment by marcioalvessilva** [comment]
Boa tarde, validação para fazer o cadastro!
![SOF](https://user-images.githubusercontent.com/48724136/191543925-e07aa0d1-c0a2-43a5-8e31-7ba9c6842ede.png)

**Comment by sousajul** [comment]
@marcioalvessilva validado

**Comment by marcioalvessilva** [comment]
Bom dia!
posso colocar em qual posição?

**Comment by sousajul** [comment]
@marcioalvessilva pode ser antes do card Relatos de Experiências. Esse é o link se necessário: https://sms.sp.bvs.br/sof.

**Comment by marcioalvessilva** [comment]
Em produção!

**Comment by marcioalvessilva** [comment]
Finalizado!
