### ISSUE TITLE
Criar imagens para país Bahamas no Country Profile

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/artes-graficas#124]
@marcioalvessilva 

Favor disponibilizar 2 imagens (homepage e flag) para o país Bahamas que será utilizado no projeto Country Profile:

https://country-profile.bvsalud.org/

**Comment by marcioalvessilva** [comment]
**Mapa**
![bahamas](https://user-images.githubusercontent.com/48724136/192363523-5d973f9a-84e1-4bf4-881a-d1a54a2aa9f8.jpg)
**Bandeira**
![bahamas-flag](https://user-images.githubusercontent.com/48724136/192363525-a57c4093-1a6e-4a7b-933e-ccd6d67e6279.jpg)

**Comment by viniciusandrade** [comment]
Obrigado @marcioalvessilva imagens integradas no sistema.
