### ISSUE TITLE
Criar imagens para país Grenada no Country Profile

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/artes-graficas#125]
@marcioalvessilva

Favor disponibilizar 2 imagens (homepage e flag) para o país Grenada que será utilizado no projeto Country Profile:

https://country-profile.bvsalud.org/

**Comment by marcioalvessilva** [comment]
**Mapa**
![grenada](https://user-images.githubusercontent.com/48724136/192363042-3d4bba49-2c8f-4f92-94f9-cfe3da064c7c.jpg)

**Bandeira**
![grenada-flag](https://user-images.githubusercontent.com/48724136/192363046-0153e25d-c078-4658-b20f-b3c27c9ecc1b.jpg)

**Comment by viniciusandrade** [comment]
Obrigado @marcioalvessilva, imagens integradas no sistema.
