### ISSUE TITLE
Guias e manuais LILACS - aspas ao contrário

### ISSUE THREAD

**Issue by suelisuga** [bireme/artes-graficas#128]
@marcioalvessilva informo que talvez haja algum problema na CSS do site de Guias e Manuais da LILACS, pois as aspas aparecem algo contrário na tabela abaixo:

![image](https://user-images.githubusercontent.com/13105683/194141637-837df1fc-f187-49c0-8858-719de0377c54.png)

Imaginei que fosse na CSS pq no HTML continua sem nenhuma formatação:
![image](https://user-images.githubusercontent.com/13105683/194142351-47337d6b-ef94-4e4b-80a6-3764b8ddcbdc.png)

O problema não é de aspecto estético, mas de funcionalidade porque o usuário que copiar e colar o código na pesquisa da BVS pode não conseguir porque a aspas está ao contrário.

Duas linhas do PTB vinculadas:
BIR.02.04
Revisar, actualizar y mantener la plataforma tecnológica de la interfaz de búsqueda y recuperación BIR.02.04.03
BIR.01.04
Mantener la Metodología LILACS actualizada para garantizar calidad de datos en la base BIR.01.04.02

Obrigada!

Sueli

**Comment by suelisuga** [comment]
Para ciência estou citando @pintoros para ciência

**Comment by marcioalvessilva** [comment]
Por favor validar

https://lilacs.bvsalud.org/guias-e-manuais/docs/filtros-de-busca-para-tipos-metodologicos-de-estudo-na-metodologia-lilacs/notas-tecnicas/02-22-campos-de-dados-da-metodologia-lilacs-utilizados-para-pesquisa-na-interface-de-pesquisa-iahx-do-portal-regional-da-bvs/


Para corrigir esse problema eu inserir uma tag **_`<pre>texto</pre>`_** essa tag mantem o texto da forma como é digitado.
**Ex do código:**
Antes
`<td>id:"biblio-1372800"</td>`
Alterada
`<td><pre>id:"biblio-1372800"</pre></td>`

**Comment by marcioalvessilva** [comment]
Concluído!
Qualquer dúvida fico à disposição.
