### ISSUE TITLE
Guias e manuais LILACS - letras sobrepostas

### ISSUE THREAD

**Issue by suelisuga** [bireme/artes-graficas#130]
Solicito apoio para melhoria da visualização da informação nos menus dos guias e manuais da LILACS. Atualmente as letras estão sobrepostas e isso gera dificuldade de leitura.

![image](https://user-images.githubusercontent.com/13105683/194416993-666888de-f403-44af-96bb-d20c4a3a0f88.png)

Obrigada!

**Comment by marcioalvessilva** [comment]
Solução CSS Inserida, por favor validar
https://lilacs.bvsalud.org/guias-e-manuais/docs/curso-avancado-de-indexacao-de-documentos/ferramentas-da-indexacao/

**Comment by suelisuga** [comment]
ficou show @marcioalvessilva !! Obrigada!!
