### ISSUE TITLE
Acessibilidade no portal LILACS - microfone

### ISSUE THREAD

**Issue by suelisuga** [bireme/artes-graficas#131]
Pf implantar módulo de acessibilidade com uso de voz (microfone)
![image](https://user-images.githubusercontent.com/13105683/195861967-e0e5d0c0-917b-4bec-b6ad-ad1e74f86adc.png)

Igual:
![image](https://user-images.githubusercontent.com/13105683/195862127-b1a9ad46-55ff-40ca-b4c2-c9cfb39a875e.png)

Obrigada!

**Comment by marcioalvessilva** [comment]
Inserido na produção.
![image](https://user-images.githubusercontent.com/48724136/197013075-b77ac9c6-7ef8-4449-8a25-0634f064fc05.png)

**Comment by suelisuga** [comment]
show Marcio!! OBrigada!
