### ISSUE TITLE
Incluir no https://logos.bireme.org/ a versão do logo da LILACS sem o termo metodologia

### ISSUE THREAD

**Issue by suelisuga** [bireme/artes-graficas#132]
Pf incluir logo da LILACS para adobe illustrator (extensão .ai) sem o termo Metodologia.

Foi nos informado que o logo disponivel é o da Metodologia LILACS e não da LILACS.

Obrigada!
Sueli

**Comment by marcioalvessilva** [comment]
@suelisuga conforme informado aguardo texto dos logos LILACS nos três idiomas (Metodologia LILACS)

**Comment by marcioalvessilva** [comment]
@suelisuga , por favor validar.
Obs: apenas na versão Illustrator

**PT**
![image](https://user-images.githubusercontent.com/48724136/202441189-7bb7eb1e-a763-4e7c-9f19-ec44aee00a41.png)

**ES**
![image](https://user-images.githubusercontent.com/48724136/202441296-406ef537-1feb-453a-9961-cb544f321741.png)

**EN**
![image](https://user-images.githubusercontent.com/48724136/202441109-3f31b8b5-d17c-422c-b715-c2d8e4c39e6c.png)

**Comment by suelisuga** [comment]
Validados @marcioalvessilva . Pf publicar no portal logos.bireme.org. Eu sempre indico esse portal para coordenadores, centros cooperantes  e consultores. obrigada!

**Comment by suelisuga** [comment]
@marcioalvessilva temos esses logos com fundo transparente?

**Comment by marcioalvessilva** [comment]
@suelisuga logos inseridos em png sem fundo e jpg.
Eu abrir um chamado para atualizar na produção.

**Comment by suelisuga** [comment]
@marcioalvessilva obrigada!
