### ISSUE TITLE
Refazer imagens no portal CNS

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#134]
Marcio como falamos, solicito substituis as imagens atuais por novas de acordo com os temas:

Quatro seções maiores

a.       RESOLUÇÕES/RECOMENDAÇÕES/MOÇÕES

b.       NOTAS TÉCNICAS

c.       ATAS DO PLENO CNS

d.       PUBLICAÇÕES DO CONTROLE SOCIAL

2.       Seis seções menores

a.       CONFERÊNCIAS DE SAÚDE

b.       FINANCIAMENTO DO SUS

c.       EQUIDADE E DIREITO À SAÚDE (aqui entram os temas: Saúde das mulheres; Saúde Indígena; Ciclos de vida; Patologias; Pessoas com Deficiência; Equidade e Saúde Mental)

d.       ATENÇÃO À SAÚDE (aqui entram: Atenção Básica; Alimentação e Nutrição; Ciência, Tecnologia e AF; Práticas Integrativas; Saúde Bucal; Saúde Suplementar e Vigilância em Saúde)

e.       TRABALHO EM SAÚDE (aqui entram: Recursos Humanos e Relações do Trabalho e Saúde do trabalhador e da trabalhadora)

f.        ESTUDOS E EDUÇÃO PARA O CONTROLE SOCIAL (aqui entram: Estudos e Educação Permanente para o Controle Social)

**Comment by marcioalvessilva** [comment]
Sugestão de imagens - fico no aguardo de sugestões e referência caso alguma imagens não seja aprovada!

### **Modelo**
![image](https://user-images.githubusercontent.com/48724136/203556549-8755e555-8d60-45dc-aadb-d68a087140af.png)

### **Primeira Seção**
![1](https://user-images.githubusercontent.com/48724136/203556704-5d3c6128-c4ef-435a-8443-1e9b2ccac4c1.jpg)
![2](https://user-images.githubusercontent.com/48724136/203556709-22a8e2b0-5f53-4478-83c7-ad1b21e1fb67.jpg)
![3](https://user-images.githubusercontent.com/48724136/203556712-9ad9b438-1f2a-43de-9578-585b577bb977.jpg)
![4](https://user-images.githubusercontent.com/48724136/203556713-7c607ee3-54d0-4779-8531-780fda689a1c.jpg)

### **Segunda Seção**
![a](https://user-images.githubusercontent.com/48724136/203556686-19384f38-6ff4-4cf2-bc25-c4ac742aa620.png)
![b](https://user-images.githubusercontent.com/48724136/203556689-8f33e25b-c481-4425-8fb9-ca7a3cc80f7e.png)
![c](https://user-images.githubusercontent.com/48724136/203556693-6fca5ebb-d1ea-42bf-8377-2597cdd838b0.png)
![d](https://user-images.githubusercontent.com/48724136/203556695-b1f183e7-a046-4299-bbb9-b306849e45df.png)
![e](https://user-images.githubusercontent.com/48724136/203556696-c1f8bb0e-54a5-4224-9154-7dea17b7d3b3.png)
![f](https://user-images.githubusercontent.com/48724136/203556697-c6b31d10-bb15-488f-80a9-9c5040448862.png)

**Comment by sousajul** [comment]
@marcioalvessilva para as imagens da primeira seção, considerar:
1. RESOLUÇÕES/RECOMENDAÇÕES/MOÇÕES -  utilizar imagens que remetam a documentos, papeis, imagens com listagem (para recomendações), etc.

2. PUBLICAÇÕES DO CONTROLE SOCIAL - utilizar imagens com publicações e pessoas (que remeta ao controle social)

Para os ícones da segunda seção, considerar:
1. CONFERÊNCIAS DE SAÚDE - ícones próximos a estes
![image](https://user-images.githubusercontent.com/13439949/203569298-f98d9528-d8e9-4cbe-9576-2eddbe8a700e.png)
![image](https://user-images.githubusercontent.com/13439949/203569484-52507e17-e2d0-4595-b92b-aefc6a6da4e9.png)

2. ESTUDOS E EDUÇÃO PARA O CONTROLE SOCIAL - ícones de estudos, livros + pessoas


Veja se é possível.
Abraços,

**Comment by marcioalvessilva** [comment]
Olá @sousajul esta bem difícil encontrar imagens para esses titulos, caso tenha alguma sugestão me passa o link https://br.depositphotos.com/ pode pesquisar nesse link eu recorto e coloco nesse formato

### **Seção1**
Para RESOLUÇÕES/RECOMENDAÇÕES/MOÇÕES eu entendo que são coisas acordadas por isso sugeri a imagem anterior
V1
![1b](https://user-images.githubusercontent.com/48724136/203624452-5f294e21-456f-4287-8e29-aa27af831a4c.jpg)
V2
![1c](https://user-images.githubusercontent.com/48724136/203624457-d5c2db0f-eca2-450a-af51-309307808044.jpg)


Para PUBLICAÇÕES DO CONTROLE SOCIAL - eu entendi que era uma forma me mapear pessoas, por isso a imagem sugeria anteriormente
![4b](https://user-images.githubusercontent.com/48724136/203624782-f8570709-31e8-423c-b60d-f3f97e8350c2.jpg)
nt.com/48724136/203624401-de946c0f-53ad-41f3-8da0-c089e28be95a.png)

 
### **Seção 2**

![f](https://user-images.githubusercontent.com/48724136/203624398-240a2601-fe58-4892-8355-2df161cebcd4.png)
![a](https://user-images.githubuserconte


Fico no aguardo!

**Comment by sousajul** [comment]
@marcioalvessilva 

Márcio como sugestão:

RESOLUÇÕES/RECOMENDAÇÕES/MOÇÕES: São publicações, achei que a primeira versão estava evidenciando mto as pessoas, por isso sugeri algo mais de documentos. Como segue:
https://br.depositphotos.com/84527936/stock-photo-business-people-handshake-sitting-at.html

PUBLICAÇÕES DO CONTROLE SOCIAL - São publicações sobre este tema, e não o controle social em si...veja o que acha dessa:
https://br.depositphotos.com/102145776/stock-photo-book-of-fantasy-stories.html

O link das últimas imagens estão quebrados, não consigo ver.

**Comment by sousajul** [comment]
Esse icone (https://user-images.githubusercontent.com/48724136/203624398-240a2601-fe58-4892-8355-2df161cebcd4.png) remete mais à apresentações do que conferencia, plenaria...

**Comment by marcioalvessilva** [comment]
### **Seção 1**
![1](https://user-images.githubusercontent.com/48724136/203764440-27270ca4-84fa-4a2b-88a5-20faf4c1b8f8.jpg)
![4](https://user-images.githubusercontent.com/48724136/203764444-cff3607a-adbb-4102-95e2-a59ef73d97eb.jpg)

**Comment by sousajul** [comment]
@marcioalvessilva ok para as imagens da primeira seção.

Ficou faltando os ícones, no comentário anterior só apareceu um ícone o outro, o link estava quebrado.
CONFERÊNCIAS DE SAÚDE
ESTUDOS E EDUÇÃO PARA O CONTROLE SOCIAL

**Comment by marcioalvessilva** [comment]
![f](https://user-images.githubusercontent.com/48724136/203837932-801bd7ee-d18b-4556-8026-f399e1b110e1.png)
![a](https://user-images.githubusercontent.com/48724136/203837933-f248c9f1-c8d8-4dc2-a64d-fb6168b40601.png)

**Comment by marcioalvessilva** [comment]
![f](https://user-images.githubusercontent.com/48724136/203845261-51493fd4-5c87-4293-8f4f-c50543f2f66a.png)
![a](https://user-images.githubusercontent.com/48724136/203845264-c5bb3009-72bf-4b12-9639-fcdec278b3ef.png)

**Comment by sousajul** [comment]
Validado e imagens já substituídas no portal.
