### ISSUE TITLE
Criar flyer Mapeamento das Medicinas Tradicionais Complementares e Integrativas na AL&C

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/artes-graficas#138]
Marcio, boa tarde, 

Precisamos de sua colaboração para criação de uma arte gráfica para divulgar um evento promovido pela OPAS/OMS Brasil e nós. Segue o texto base. Nosso prazo como sempre está apertado. Gostaríamos de até 6a feira já está divulgando. 

A Representação OPAS/OMS Brasil convida 

Webinário “Projeto de Mapeamento das Medicinas Tradicionais Complementares e Integrativas”  

Lançamento de novos Mapas de Evidências efetividade clínica das Práticas Integrativas e Complementares em Saúde (PICS) 

Dia 13 de dezembro às 16 horas (hora de Brasília) 

Evento público, Via Zoom <link curto> 

Objetivos:  

- Divulgação dos dados da 1ª fase do Projeto de Mapeamento das Medicinas Tradicionais Complementares e Integrativas nas Américas, 

- Apresentação dos novos Mapas de Evidências sobre efetividade clínica das PICS que contribuem para o fortalecimento do SUS por meio da Política Nacional de Práticas Integrativas e Complementares (PNPIC). 

 

 (LOGOS) 

BIREME/OPAS/OMS      FIOCRUZ-OBSERVAPICS               CABSIN 

Rede MTCI Américas     Rede PICS

**Comment by marcioalvessilva** [comment]
Concluído!
https://github.com/bireme/artes-graficas/tree/main/mapeamento-medicinas/JPG
![image](https://user-images.githubusercontent.com/48724136/206523194-376f2a7d-3021-405a-a9e9-5c1558ef0ba5.png)

**Comment by sousajul** [comment]
@marcioalvessilva conforme solicitação da Veronica, incluir link do youtube (https://www.youtube.com/@ObservaPICS) na imagem de destaque.
