### ISSUE TITLE
Criar banner portal regional 

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/artes-graficas#139]
@pintoros segue banners para o portal regional, qualquer modificação por favor me avisar

Link GitHub
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/mapeamento-das-medicinas/JPG/mapeamento-das-medicinas.jpg

![image](https://user-images.githubusercontent.com/48724136/206527860-e0722a05-dd55-44e3-a3a3-9201dcf70175.png)

**Comment by pintoros** [comment]
Ok. publicado. Obrigada

**Comment by pintoros** [comment]
Boa tarde @marcioalvessilva, a Verônica solicitou atualizar a informação do youtube também no banner para o portal regional:

evento público no Youtube
https://www.youtube.com/@ObservaPICS

Obrigada

**Comment by marcioalvessilva** [comment]
Imagem Atualizada
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/mapeamento-das-medicinas/JPG/mapeamento-das-medicinas.jpg
