### ISSUE TITLE
Criar artes com o programa da comemoração dos 35 anos do DeCS/MeSH

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/artes-graficas#14]
Criar artes com o programa da comemoração dos 35 anos do DeCS/MeSH

Formatos desejados
- Facebook
- Twitter

![image](https://user-images.githubusercontent.com/48724136/130469389-a7ccdfc0-b1a8-44ed-a8e3-a49fff45a403.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva ok. Valide-o com a Hendrix e Dr. Diego, por favor.

**Comment by marcioalvessilva** [comment]
Segue link das artes do Convite e Programa DeCS para os 35 anos nos três idiomas
https://github.com/bireme/artes-graficas/tree/main/decs-mesh/35-anos/jpg

Link será enviado por e-mail para  Hendrix e Dr. Diego.

**Comment by renatomurasaki** [comment]
@marcioalvessilva muito bom! obrigado

**Comment by marcioalvessilva** [comment]
Artes de divulgação criadas!
https://github.com/bireme/artes-graficas/tree/main/decs-mesh/35-anos/jpg
