### ISSUE TITLE
Imagens para Vitrine MTCI

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#140]
Tradução das imagens (link abaixo) para os idiomas abaixo

Links das imagens na área de mídias da vitrine - (info de acesso enviada por email)
http://mtci.bvsalud.org/vitrinas/wp-content/uploads/2021/11/simposio.png
http://mtci.bvsalud.org/vitrinas/wp-content/uploads/2021/11/videos.png
http://mtci.bvsalud.org/vitrinas/wp-content/uploads/2021/11/info.png

Pf ajustar o fundo do label para verde, no tom da vitrine:
https://mtci.bvsalud.org/vitrinas/pt/post_vitrines/contribuicoes-das-medicinas-tradicionais-complementares-e-integrativas-mtci-no-contexto-da-pandemia-da-covid-19/

Traduções que faltam:

Simpósios
Symposia
Vídeos
Infografías
Infographics

Obrigada

**Comment by marcioalvessilva** [comment]
### **Infográfico**
![Infographics-en](https://user-images.githubusercontent.com/48724136/207066028-d54bf2e3-ef04-4698-8279-c5a9f941026d.jpg)
![infograficos-pt](https://user-images.githubusercontent.com/48724136/207066027-7fb53c1a-804b-4f37-8d8b-96e64ce32275.jpg)
![infografías-es](https://user-images.githubusercontent.com/48724136/207066023-f3354965-3e66-4e62-85ca-a4bf345265b7.jpg)

### **Vídeos**
![videos](https://user-images.githubusercontent.com/48724136/207066020-e5ae3886-a444-4609-bb26-47e6610c5038.jpg)
![videos-en](https://user-images.githubusercontent.com/48724136/207066021-037b55ff-62e8-403d-b099-a3bcef23a3c3.jpg)


### **Simpósios**
![Simpósios-es](https://user-images.githubusercontent.com/48724136/207066030-1b9b0b44-826d-47a4-ba36-8ce30668d56a.jpg)
![simposios-pt](https://user-images.githubusercontent.com/48724136/207066009-54be20c3-109a-4aa4-88f3-4f7f4168005b.jpg)
![symposia-en](https://user-images.githubusercontent.com/48724136/207066017-e5d162d8-3c14-4fb8-9fd9-91a5507f8a22.jpg)

**Comment by pintoros** [comment]
Perfeito Márcio!

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:a6ef76a9-c555-43c9-963e-b6f95dbaa540]

________________________________
De: Márcio Alves ***@***.***>
Enviado: segunda-feira, 12 de dezembro de 2022 11:11
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Imagens para Vitrine MTCI (Issue #140)


Infográfico

[Infographics-en]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F207066028-d54bf2e3-ef04-4698-8279-c5a9f941026d.jpg&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903031676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dpk4Ttwe2bjWxM8ug8SQXl8NPcrcR0X%2BMQZEi8XPieg%3D&reserved=0>
[infograficos-pt]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F207066027-7fb53c1a-804b-4f37-8d8b-96e64ce32275.jpg&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903031676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xLsoS5%2FCCwLvtP%2FeTKLP167c4XcFSLVa2lsc32GTVss%3D&reserved=0>
[infografías-es]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F207066023-f3354965-3e66-4e62-85ca-a4bf345265b7.jpg&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903031676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2Ul8XotIAzNzZb8ksezDEY0WPDze79wKRDcqzGtJ9q4%3D&reserved=0>

Vídeos

[videos]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F207066020-e5ae3886-a444-4609-bb26-47e6610c5038.jpg&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903031676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dzNYh9q2yoUxuTfcV6WZLvu%2B2SLWThA0lr5SCoTvdcg%3D&reserved=0>
[videos-en]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F207066021-037b55ff-62e8-403d-b099-a3bcef23a3c3.jpg&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903187886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jGDfm3%2BxvjxijjPJiB%2Ftps6wfbhZIeaaMBftO1DQHOc%3D&reserved=0>

Simpósios

[Simpósios-es]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F207066030-1b9b0b44-826d-47a4-ba36-8ce30668d56a.jpg&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903187886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nhxNw5nJGSDh1Eeh0qloA12l7KbX4dSL6wFhBrvkxxE%3D&reserved=0>
[simposios-pt]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F207066009-54be20c3-109a-4aa4-88f3-4f7f4168005b.jpg&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903187886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=i5FCD7D6p6hBt8qFpFwAGKcfNF4mzIr%2BvtARW%2Fvwr9A%3D&reserved=0>
[symposia-en]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F207066017-e5d162d8-3c14-4fb8-9fd9-91a5507f8a22.jpg&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903187886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ye59hnE9wNS8aQx5mAAD8z3rbjCJoNkIqOUdDwA1mpA%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F140%23issuecomment-1346576939&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903187886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7iYiZVYcWvR1tw9tZdf%2BryT9Oj3TYhIZhrn%2FxmQzOF4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4GKWEYGG3MF3UWSW73WM4XA3ANCNFSM6AAAAAASYTFVIE&data=05%7C01%7Cpintoros%40paho.org%7C1a3fb738f76a43d2e45608dadc4ac200%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638064510903187886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fbrumm%2BiRIqJVCx6ahumfjnemmdsGodtYRSfpuVgVgE%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
