### ISSUE TITLE
Novos Mapas de Evidencias

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/artes-graficas#141]
Novos Mapas de Evidencias

No GitHub
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/mapa-de-evidencia/JPG/novos-mapas-pt.jpg
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/mapa-de-evidencia/JPG/novos-mapas-es.jpg
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/mapa-de-evidencia/JPG/novos-mapas-en.jpg

![image](https://user-images.githubusercontent.com/48724136/207355352-0a8c7390-63dd-45c1-937a-39b2d2c9422e.png)
![image](https://user-images.githubusercontent.com/48724136/207355383-8a8d619f-081e-4e2d-a174-b52d823e8301.png)
![image](https://user-images.githubusercontent.com/48724136/207355425-55e6478b-7d3e-44c8-8845-641a355f42be.png)

**Comment by pintoros** [comment]
Márcio, falta acento circunflexo em evidências no PT

Obrigada!

**Comment by marcioalvessilva** [comment]
Atualizado!
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/mapa-de-evidencia/JPG/novos-mapas-pt.jpg

![image](https://user-images.githubusercontent.com/48724136/207437451-ca1ce737-df21-4c9b-b014-44cafc55aa67.png)

**Comment by marcioalvessilva** [comment]
Finalizado!
