### ISSUE TITLE
No portal CNS Substituir "Notas Técnicas" por "CNS contra a Covid-19"

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#143]
Márcio criar nova imagem para substituir  "Notas Técnicas" por "CNS contra a Covid-19"

![image](https://user-images.githubusercontent.com/13439949/208479732-9ad7c284-d944-4318-a262-a4de7a0c1699.png)

**Comment by marcioalvessilva** [comment]
![2-nova-c](https://user-images.githubusercontent.com/48724136/208681337-2cb9f419-ab96-480e-a638-69a37611f00b.jpg)
![2-nova-a](https://user-images.githubusercontent.com/48724136/208681341-408b06a1-d873-498f-9f11-531a2c1a47f9.jpg)
![2-nova-b](https://user-images.githubusercontent.com/48724136/208681343-0d852f74-8209-4e88-91df-d0747b795740.jpg)

**Comment by marcioalvessilva** [comment]
Finalizado!
