### ISSUE TITLE
Destaque para o Portal regional - janeiro 1

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#144]
Por favor Márcio, poderia montar o banner para  o regional com o seguinte destaque:

Curso en línea:
Acceso y uso de la Información Científica en salud
¡Versión revisada y actualizada!

Online course: 
Access and Use of Scientific Information in Health
Revised and updated version!

Curso online:
Acesso e Uso da Informação Científica em Saúde
Versão revisada e atualizada!

![curso-pt](https://user-images.githubusercontent.com/29313904/210848249-8d66c034-4e96-4fa2-8573-90b336690dc3.jpg)
![curso-en](https://user-images.githubusercontent.com/29313904/210848255-33799057-77ab-464b-8851-d0b709baffa6.png)
![curso-es](https://user-images.githubusercontent.com/29313904/210848257-e13ea103-50d3-44bb-b3fa-e74058312389.png)

Copio a arte dos banners de cada um para inspiração:

**Comment by marcioalvessilva** [comment]
Link no GitHub
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/acesso-e-uso-da-informa%C3%A7%C3%A3o/JPG


EN
![image](https://user-images.githubusercontent.com/48724136/211009508-43cfec14-07c5-4fd8-a0e4-6eb57f7ba69c.png)

ES
![image](https://user-images.githubusercontent.com/48724136/211011546-5ab08a5d-f517-44be-b88e-892150777f8c.png)


PT
![image](https://user-images.githubusercontent.com/48724136/211009567-f21f6da4-271b-49a9-9ab3-709450e18471.png)

**Comment by pintoros** [comment]
publicado
