### ISSUE TITLE
Destaque para o Portal Regional janeiro 2

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#145]
Márcio, segue o segundo destaque:

Objetivos de Desenvolvimento Sustentável-ODS 3: Saúde e Bem-Estar
Você pode acessar as Vitrines do Conhecimento estão sendo desenvolvidas para cada Meta

Sustainable Development Goals-SDG 3: Health and Well-Being
You may access the Windows of Knowledge that are being developed on each of the Goals

Objetivos de Desarrollo Sostenible-ODS 3: Salud y Bienestar
Puedes acceder a las Vitrinas de Conocimiento que se están desarrollando para cada Meta

Imagens para inspirar
![Não-mover-Redimensionar-site-1100x619](https://user-images.githubusercontent.com/29313904/210872149-e1eca359-9e4f-4390-9142-1f4b3d207fe0.png)
![1200px-Sustainable_Development_Goal-es-15](https://user-images.githubusercontent.com/29313904/210872155-399f505d-ae6b-4ed3-8f7b-b80bdc9d0aa0.jpg)

![maxresdefault](https://user-images.githubusercontent.com/29313904/210872651-01377552-d5d0-49dd-b202-f33c17f23d1d.jpg)

**Comment by marcioalvessilva** [comment]
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/ods-3/JPG

PT
![image](https://user-images.githubusercontent.com/48724136/211014917-7f39187c-0f46-4df7-af5a-3a8f498e1678.png)

ES
![image](https://user-images.githubusercontent.com/48724136/211014946-bb764136-0b90-4c1b-9e4a-a695981d75b7.png)


EN
![image](https://user-images.githubusercontent.com/48724136/211015005-1be2f9ce-d0e4-4404-89a1-86044e476857.png)

**Comment by pintoros** [comment]
Márcio, faltou um "que" na frase em pt. Se der tempo eu prefiro que inverta os tamanhos das frases, a primeira com mais destaque e a 2a, que com letra menor.

Obrigada

**Comment by marcioalvessilva** [comment]
![image](https://user-images.githubusercontent.com/48724136/211072319-75a16f43-49b5-40fd-8698-57b233d59222.png)


![image](https://user-images.githubusercontent.com/48724136/211072348-80c286ca-5033-4f42-a768-12912ad862a9.png)


![image](https://user-images.githubusercontent.com/48724136/211072389-9e6d0085-706c-4d6c-8b67-82afdc09d839.png)

**Comment by pintoros** [comment]
Obrigada. Aprovado!
