### ISSUE TITLE
Destaque para o Portal Regional janeiro 3

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#146]
Como pesquisar na BVS? 
Conheça os recursos disponíveis para ajudá-lo na busca e recuperação de informação

¿Cómo buscar en la BVS?
Conozca los recursos disponibles para ayudarlo en la búsqueda y recuperación de información

How to search in the VHL?
Get to know the resources available to help you in the search and retrieval of information

**Comment by marcioalvessilva** [comment]
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/como-pesquisar/JPG

EN
![image](https://user-images.githubusercontent.com/48724136/211027554-54cd4f03-35f5-44cf-aece-0075317e1ef9.png)


ES
![image](https://user-images.githubusercontent.com/48724136/211027608-d60bf3b9-7876-4274-ba3f-03397dee610f.png)


PT
![image](https://user-images.githubusercontent.com/48724136/211027665-867d0ea8-a24a-423d-a1a5-4c8415fa078d.png)

**Comment by pintoros** [comment]
publicado
