### ISSUE TITLE
Banner curso avançado de CCS nos formatos TW, FB e Portal regional 

### ISSUE THREAD

**Issue by liliancalo** [bireme/artes-graficas#147]
![image](https://user-images.githubusercontent.com/85634970/216065885-5bde5813-36b7-49dd-99a9-d0e6f1db3f90.png)

**Comment by marcioalvessilva** [comment]
Seguem Artes 
**Twitter e Facebook**
https://github.com/bireme/artes-graficas/blob/main/comunicacao-cientifica/JPG/twitter-es.jpg
https://github.com/bireme/artes-graficas/blob/main/comunicacao-cientifica/JPG/facebook-es.jpg

**Portal Regional**
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/comunicacao-cientifica/JPG/cacccs-es.jpg

Por favor validar!

**Comment by marcioalvessilva** [comment]
Concluído!
