### ISSUE TITLE
Destaque Vitrine Yanomami

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#149]
@Márcio, vc poderia melhorar a arte de destaque (Portal Regional) para Vitrine Yanomami que foi feita a "toque de caixa" pelo Mori nas suas férias? 
Também preciso de uma imagem para incluir o destaque nos sites (outras BVS e redes sociais)

Obrigada

A informação só em pt é:

Vitrine do Conhecimento  
Emergência Sanitária no Território Yanomami (em letra mais destacada)
Informação relevante para os profissionais de saúde (em letra menor)

**Comment by marcioalvessilva** [comment]
Por favor validar
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/Yanomami/JPG/yanomami.jpg
![image](https://user-images.githubusercontent.com/48724136/216679014-4bf79335-085c-4f10-b7c1-f1574eebb781.png)

**Comment by pintoros** [comment]
Oi Márcio,

A arte está bonita, mas tenho receio que esse desenho do cocar não represente a etnia indígena do Brasil. Lembra o cocar dos indígenas norte americanos.



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:0b0cb69d-16d9-4d0c-8b6f-0405f0df202f]

________________________________
De: Márcio Alves ***@***.***>
Enviado: sexta-feira, 3 de fevereiro de 2023 15:25
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Destaque Vitrine Yanomami (Issue #149)


Por favor validar
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/Yanomami/JPG/yanomami.jpg<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fblob%2Fmain%2Fbanners-sites%2Fregional%2FYanomami%2FJPG%2Fyanomami.jpg&data=05%7C01%7Cpintoros%40paho.org%7C74f0e09e68a3411fe5c008db06141163%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638110455489700184%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bFKT%2BD7nid3mv%2FdCMuiYQYWuH5kJlYA415M%2B%2FOR%2BHRw%3D&reserved=0>
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F216679014-4bf79335-085c-4f10-b7c1-f1574eebb781.png&data=05%7C01%7Cpintoros%40paho.org%7C74f0e09e68a3411fe5c008db06141163%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638110455489700184%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t0cig8yH4jdQv1nfSqWvXuGxgOSdG4%2Fkg9AFCmVuvsM%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F149%23issuecomment-1416242379&data=05%7C01%7Cpintoros%40paho.org%7C74f0e09e68a3411fe5c008db06141163%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638110455489700184%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FEcilpFaMXTpKW8pH85%2Fm6AdswsNwFn4FcI9rePrVXY%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4DRC7PNGQDIIQZUYD3WVVESRANCNFSM6AAAAAAUPPBLH4&data=05%7C01%7Cpintoros%40paho.org%7C74f0e09e68a3411fe5c008db06141163%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638110455489700184%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BYg3eKRjYmMSgkXWD0YwBA09aY%2B6CD8urLoyqefycSc%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Nova Imagem
![image](https://user-images.githubusercontent.com/48724136/216694712-b75ac4d1-5634-4994-86a7-b2214c9f6b37.png)

**Comment by pintoros** [comment]
Ótimo!

Obrigada!

Já vou trocar o que está lá.





Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:d5bcfd0a-aace-4342-aed9-72c29b16bdc5]

________________________________
De: Márcio Alves ***@***.***>
Enviado: sexta-feira, 3 de fevereiro de 2023 16:50
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Destaque Vitrine Yanomami (Issue #149)


Nova Imagem
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F216694712-b75ac4d1-5634-4994-86a7-b2214c9f6b37.png&data=05%7C01%7Cpintoros%40paho.org%7C542b4c19ead8420b8afc08db061fedc3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638110506440995247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a2EA2VaIHLEdvFLkxScb%2FLmZycsyx19Eujtuk7zwXG4%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F149%23issuecomment-1416331426&data=05%7C01%7Cpintoros%40paho.org%7C542b4c19ead8420b8afc08db061fedc3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638110506440995247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=goC2J%2F%2F5jap88tX7KvM7HW90YRlLyShC8wLwA%2F545vQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BG2GHUFXPNQDJUEVDWVVOQ7ANCNFSM6AAAAAAUPPBLH4&data=05%7C01%7Cpintoros%40paho.org%7C542b4c19ead8420b8afc08db061fedc3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638110506440995247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=i8ur4jQTOcs0AwLc2iT4AU3n7JYMXSgPiEpuBY7tqnk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Atualizada!
https://github.com/bireme/artes-graficas/blob/main/banners-sites/regional/Yanomami/JPG/yanomami.jpg

![image](https://user-images.githubusercontent.com/48724136/216703908-803281d8-f5fd-45e3-86a1-49f941ce78b9.png)

**Comment by marcioalvessilva** [comment]
Finalizado!
