### ISSUE TITLE
Vitrine Promoción de la Salud - ajustes

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#151]
**Cores** - ajustei a aranha para o verde que eu tinha usado anteriormente para que fique como referência
Elas pediram detalhes nos tons da imagem central (terra alaranjado ou outro), principalmente na área de países. Para não ficar tão monocromático. 

Também sugiro um tom mais forte na letra, pode ser um verde da mesma paleta, só que mais forte que o tom de fundo, para não ficar tudo igual. 

---------------------------------------

**Icones da aranha** - ajustar/criar:

-Escuelas Promotoras de la Salud - crianças mais baixas e em número de 3 
Jovens (como grupo)

-Universidades Saludables - Grupo de jovens para não caracterizar casal

-Criar um ícone para Participação Social, que será aplicado em alguns dias para um novo documento na aranha. 
Ideia: Grupo de mãos levantadas em diferentes alturas.

----------------------------------------------------

**Área de países:**

O local que vai ficar o link para os documentos de cada área precisa chamar uma pouco mais de atenção, pois será referência e na maioria das vezes, será um único link para a BVS. No lugar da palavra link, provavelmente estará escrito: _Acceder los documentos_. Pensei em um negrito, ou um bullet que não fosse a bolinha. Algo que salte aos olhos, como um título.

*****Alterações que estão previstas no conteúdo referente a países, após o meio e até o final desse ano:

-Há possibilidade de crescer até 35-40 países, mas gostariam de manter esse desenho (mostrando até 20 como hoje) e ir incluindo os novos países a medida que os documentos forem propostos, por isso pediram para verificar a possibilidade de rolagem da barra de países a esquerda. Se não for possível, precisaremos de uma outro solução, o mais similar possível a essa, pq gostaram bastante da navegação com a barra lateral dos países.

-Também pode ser que seja necessário incluir mais 2 ou 3 áreas ao lado dos países.

A discussão foi longa depois que vc saiu sobre esse tema. Segue o link da gravação: https://paho-my.sharepoint.com/:v:/r/personal/pintoros_paho_org/Documents/Recordings/seguimiento%20vitrina-20230310_120122-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?csf=1&web=1&e=q6bUco

----------------------------------------------------
Criar uma área logo abaixo da área de países. Pediram como uma linha, onde será incluído um link para um formulário, com a seguinte frase:
_Para proponer un nuevo documento pincha aquí_

**Comment by marcioalvessilva** [comment]
@marcioalvessilva, ficou pendente apenas esse item 
Criar um ícone para Participação Social, segue sugestão.

![image](https://user-images.githubusercontent.com/48724136/226406319-48b76875-fd2a-4cc2-ac8a-32f0657668e3.png)

Abraço!

**Comment by pintoros** [comment]
@da Silva, Marcio ***@***.***> eu achei perfeito. 😉

Vou encaminhar a atual proposta para validarem.

Obrigada!

________________________________

Rosemeire Rocha Pinto, Bibliotecária, MS
BIREME<https://www.paho.org/en/bireme> EIH PAHO WHO<https://www.paho.org/en/evidence-and-intelligence-action-health>


[cid:e5824113-9de1-4c24-8d97-57e9940fb597]

________________________________
De: Márcio Alves ***@***.***>
Enviado: segunda-feira, 20 de março de 2023 13:31
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Vitrine Promoción de la Salud - ajustes (Issue #151)


@marcioalvessilva<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcioalvessilva&data=05%7C01%7Cpintoros%40paho.org%7C6e0f6aa1c35a4e7f380508db29609e36%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638149267185630739%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TlkQSvXpbGXgpQjtV5mT2C92gqAXmktTmXNW5LCwDEE%3D&reserved=0>, ficou pendente apenas esse item
Criar um ícone para Participação Social, segue sugestão.

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F226406319-48b76875-fd2a-4cc2-ac8a-32f0657668e3.png&data=05%7C01%7Cpintoros%40paho.org%7C6e0f6aa1c35a4e7f380508db29609e36%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638149267185630739%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fc7SHxYLzLtCJKaT3ooGmLuX4swq%2BEv3B6TTJvkjzNA%3D&reserved=0>

Abraço!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F151%23issuecomment-1476565676&data=05%7C01%7Cpintoros%40paho.org%7C6e0f6aa1c35a4e7f380508db29609e36%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638149267185630739%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8baqZrzJNiKxh3KSNpijK0%2FqMDBiUAf%2FZHjii3XlkAc%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4DD5WAWQENP37B5AJDW5CA7VANCNFSM6AAAAAAVW3DZBY&data=05%7C01%7Cpintoros%40paho.org%7C6e0f6aa1c35a4e7f380508db29609e36%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638149267185630739%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EOKW3Gsrk5RPNw%2FnnUQ9uMmZguAQQ%2BQH4HbMzZ%2BF6bE%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Finalizado!

**Comment by pintoros** [comment]
@marcioalvessilva e @marcoslmori na ultima reunião a contraparte apontou alguns ajustes (PPT anexo). Precisa de ajuste das imagens dos países. No demais, talvez Mori e eu, qdo voltar de férias, possamos ajustar diretamente.
Sugiro que enviem as novas imagens para aprovação pela contraparte antes de subir na vitrine. 
[
[Cambio imagens-layout.pptx](https://github.com/bireme/artes-graficas/files/11517527/Cambio.imagens-layout.pptx)
](url)

**Comment by marcioalvessilva** [comment]
Concluído!
Qualquer novidade abrir novo issue
