### ISSUE TITLE
Arte para Webinar de lançamento DeCS

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/artes-graficas#152]
Prezado, Márcio, por favor poderia elaborar arte para divulgação do lançamento do DeCS seguindo a imagem de divulgação/banner do site.
Data provisória: 23/03/2023 - 15h
link da videoconferência a ser gerado.

C/c @acecampos

**Comment by lucianaPRB** [comment]
Márcio, segue link de inscrição no evento:
https://events.teams.microsoft.com/event/45f6e432-6a72-46e1-b44e-920e1535c762@e610e79c-2ec0-4e0f-8a14-1e4b101519f7

**Comment by marcioalvessilva** [comment]
bom dia, @lucianaPRB @acecampos 
Por favor traduzir para outros idiomas

Validar link encurtado: bit.ly/DeCS2023
![image](https://user-images.githubusercontent.com/48724136/226368868-6f7bd1a6-9430-4cff-aff9-b44d8ab30644.png)

**Comment by lucianaPRB** [comment]
Obrigada, Márcio. Seguem as variações:

PT-BR
Lançamento
23 março de 2023 - 15h (Horário de Brasília)
Profa. Dra.
Participação:
Acesse: 

ES
Lanzamiento
23 marzo 2023 - 15h (Hora de Brasília)
Participación
Profª Drª
Acceso:

EN
Release
March 23 2023 - 15h (UTC/GMT -3 hours)
Speaker
Dr. Mariângela Fujita, PhD
Sign up

**Comment by marcioalvessilva** [comment]
Por favor validar

### **PT**
![image](https://user-images.githubusercontent.com/48724136/226402446-90ec361e-1f92-4035-85f7-d9a0086e8247.png)

### **ES**
![image](https://user-images.githubusercontent.com/48724136/226402489-3b119ab1-0895-43eb-9d66-38d96e170d6e.png)

### **EN**
![image](https://user-images.githubusercontent.com/48724136/226402535-2651fbd8-1751-4ed0-9646-863b6b511e12.png)

**Comment by marcioalvessilva** [comment]
Grato @lucianaPRB!!!

**Comment by acecampos** [comment]
@marcioalvessilva por favor, precisaria consertar o nome do DeCS no banner em português: **Descritores em Ciências da Saúde**.

**Comment by marcioalvessilva** [comment]
![image](https://user-images.githubusercontent.com/48724136/226415913-d4fe999c-73ad-4a7a-ab5f-18c066401ae8.png)

@acecampos  por favor abrir novo isseu para correção do logo DeCS/MeSH (png) na página de logo

**Comment by acecampos** [comment]
Consertado. Obrigada, Márcio!
