### ISSUE TITLE
BVS Moçambique - vários itens de layout

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#153]
Márcio, após reunião com equipe de Moçambique, precisamos do seu apoio para:

1. Aumentar o tamanho da fonte do menu e dar mais espaçamento entre os itens - Márcio
2. Tornar a área de destaque como um banner fixo com uma frase de impacto que apresenta da BVS Moçambique e colocar a caixa de pesquisa dentro - Márcio
3. Criar uma imagem de destaque para o lançamento da BVS e disponibilizar abaixo da seção "Sites Relacionados" - Márcio
4. Criar imagem para o novo tema "Saúde Mental" - Márcio

**Comment by sousajul** [comment]
Márcio, seguem retorno sobre os itens:
1. Ok
2. Segue a frase: Promovendo o acesso livre à informação em saúde
3.  Aguardando
4. Ok

**Comment by marcioalvessilva** [comment]
Itens finalizado (1,2 e 4).
Item 3 - abrir novo issue assim que tiver mais informações.
Continuo à disposição.
