### ISSUE TITLE
Correção do logo DeCS/MeSH (png) na página de logo

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#154]
Márcio, por favor, efetuar correção do logo DeCS/MeSH (png)
Alterar o nome do produto: 
DE: Descritores de Ciências e Saúde 
PARA: Descritores em Ciências da Saúde

Obrigada!

**Comment by marcioalvessilva** [comment]
@acecampos aguardo validação para publicar, abraço!

![image](https://user-images.githubusercontent.com/48724136/228031134-1449d364-5bab-4ec0-b05c-488b610f6e87.png)
