### ISSUE TITLE
Save the Date -  BVS 25 Anos - 3 idiomas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/artes-graficas#156]
Save the Date 

Webinário 

BVS 25 Anos: Conquistas, Desafios e Oportunidades 

4 abril 2023  

15h30 às 17h00 (Hora de Brasília, GMT-3) 

Inscreva-se: https://bit.ly/BVS25a  

Com tradução simultânea 

 ------------------------------------------------------

Save the Date 

Webinar 

VHL 25 Years: Achievements, Challenges and Opportunities 

April, 4th 2023 

3:30pm – 5pm (Brasília time, GMT-3) 

Sign up at https://bit.ly/BVS25a  

Simultaneous translation will be provided 

-------------------------------------------------------- 

Save the Date 

Webinario 

BVS 25 Años: Logros, Desafíos y Oportunidades 

4 Abril 2023 

15:30 a 17:00 (hora de Brasília GMT-3) 

Regístrate: https://bit.ly/BVS25a  

Con interpretación simultánea

**Comment by marcioalvessilva** [comment]
Aguardo aprovação para que seja feita as versões em outros idiomas.


### **Versão 1** 
![image](https://user-images.githubusercontent.com/48724136/226748864-605098e5-632c-428f-b049-86afb922ec5d.png)


### **Versão 2** 
![image](https://user-images.githubusercontent.com/48724136/226748895-9fa187bc-f7eb-4b16-83a7-b169f4dc2b45.png)

**Comment by marcioalvessilva** [comment]
Link no GitHub (Twiiter/Facebook)
https://github.com/bireme/artes-graficas/tree/main/bvs/25%20anos/JPG


### **PT**
![image](https://user-images.githubusercontent.com/48724136/226915519-e7196669-670a-46c1-be7a-2908bcc6582c.png)

### **ES**
![image](https://user-images.githubusercontent.com/48724136/226915653-2f3cc43a-d20e-4d81-8fd6-23c9b42b7111.png)

### **EN**
![image](https://user-images.githubusercontent.com/48724136/226915432-621cefcb-9d89-4b6a-8eda-3cf4475f05f2.png)

**Comment by marcioalvessilva** [comment]
@pintoros por favor validar os banners do portal regional
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/bvs-25anos/JPG
