### ISSUE TITLE
Vitrine SMS-SP - Ajustes

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#157]
@marcioalvessilva  fiz um PPT com a explicação e demanda de ajuste de cada área.
Segue anexo.
[Ajustes - Vitrine SMS.pptx](https://github.com/bireme/artes-graficas/files/11041395/Ajustes.-.Vitrine.SMS.pptx)
Vou enviar e-mail complementando as imagens.

Acesso a Vitrine

https://sms.sp.bvs.br/vitrinas/wp-admin/post.php?post=242&action=edit

**Comment by marcioalvessilva** [comment]
Por favor validar!

**Comment by marcioalvessilva** [comment]
@pintoros bom dia!
Estou finalizando esse issue em caso de necessidade por favor reativar ou criar novo issue, Grato!
