### ISSUE TITLE
Flyer BVS 25 ANOS

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/artes-graficas#158]
Flyer pt 

BIREME convida para o webinário comemorativo 

BVS 25 Anos: Conquistas, Desafios e Oportunidades 

Dia 4 abril 2023  

Das 15h30 às 17h00 (hora de Brasília GMT-3) 

Via Zoom, com interpretação simultânea ao espanhol, português e inglês 

Inscreva-se: https://bit.ly/BVS25a 

 

Flyer es 

BIREME invita al webinario conmemorativo 

BVS 25 Años: Logros, Desafíos y Oportunidades 

4 de abril de 2023 

De 15:30h a 17:00h (hora de Brasília, GMT -3) 

Vía Zoom, con interpretación simultánea al español, inglés y portugués 

Regístrate: https://bit.ly/BVS25a 

 

Flyer en 

BIREME invites to the commemorative webinar 

VHL 25 Years: Achievements, Challenges and Opportunities 

April 4th, 2023 

From 3:30pm to 5:00pm (Brasília Time, GMT -3) 

Via Zoom, with simultaneous interpretation into Spanish, English and Portuguese 

Sign up: https://bit.ly/BVS25a

**Comment by marcioalvessilva** [comment]
Banners portal regional atualizados
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/bvs-25anos/JPG

**Comment by marcioalvessilva** [comment]
@veronicaabdala segue proposta de Flyer (*selo 25 anos aleatório)
Aguardo orientações

![BVS-25anos-pt](https://user-images.githubusercontent.com/48724136/227723129-d0361676-25cd-4c52-9147-4e4fef929f19.jpg)

**Comment by marcioalvessilva** [comment]
@veronicaabdala  segue proposta de flyer (selo 25 anos selecionado aleatoriamente)
![BVS-25anos-pt](https://user-images.githubusercontent.com/48724136/227723607-cc076761-58d2-4c55-8d32-84e7207a3f9e.jpg)

**Comment by marcioalvessilva** [comment]
### **PT**
https://github.com/bireme/artes-graficas/blob/main/bvs/25%20anos/JPG/BVS-25anos-pt.jpg
![image](https://user-images.githubusercontent.com/48724136/227953215-d7dfe5d3-a031-4258-a587-9d1270155372.png)


### **ES**
https://github.com/bireme/artes-graficas/blob/main/bvs/25%20anos/JPG/BVS-25anos-es.jpg
![image](https://user-images.githubusercontent.com/48724136/227953269-91ec34f4-7dff-4360-acef-89f726c677c9.png)



### **EN**
https://github.com/bireme/artes-graficas/blob/main/bvs/25%20anos/JPG/BVS-25anos-en.jpg
![image](https://user-images.githubusercontent.com/48724136/227953320-fb37fbcc-f6cc-4e56-8967-cf4d9f595b71.png)

**Comment by marcioalvessilva** [comment]
Finalizado!
