### ISSUE TITLE
Thumbnail para canal do DeCS no YouTube

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#159]
Por favor, Márcio, criar um Thumbnail para o canal do YouTube para servir de miniatura estática.
Agradecemos!
@lucianaPRB e acecampos

**Comment by marcioalvessilva** [comment]
No GitHub https://github.com/bireme/artes-graficas/tree/main/decs-mesh/Video/thumbnail/JPG

Versão 1
![image](https://user-images.githubusercontent.com/48724136/227633130-8bdbdfea-eb1e-4bb8-8aec-03a79e6a48b5.png)

Versão 2
![image](https://user-images.githubusercontent.com/48724136/227633185-4eb3f621-dc08-4911-b2f4-3a3f3c441af6.png)

Versão 3
![image](https://user-images.githubusercontent.com/48724136/227633235-f146f00f-c653-450a-b625-35c7146911ff.png)

**Comment by marcioalvessilva** [comment]
Finalizado!
