### ISSUE TITLE
Colocar tarja de "Inscrições Encerradas"

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#16]
Márcio, por favor, criar uma tarja sobre o banner da "Oportunidade de trabalho" informando que as inscrições estão encerradas.

"Inscrições encerradas".

Obrigada!

**Comment by marcioalvessilva** [comment]
@acecampos, @renatomurasaki e @arthurtreuherz  
https://github.com/bireme/artes-graficas/blob/main/banners-sites/decs/vaga/jpg/bannerEncerrrado.jpg

Fico no aguardo da aprovação para publicar!

![image](https://user-images.githubusercontent.com/48724136/130667933-4fae516a-cb31-48e5-9938-4026b1a29d67.png)

**Comment by acecampos** [comment]
Por  mim, aprovado. Obrigada!

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado. Concordo com a @acecampos

**Comment by marcioalvessilva** [comment]
Banner publicado!
