### ISSUE TITLE
Vitrine - BVS 25 anos

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#160]
Márcio poderia customizar essa vitrine com as cores usadas no flyer? Pode mudar tudo que está lá.
Inclusive background etc.
Está na área de rascunho no regional:
https://bvsalud.org/vitrinas/wp-admin/post.php?post=6556&action=edit

Tem também um infográfico que tentei colocar e que a imagem fica desalinhada. Segue anexo o PPT, caso necessite edição:
[Infograficos_bvs_25 Anos.pptx](https://github.com/bireme/artes-graficas/files/11083055/Infograficos_bvs_25.Anos.pptx)

Obrigada

**Comment by marcioalvessilva** [comment]
Bom dia @pintoros 
Segue print 
* os vídeos não estão aparecendo, pode confirmar se os links estão corretos
* vou continuar dando uma analisada se consigo inserir detalhes, como era urgente, fiz alguns acabamentos simples para não ficar travado essa vitrine

![image](https://user-images.githubusercontent.com/48724136/228852102-f025383a-10c9-41ce-85e4-a9cb4c5402a9.png)

**Comment by pintoros** [comment]
Eu acho que está ótimo Márcio!
Os vídeos, coloquei um link aleatório para testar, e achei estranho não aparecer...
Acabei de pedir o link certo para Juliana.

Sobre as imagens que coloquei no PPT (nos 3 idiomas) para vc olhar, eu não estava conseguindo inserir na área de Infografias pq ficava distorcido.
Se eu salvar em PDF será que dá certo?

**Comment by marcioalvessilva** [comment]
Bom dia @pintoros falei com o Mori sobre a tradução do texto "mais vídeos", acredito que esteja tudo ok, continuo à disposição.

**Comment by marcoslmori** [comment]
Atualizado o plugin e creio já foi resolvido o saiba mais em inglês

**Comment by marcioalvessilva** [comment]
Acredito que esse issue pode ser finalizado!
