### ISSUE TITLE
Banner divulgação da gravação do Lançamento DeCS 2023

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/artes-graficas#161]
Prezado Márcio, 
Poderia elaborar um banner, nos três idiomas, de divulgação para a gravação do Lançamento DeCS 2023?
O texto seria:
PT
Perdeu o Lançamento da Edição 2023? Assista no Youtube!

EN
Did you miss the release of the 2023 Edition? Watch it on Youtube!
Turn on the subtitles for your language!

ES
¿Te perdiste el lanzamiento de la edición 2023? ¡Véalo en Youtube!
Active los subtítulos en su idioma!

Muito obrigada!
c/c @acecampos

**Comment by marcioalvessilva** [comment]
### **PT**
![image](https://user-images.githubusercontent.com/48724136/229145887-c4d7f4d3-7518-4fbe-8485-f0a72084337d.png)

### **ES**
![image](https://user-images.githubusercontent.com/48724136/229145928-053ab072-1e65-4873-a902-a819e7708232.png)

### **En**
![image](https://user-images.githubusercontent.com/48724136/229145977-78a0c66e-94c8-4347-9941-f248d5a8f87e.png)
