### ISSUE TITLE
Destaque - Portal Regional da BVS

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#162]
Márcio, a Verônica solicitou incluir um destaque no Portal Regional da BVS, como ali é um quebra cabeças, não ouso mexer.

Em https://bvsalud.org/ tem uma pequena área a direita escrito Vitrines do Conhecimento. 

Acima do destaque da Vitrine de COVID, incluir a imagenzinha que está no centro da vitrine 25 anos da BVS (nos moldes daquela da Vitrine de COVID) escrito:

BVS 25 anos  - pt
https://bvsalud.org/vitrinas/post_vitrines/bvs-25-anos/

BVS 25 años - es
https://bvsalud.org/vitrinas/es/post_vitrines/bvs-25-aniversario/

VHL 25 years - en 
https://bvsalud.org/vitrinas/en/post_vitrines/vhl-25-years/

**Comment by marcioalvessilva** [comment]
### **PT**
![image](https://user-images.githubusercontent.com/48724136/229639078-493611f2-92a1-4236-a6fe-47613667da38.png)

### **ES**
![image](https://user-images.githubusercontent.com/48724136/229639050-ff9d1ec5-6bd8-42d2-b260-da1f77bf5ff3.png)

### **EN**
![image](https://user-images.githubusercontent.com/48724136/229639031-70cd3baa-839a-437b-88fb-eee4ffff3503.png)

**Comment by pintoros** [comment]
Obrigada!
