### ISSUE TITLE
Atualização / Correção instância LIS Vitrinas 

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#163]
https://bvsalud.org/vitrinas/ 

**1)** Solicito corrigir a imagem de destaque da Enfermagem nos idiomas Português e Inglês
pt-  Enfermagem
en - Nursery

**2)** Solicito incluir imagem do selo de destaque para BVS 25 anos abaixo da imagem de Enfermagem
pt - https://bvsalud.org/vitrinas/post_vitrines/bvs-25-anos/
es - https://bvsalud.org/vitrinas/es/post_vitrines/bvs-25-aniversario/
en - https://bvsalud.org/vitrinas/en/post_vitrines/vhl-25-years/

**3)** Solicito alterar a cor do botão Todas as Vitrines. Sugestão (a que ficar melhor) 
* formato arredondado nos cantos - para parecer mais um botão
- cinza com letras azuis ou  
- azul com letras brancas

**Comment by marcioalvessilva** [comment]
Por favor validar!

**Comment by pintoros** [comment]
Botão pt - Todas as Vitrines do Conhecimento
Botão en - Colocar A primeira letra em maiúsculo para Windows of Knowledge

Errei na tradução da imagem em inglês. O correto é Nursing e Nursery. Desculpa

________________________________

Rosemeire Rocha Pinto, Bibliotecária, MS
BIREME<https://www.paho.org/en/bireme> EIH PAHO WHO<https://www.paho.org/en/evidence-and-intelligence-action-health>


[cid:1a0e8a3a-e4c2-4bdf-8a8f-96ef9d5afba6]

________________________________
De: Márcio Alves ***@***.***>
Enviado: terça-feira, 4 de abril de 2023 15:31
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Atualização / Correção instância LIS Vitrinas (Issue #163)


Por favor validar!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F163%23issuecomment-1496420468&data=05%7C01%7Cpintoros%40paho.org%7Ce4b5d6e4140341ae261808db353ae11d%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638162299236579293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zb9CU1ugnJ4bJffSBLRWBpPG64hnKPZyYxuEGzGt%2BPM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4HMXW2VFESTRNHPDWDW7RSJ5ANCNFSM6AAAAAAWSZX5EM&data=05%7C01%7Cpintoros%40paho.org%7Ce4b5d6e4140341ae261808db353ae11d%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638162299236579293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n7AVhR42KVFS9VtpIjMaMi6dwJpOAr2jS2Wx2hFFy70%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Por favor validar!

**Comment by pintoros** [comment]
Feito! Obrigada Márcio!
