### ISSUE TITLE
Incluir data de expiração em banners no wordpress DeCS

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/artes-graficas#164]
Prezado @marcioalvessilva 
Poderia por favor adicionar ao Wordpress do DeCS data para que os banners saiam do ar?

Obrigada!

**Comment by marcioalvessilva** [comment]
Olá @lucianaPRB!
Conforme conversado, existe um efeito colateral para essa solicitação.
- Caso não exista nenhum banner ativo, ficará aparecendo o botão de fechar (print exemplo).
![image](https://user-images.githubusercontent.com/48724136/233064845-054a2937-d975-4011-8d27-89c0f8628632.png)

Hoje existe um campo para oculta a exibição do carrossel, acredito que seja uma solução melhor.
Aguardo orientações.

**Comment by marcioalvessilva** [comment]
Finalizado!
