### ISSUE TITLE
Ajuste Rodapé e novo tema BVS Moçambique

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#165]
Marcio, solicito seu apoio para:

1. Criar imagem para tema novo: HIV SIDA
2. Ajustar os logos do rodapé seguindo a ordem:

![image](https://user-images.githubusercontent.com/13439949/232112137-46b967eb-a32f-42bf-a4a2-69ebec59cd19.png)

![logo-MISAU-MZ](https://user-images.githubusercontent.com/13439949/232112438-1e314f43-aa93-45c0-adad-f3ae662d14df.png)

Link: https://www.misau.gov.mz

**Comment by marcioalvessilva** [comment]
Finalizado, qualquer modificação, por favor reabrir issue
