### ISSUE TITLE
Alterar banner BVS Moçambique

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#166]
Márcio,

Conforme solicitação da equipe de coordenação da BVS Moçambique, poderia colocar as letras do banner da BVS em letras maiúsculas.

![image](https://user-images.githubusercontent.com/13439949/232121257-9505893c-05ff-4aa5-86d1-45bb095bfc7d.png)

**Comment by marcioalvessilva** [comment]
Finalizado, qualquer alterações por favor reabrir issue
