### ISSUE TITLE
Template powerpoint DeCS 

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/artes-graficas#168]
Prezado @marcioalvessilva 
Poderia elaborar um template de apresentações para o DeCS com identidade visual e logo DeCS e BIREME?
Muito obrigada!

C/C @acecampos

**Comment by marcioalvessilva** [comment]
Olá! @lucianaPRB e @acecampos 
Seguem três propostas de background para powerpoint, façam um teste e me avisem caso deseje um outra opção.
Abraço!

### **Modelo 1**
![modelo 1](https://user-images.githubusercontent.com/48724136/232912038-34c82228-3e7d-4bd5-bdbe-bfc36652668d.jpg)

### **Modelo 2**
![modelo 2](https://user-images.githubusercontent.com/48724136/232912039-f96ac195-9cf1-42b8-b5ce-b66d82d21e4a.jpg)

### **Modelo 3**
![modelo 3](https://user-images.githubusercontent.com/48724136/232912036-f910ff1e-7618-4a7f-8229-3807a8f0acaa.jpg)

**Comment by lucianaPRB** [comment]
@marcioalvessilva 
Todos ficaram ótimos, muito obrigada por isso!
Vamos ficar com o modelo 1, pode dar andamento.

Obrigada!
Luciana e @acecampos

**Comment by marcioalvessilva** [comment]
Segue variações para utilizar de acordo com o conteúdo.

**1**
![modelo 1-1](https://user-images.githubusercontent.com/48724136/233176071-469611e9-aba2-4671-bb27-1c44a9fdb4ed.jpg)
**2**
![modelo 1-2](https://user-images.githubusercontent.com/48724136/233176075-cde076f6-1d33-4dfa-bf98-26c6c38884bd.jpg)
**3**
![modelo 1-3](https://user-images.githubusercontent.com/48724136/233176079-b6890922-b821-418f-a87d-e1296b399364.jpg)
**4**
![modelo 2-1](https://user-images.githubusercontent.com/48724136/233176081-56172360-1a5a-4f2b-a5d9-bc4d6665e631.jpg)
**5**
![modelo 2-2](https://user-images.githubusercontent.com/48724136/233176064-096f4209-7178-4213-b745-6ff5d546cb55.jpg)

**Comment by marcioalvessilva** [comment]
Finalizado!
