### ISSUE TITLE
Páginas para consulta pública da revisão da categoria SP

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#17]
@marcioalvessilva por favor, fazer duas páginas com banners chamando para a consulta pública sobre a revisão da categoria Saúde Pública do DeCS: uma página em português e outra em espanhol.

Data: de 6 de setembro a 24 de outubro de 2021.

Nomes das subcategorias (português):

[SP1] Políticas, Planejamento e Administração em Saúde => leva para documento técnico em PDF dessa subcategoria
[SP2] Atenção à Saúde => leva para documento técnico em PDF dessa subcategoria
[SP3] Estudos Populacionais em Saúde Pública => leva para documento técnico em PDF dessa subcategoria
[SP4] Saúde Ambiental => leva para documento técnico em PDF dessa subcategoria
[SP5] Epidemiologia e Bioestatística => leva para documento técnico em PDF dessa subcategoria
[SP6] Ciências da Nutrição => leva para documento técnico em PDF dessa subcategoria
[SP8] Desastres => leva para documento técnico em PDF dessa subcategoria
[SP9] Direito Sanitário => leva para documento técnico em PDF dessa subcategoria

Nomes das subcategorias (espanhol):
[SP1] Políticas, Planificación y Administración en Salud => leva para documento técnico em PDF dessa subcategoria
[SP2] Atención a la Salud => leva para documento técnico em PDF dessa subcategoria 
[SP3] Estudios Poblacionales en Salud Pública => leva para documento técnico em PDF dessa subcategoria
[SP4] Salud Ambiental => leva para documento técnico em PDF dessa subcategoria
[SP5] Epidemiología y Bioestadística => leva para documento técnico em PDF dessa subcategoria
[SP6] Ciencias de la Nutrición => leva para documento técnico em PDF dessa subcategoria
[SP8] Desastres => leva para documento técnico em PDF dessa subcategoria
[SP9] Derecho Sanitario => leva para documento técnico em PDF dessa subcategoria

Um botão "Faça aqui sua contribuição" com link para um formulário de Google forms
Agradeço!

**Comment by marcioalvessilva** [comment]
@anakatiacamilo, @renatomurasaki e @arthurtreuherz 
Segue link da página em português na instância de teste do DeCS
https://decs.teste.bvs.br/consulta-publica/

Fica pendente o link para os arquivos para os arquivos.

Aguardo aprovação para fazer a página em espanhol já na produção e deixar como rascunho.

**Comment by renatomurasaki** [comment]
@marcioalvessilva @acecampos @arthurtreuherz Gostei bastante da página. Seguem minhas sugestões para avaliação de vocês:

- precisamos colocar a lista de nomes e afiliação dos especialistas que fazem parte do Comitê, tanto brasileiros como mexicanos
- Por se tratar de Saúde Pública, trocaria DeCS/MeSH para DeCS
- Trocaria o título "Subcategoria de Saúde Pública" para "Acesse abaixo a proposta de atualização por subcategoria de Saúde Pública "

**Comment by marcioalvessilva** [comment]
@renatomurasaki, @acecampos e @arthurtreuherz 
Fiz duas das alterações informadas, fico no aguardo da lista de nomes e afiliações.

**Comment by renatomurasaki** [comment]
@acecampos veja com o @marcioalvessilva por favor, para incluir a lista de especialistas na página. Veja se alguma informação que está na seção introdução que a Elenice preparou valeria a pena incluir nesta página. A decisão é sua.

**Comment by acecampos** [comment]
@marcioalvessilva envio os textos para o release que ficarão abaixo do botão que leva ao formulário:
[Apresentação para site-ES.docx](https://github.com/bireme/artes-graficas/files/7101225/Apresentacao.para.site-ES.docx)
[Apresentação para site-PT.docx](https://github.com/bireme/artes-graficas/files/7101226/Apresentacao.para.site-PT.docx)

**Comment by marcioalvessilva** [comment]
Páginas criadas, inseridas como rascunhos e programadas para publicação no dia 10/09/2021
@acecampos por favor verificar em e informar se precisam de mais alguma alterações.

**Comment by acecampos** [comment]
@marcioalvessilva obrigada!
As alterações para fazer na página espanhol, por favor:
- Nomes das subcategorias: mudar para espanhol, porque reparei que os botões para acesso aos pdf estão em português, mesmo na página em espanhol.
- Tem uma indentação diferente onde o texto começa por "Dra. Cibele..." no parágrafo do comitê de SP1.
- acho que o texto "Acesse abaixo a proposta de atualização por subcategoria de Saúde Pública" pode ser traduzido ao espanhol assim: "Acceda a continuación a la propuesta de actualización por subcategoría de Salud Pública"
- o texto "Faça sua contribuição aqui" pode ser traduzido ao espanhol assim: "Haz tu contribución aquí".

Estou achando que ninguém vai rolar para ver mais nada abaixo do botão "Faça aqui sua contribuição". Mas se colocar o texto em cima, ninguém vai ver o botão para o formulário. Vou pensar em alguma solução... Tem como fazer duas colunas de texto?
Por enquanto é isso...
Grata!

**Comment by marcioalvessilva** [comment]
@acecampos Grato!
Sobre inserir em duas colunas é possível sim.

**Comment by marcioalvessilva** [comment]
@acecampos página atualizada!

**Comment by marcioalvessilva** [comment]
Página publicada!
