### ISSUE TITLE
Thumbnail para vídeo DeCS

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/artes-graficas#171]
Prezado @marcioalvessilva, por favor, preparar miniatura para vídeo do DeCS no Youtube com o texto "Explicando os detalhes dos descritores"

Obrigada!

**Comment by marcioalvessilva** [comment]
Segue imagem

![thumbnail-descritores](https://github.com/bireme/artes-graficas/assets/48724136/c2513284-460d-4237-9bb4-2af444a8ff56)

**Comment by lucianaPRB** [comment]
Perfeito, @marcioalvessilva ! Obrigada
