### ISSUE TITLE
Criar Layout para o Dashboard do Google Analytics

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/artes-graficas#172]
Por favor, 
Criar layout para o Dashboard de google analytics https://lookerstudio.google.com/reporting/afadc1ed-6c5a-4fc4-83ae-8f0dde43bbcd  da BVS Economia da Saúde  https://economia.saude.bvs.br/.

Grata

**Comment by marcioalvessilva** [comment]
Por favor validar alterações.
Fico no aguardo de orientações em caso de mais mudanças desejadas

![print](https://github.com/bireme/artes-graficas/assets/48724136/fe1a0f90-e6b4-4d64-9a66-bc250bfd55d8)

Abraço!

**Comment by marcioalvessilva** [comment]
Por favor validar!
Continuo à disposição, Abraço!
![print](https://github.com/bireme/artes-graficas/assets/48724136/7258199e-9b8d-4548-9fb0-a960a5806e4e)

**Comment by marcioalvessilva** [comment]
Finalizado!
