### ISSUE TITLE
Site Eventos e Banner - Urgente

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#174]
1) Necessitamos customizar o site https://bvsalud.org/events/ para os dois eventos próximos , sendo que o primeiro inicia domingo :-O . A @veronicaabdala solicitou que trabalhe com essa prioridade, por favor.
Anexo a orientação e os links para a customização do site para os dois eventos (será o mesmo para os dois)
[Site Eventos.pptx](https://github.com/bireme/artes-graficas/files/11887567/Site.Eventos.pptx)

2) Banner impresso - Incluir a arte do site, a frase principal e o QR Code para o site e o Logo BIREME em destaque: 
Tamanho da arte para impressão do banner 80x120cm

@marcioalvessilva pode me chamar se tiver dúvida.

**Comment by marcioalvessilva** [comment]
Finalizado!
