### ISSUE TITLE
Criação de flyer e fundo de PPT para calendário de capacitação 2024

### ISSUE THREAD

**Issue by suelisuga** [bireme/artes-graficas#179]
Solicito criação de flyers e fundo de ppt para o calendário de capacitações 2024.

O modelo segue o que fizemos em 2022, então teremos um título que aglutina todo o calendário, que poderia ser algo como: "Fortalecimento das Redes de Informação em Saúde na AL&C (2024)" e se subdivide em 4 eixos:

1. Buenas prácticas en los Procesos Editoriales de Revistas Científicas LILACS
2. Indización de documentos según la Metodología LILACS
3. Biblioteca Virtual en Salud (BVS);
4. Reunião da Rede de Referencistas.

Considerando isso solicito a criação de 1 flyer que representa as reuniões como um todo e 4 flyers e fundos de PPT padronizados para cada um dos eixos.

Ademais, solicito:
- Imagens iguais ou parecidas para dar uma unidade ao Calendário, mas com cores diferentes para cada um dos 4 eixos;
- Todos textos editáveis;
- Layout que possibilite incluir de 3 a 6 datas de reunião;
- Título da sessão, nome e instituição dos palestrantes;
- Data e hora do encontro;
- Link encurtado na reunião;
- Logo da BIREME, BVS e LILACS em português e espanhol.

Segue exemplo:

- Calendario geral: https://red.bvsalud.org/fortalecimento-das-redes-de-informacao-em-saude-na-alc/
![image](https://github.com/bireme/artes-graficas/assets/13105683/c108f8a6-983b-4509-827b-e9814190ee29)

- Flyer de eixo temático: https://red.bvsalud.org/fortalecimento-das-redes-de-informacao-em-saude-na-alc/reunioes-de-coordenacao-bvs-e-lilacs/

![image](https://github.com/bireme/artes-graficas/assets/13105683/8904028b-cbd3-4c46-a265-54190ccbf1e1)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sugasuel/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sugasuel/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Data da   capacitação | Temas de   capacitação
-- | --
25/04/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
27/06/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
22/08/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
24/10/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
28/11/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
14/03/2024 | Biblioteca Virtual en Salud
11/04/2024 | Biblioteca Virtual en Salud
12/09/2024 | Biblioteca Virtual en Salud
10/10/2024 | Biblioteca Virtual en Salud
09/05/2024 | Biblioteca Virtual en Salud
14/11/2024 | Biblioteca Virtual en Salud
28/03/2024 | Indización de   documentos según la Metodología LILACS
23/05/2024 | Indización de   documentos según la Metodología LILACS
25/07/2024 | Indización de   documentos según la Metodología LILACS
26/09/2024 | Indización de   documentos según la Metodología LILACS
29/02/2024 | Biblioteca Virtual en Salud
13/06/2024 | Reunión de la Red de Referencistas
11/07/2024 | Reunión de la Red de Referencistas
08/08/2024 | Reunión de la Red de Referencistas

</body>

</html>

Muito obrigada!

**Comment by suelisuga** [comment]
@marcioalvessilva em reunião hoje, a Verônica pediu para criar um flyer com todas as datas do calendário de capacitação 2024:


Português:
29/02/2024 | Biblioteca Virtual em Saúde
14/03/2024 | Biblioteca Virtual em Saúde
28/03/2024 | Indexação de documentos segundo a Metodologia LILACS
11/04/2024 | Biblioteca Virtual em Saúde
25/04/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
09/05/2024 | Biblioteca Virtual em Saúde
23/05/2024 | Indexação de documentos segundo a Metodologia LILACS
13/06/2024 | Encontro da Rede de Referencistas
27/06/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
11/07/2024 | Encontro da Rede de Referencistas
25/07/2024 | Indexação de documentos segundo a Metodologia LILACS
08/08/2024 | Encontro da Rede de Referencistas
22/08/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
12/09/2024 | Biblioteca Virtual em Saúde
26/09/2024 | Indexação de documentos segundo a Metodologia LILACS
10/10/2024 | Biblioteca Virtual em Saúde
24/10/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
14/11/2024 | Biblioteca Virtual em Saúde
28/11/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS

Espanhol: 
29/02/2024 | Biblioteca Virtual en Salud
14/03/2024 | Biblioteca Virtual en Salud
28/03/2024 | Indización de documentos según la Metodología LILACS
11/04/2024 | Biblioteca Virtual en Salud
25/04/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
09/05/2024 | Biblioteca Virtual en Salud
23/05/2024 | Indización de documentos según la Metodología LILACS
13/06/2024 | Encuentro de la Red de Referencistas
27/06/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
11/07/2024 | Encuentro de la Red de Referencistas
25/07/2024 | Indización de documentos según la Metodología LILACS
08/08/2024 | Encuentro de la Red de Referencistas
22/08/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
12/09/2024 | Biblioteca Virtual en Salud
26/09/2024 | Indización de documentos según la Metodología LILACS
10/10/2024 | Biblioteca Virtual en Salud
24/10/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS
14/11/2024 | Biblioteca Virtual en Salud
28/11/2024 | Buenas prácticas en los procesos editoriales de revistas científicas LILACS

Considerando que são muitas datas, entendo que será melhor fazer uma imagem maior, considerando esse espaço aqui:
![image](https://github.com/bireme/artes-graficas/assets/13105683/2269ad69-17e9-45b3-926e-dcb59fd9e57a)

Ainda teremos o RSS do DirEve, mas embaixo, vamos colocar a imagem que será produzida.

Qlq dúvida, fico à disposição.

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Versão com texto reduzido!
![agenda-site-v2-pt](https://github.com/bireme/artes-graficas/assets/48724136/9a1142f4-43d8-462c-ba97-d6cc01ce96d1)

**Comment by marcioalvessilva** [comment]
Ajuste
![agenda-site-v2-pt](https://github.com/bireme/artes-graficas/assets/48724136/904f624b-1641-42ff-90c2-4e65bbc5af02)

**Comment by marcioalvessilva** [comment]
Ajuste - Data de abertura foi separada das demais reuniões

![agenda-site-v2-pt](https://github.com/bireme/artes-graficas/assets/48724136/9426ab3f-89f7-4bae-b2a2-aa15b25fb2d0)

**Comment by marcioalvessilva** [comment]
Concluído!
