### ISSUE TITLE
Criar imagem de destaque para a BVS Brasil

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#18]
Criar imagem para destacar a Vitrine do Conhecimento História natural da COVID-19 no carrossel de destaques da BVS Brasil (https://brasil.bvs.br/).

Criar imagem com o título "Vitrines do Conhecimento" para incluir na seção "Fontes de Informação" da BVS Brasil.
![image](https://user-images.githubusercontent.com/13439949/131564540-6a80032a-bd7f-4cc8-83dd-40125a51cd4f.png)

**Comment by renatomurasaki** [comment]
@pierrima criamos um projeto no seu nome. Basta acessar

https://github.com/orgs/bireme/projects/19

Em todos os issues assignados para você, independentemente do repositório, basta associá-lo ao seu projeto e com isso você terá em um único lugar a visão de todos os issues e em que momento do kanban ele está.

**Comment by pierrima** [comment]
Olá Juliana, boa tarde
Seguem as imagens solicitadas.

![vitrineconhecimento](https://user-images.githubusercontent.com/13052947/131726778-559eb194-fe76-4b28-87ea-0f830fa8da20.png)
![destaque_covid](https://user-images.githubusercontent.com/13052947/131726823-4587fc19-9766-4ef5-9063-949ebeec7152.jpg)

**Comment by renatomurasaki** [comment]
@sousajul quando estiver de acordo com a entrega, favor encerrar o issue, clicando no botão Close. Caso contrário, comentar por aqui a necessidade de mudança para que mantenhamos o issue com a informação atualizada e rastreável. Obrigado.
