### ISSUE TITLE
Artes gráficas para edição 2024 do DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#181]
@marcioalvessilva, por favor, desenvolver artes para:

- [x] Destaque na forma de banner que o usuário pode fechar sobre lançamento do DeCS 2024, como a do exemplo do ano de 2022 da imagem abaixo
 ![image](https://github.com/bireme/artes-graficas/assets/35345406/8ba8605f-5233-455b-808c-4b47b60644ad)
- [ ] Quantidades (atualizaremos os valores futuramente) como no exemplo dos anos anteriores, abaixo:
![image](https://github.com/bireme/artes-graficas/assets/35345406/2c1c9df2-2e91-4548-b6b8-e0cb69d83164)

Obrigada!

**Comment by marcioalvessilva** [comment]
Por favor validar!!!
![2024-pt](https://github.com/bireme/artes-graficas/assets/48724136/e698437e-c8fa-4ed8-b411-657acad5ace4)
![2024-en](https://github.com/bireme/artes-graficas/assets/48724136/ccb1af6e-52f8-475a-8ecc-188c98168a2e)
![2024-es](https://github.com/bireme/artes-graficas/assets/48724136/78ad75e8-1000-4fac-9774-d36d45eb2dc4)
![2024-fr](https://github.com/bireme/artes-graficas/assets/48724136/51e4ce2c-2b20-4f1a-989f-709151a1eca2)

Aguardo dados atualizados para atualizar tabela DeCS/MeSH

**Comment by acecampos** [comment]
Oi, Márcio! Está ótimo, obrigada!
Fazer, por favor, uma correção no banner do inglês: colocar o texto abaixo do ano, ficando assim:

2024
edition is available

Grata

**Comment by marcioalvessilva** [comment]
Atualizado!
![2024-en](https://github.com/bireme/artes-graficas/assets/48724136/306b20f7-63bc-4189-afad-e409a784df78)

**Comment by acecampos** [comment]
Validado, @marcioalvessilva.
Obrigada!

**Comment by acecampos** [comment]
Por favor, @marcioalvessilva:
- [ ] tirar o **/MeSH** da figura com os dados numéricos, para ficar como na figura abaixo;
- [ ] atualizar as quantidades conforme números destacados em amarelo, para todos os idiomas.

![image](https://github.com/bireme/artes-graficas/assets/35345406/47a0b1b5-82fc-42a0-a19b-2756bc15daa5)
Obrigada!

**Comment by marcioalvessilva** [comment]
Por favor validar

**EN** - [DeCS_en_2023.pdf](https://github.com/bireme/artes-graficas/files/14587660/DeCS_en_2023.pdf)
![image](https://github.com/bireme/artes-graficas/assets/48724136/0f111b79-4c7e-4a03-8284-52e6b32ce38e)


**ES** - [DeCS_es_2023.pdf](https://github.com/bireme/artes-graficas/files/14587661/DeCS_es_2023.pdf)
![image](https://github.com/bireme/artes-graficas/assets/48724136/202aa74d-d131-447b-b9cb-bca7049560fd)

**FR** - [DeCS_fr_2023.pdf](https://github.com/bireme/artes-graficas/files/14587662/DeCS_fr_2023.pdf)
![image](https://github.com/bireme/artes-graficas/assets/48724136/fd793ed6-f23b-4683-8734-4ac7ea2af53f)


**PT** - [DeCS_pt_2023.pdf](https://github.com/bireme/artes-graficas/files/14587664/DeCS_pt_2023.pdf)
![image](https://github.com/bireme/artes-graficas/assets/48724136/3354f9f7-5be1-4c52-ada8-803e9ccf6962)

**Comment by acecampos** [comment]
@marcioalvessilva validado!
Obrigada!
