### ISSUE TITLE
Imagem para divulgação da abertura do Processo de Avaliação e Seleção de Periódicos LILACS Brasil 2024

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/artes-graficas#182]
Solicito imagem para divulgação, via Twitter e e-mail, da abertura do Processo de Avaliação e Seleção de Periódicos LILACS Brasil 2024
Data: 01 a 30 abril
Informações: https://bit.ly/lilacsbr24
Somente em português

Exemplo de 2022:
![image](https://github.com/bireme/artes-graficas/assets/47643830/9bd4ebf0-b496-447d-bd6d-106d5e2bbe7b)

**Comment by marcioalvessilva** [comment]
Seguem duas opções, fico no aguardo de validação.

![processo-avaliacao](https://github.com/bireme/artes-graficas/assets/48724136/c7dd9659-aea4-4588-bd14-55a8e873b5bf)
![processo-avaliacao-2](https://github.com/bireme/artes-graficas/assets/48724136/0763c98e-d99d-4a9b-8ed1-9ae579d2e012)

**Comment by AngelicaSAPaula** [comment]
@marcioalvessilva Acredito que utilizaremos as duas, uma em cada quinzena do mês, para chamar mais atenção! Muito obrigada!
