### ISSUE TITLE
Template para mídias sociais do DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#183]
Márcio, boa tarde! 
A @anafranzon solicita um template com formato/funcionalidade de moldura que sirva como identidade visual para as notícias do DeCS nas redes sociais da BIREME.
Poderia construir opções para votarmos, por favor?

Gratas,
@lucianaPRB e @acecampos.

**Comment by anafranzon** [comment]
Oi, @marcioalvessilva, obrigada! Eu gostei dos três. Creio que podemos usa-los todos, alternando entre os modelos, e vamos avaliando se ficam bons com as imagens, etc. Que vocês acham disso, @lucianaPRB e @acecampos ? Se estiverem de acordo, Márcio, disponibiliza os arquivos por favor? Eu uso Canva para edição, então, precisaria ser em PNG ou JPG com o fundo vazio, é possível? Obrigada, boa semana a todos.

**Comment by acecampos** [comment]
@marcioalvessilva, estão todos ótimos, mas tenho um xodó.
@anafranzon, de acordo; vamos "sentindo" como eles se aplicam....
Boa semana!!

**Comment by lucianaPRB** [comment]
Oi @marcioalvessilva, ficaram muito bons realmente!
@anafranzon Super concordo!

**Comment by marcioalvessilva** [comment]
Perfeito, vou gerar os arquivos e envio o link para download.

**Comment by marcioalvessilva** [comment]
https://github.com/bireme/artes-graficas/tree/main/decs-mesh/Templates%20Posts/PNG

Segue link com templates nos 3 idiomas

**Comment by marcioalvessilva** [comment]
Finalizado
