### ISSUE TITLE
Mudar botão no portal DeCS/MeSH em Espanhol

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#186]
Boa tarde, @marcioalvessilva!
Por favor, mudar os dizeres no botão "Como pesquisar" para "Como buscar" na página em espanhol. 
@pintoros, obrigada por informar!
![image](https://github.com/bireme/artes-graficas/assets/35345406/8f6fd926-3e74-445e-b14b-295236da126d)

**Comment by marcioalvessilva** [comment]
Imagem atualizada! por favor validar

**Comment by acecampos** [comment]
@marcioalvessilva, validado. Grata!
