### ISSUE TITLE
Destaque OROPOUCHE - Portal Regional

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#187]
Solicito imagem destaque para carrossel Portal Regional sobre Febre Oropouche.

Febre Oropouche - com letras maiores
documentos na BVS - Biblioteca Virtual em Saúde - com letras menores

Fiebre Oropouche
documentos en la BVS - Biblioteca Virtual en Salud

Oropouche Fever
Documents in the VHL - Virtual Health Library

sites de referência para imagem:
https://www.paho.org/pt/noticias/2-8-2024-opas-pede-aos-paises-que-reforcem-prevencao-vigilancia-e-diagnostico-do-virus
https://www.paho.org/pt/noticias/6-8-2024-nova-estrategia-busca-na-bvs-para-febre-do-oropouche

**Comment by marcioalvessilva** [comment]
Boa tarde @pintoros, seguem, caso não aprove envio uma nova versão amanhã
Abraço!
![febre-en](https://github.com/user-attachments/assets/9e3e5a86-d551-40a6-a009-0114eb207095)
![febre-es](https://github.com/user-attachments/assets/46e9f9a4-de0b-4a6e-8b48-3861aa4ceb91)
![febre-pt](https://github.com/user-attachments/assets/e879bdf3-437c-4e6e-8b2d-e2e0aa20793d)

**Comment by pintoros** [comment]
Obrigada Márcio, vou tentar subir no regional.
