### ISSUE TITLE
Adicionar Banner sobre Inteligência Artificial

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/artes-graficas#191]
Prezado @marcioalvessilva 
por favor, preciso de um banner para usar na página de consulta ao DeCS Finder, que tenha a opção de ser fechado pelo usuário
e contenha os dizeres:

"Encontre descritores ideais com o DeCS Finder IA
Simplifique a indexação dos seus textos com inteligência artificial. O DeCS Finder IA, desenvolvido pela BIREME, identifica os descritores DeCS/MeSH para o seu conteúdo, de forma rápida e precisa.
Experimente agora e potencialize sua pesquisa!"

Muito obrigada!

**Comment by marcioalvessilva** [comment]
@lucianaPRB pode por favor fazer a tradução para os demais idiomas.

**Comment by lucianaPRB** [comment]
@marcioalvessilva Seguem as traduções:

POR: Encontre descritores ideais com o DeCS Finder IA
Simplifique a indexação dos seus textos com inteligência artificial. O DeCS Finder IA, desenvolvido pela BIREME, identifica os descritores DeCS/MeSH para o seu conteúdo, de forma rápida e precisa.
Experimente agora e potencialize sua pesquisa!

ING: Find ideal descriptors with DeCS Finder IA
Simplify the indexing of your texts with artificial intelligence. DeCS Finder IA, developed by BIREME, identifies DeCS/MeSH descriptors for your content quickly and precisely.
Try it now and boost your search!

ESP: Encuentre los descriptores ideales con DeCS Finder IA
Simplifique la indización de sus textos con inteligencia artificial. DeCS Finder IA, desarrollado por BIREME, identifica descriptores DeCS/MeSH para su contenido de forma rápida y precisa.
¡Pruébelo ahora y potencie su búsqueda!

FRA: Trouvez les descripteurs idéaux avec DeCS Finder IA
Simplifiez l'indexation de vos textes grâce à l'intelligence artificielle. DeCS Finder IA, développé par BIREME, identifie rapidement et précisément les descripteurs DeCS/MeSH de vos contenus.
Essayez-le maintenant et boostez votre recherche !

Obrigada por me lembrar!

**Comment by marcioalvessilva** [comment]
@heitorbarbieri conforma comentei segue orientações para inserir modal no DeCS Finder IA

### *************** 1 - Criar arquivo modal ou inserir no final do arquivo index ***************
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">DeCS Finder IA</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Encontre descritores ideais com o DeCS Finder IA
        Simplifique a indexação dos seus textos com inteligência artificial. O DeCS Finder IA, desenvolvido pela BIREME, identifica os descritores DeCS/MeSH para o seu conteúdo, de forma rápida e precisa.
        Experimente agora e potencialize sua pesquisa!
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    $('#myModal').modal('show');
  });
</script>


### *************** 2 - Atualizar textos  ***************
Textos estão neste mesmo issue acima (PT, EN, ES, FR)


### *************** 3 - Fazer a chamada o arquivo modal no final do documento ***************
<?php include ('modal.php') ?>

**Comment by marcioalvessilva** [comment]
Finalizado!
