### ISSUE TITLE
https://logos.bireme.org/ - atualizaçao arquivos 

### ISSUE THREAD

**Issue by anafranzon** [bireme/artes-graficas#193]
Pessoal, bom dia.

Precisamos por favor atualizar os arquivos da pagina [https://logos.bireme.org]. 1) Alterar a logo OPAS para a versao 2024, e 2) alterar a logo BIREME para a versao mais recente (tamanho de fonte aumentada e excluindo o nome por extenso).

Segue link para arquivos atualizados da OPAS - https://paho.sharepoint.com/sites/Intra-CMU/SitePages/es/Brand-Logos.aspx

Obrigada.

**Comment by marcioalvessilva** [comment]
Essa atividade está em andamento com o Lucas, são muitos formatos, em breve acredito que ele consiga realizar essa entrega

**Comment by marcioalvessilva** [comment]
bom dia! @anafranzon
Página de logos atualizada.

**Comment by anafranzon** [comment]
Oi Márcio, aparentemente as atualizações ainda não estão visíveis para mim? Pode conferir por favor?https://logos.bireme.org/ Obrigada.

**Comment by marcioalvessilva** [comment]
Limpa o cache, acredito que vai aparecer
![image](https://github.com/user-attachments/assets/11e6d6c9-ab70-45d1-a4f4-e0f4c63f237e)

**Comment by marcioalvessilva** [comment]
@anafranzon , Não serão todos os site atualizado automaticamente,
Alguns sites usa essa url para buscar o logo outro são inseridos diretamente.
Abre outro issue e lista os site que você encontrar que não tenham trocado, como esse é um recurso que aplico um a um.

Abraço!
