### ISSUE TITLE
Fique por Dentro

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/artes-graficas#194]
Oi, Márcio, tudo bem?

Como nos anos anteriores, você pode criar novas “carinhas” para o Fique Por Dentro (FpD) para escolhermos e adotarmos em 2025? 
Desculpas que não uso o GitHub. Obrigada, um abç.
Silvia AT, AM BIR
Silvia AT

**Comment by ramosluc** [comment]
Segue modelos para visualização conforme solicitado.
![fpd_01](https://github.com/user-attachments/assets/b09f2f49-57f4-4dd9-824c-665ce25c15ae)
![fpd_02](https://github.com/user-attachments/assets/6f0ba5ae-8d0f-4e88-8179-f9120421d988)
![fpd_03](https://github.com/user-attachments/assets/759f57bc-2918-4c2e-914f-94a0e8f6024b)
![fpd_04](https://github.com/user-attachments/assets/a8030245-ab14-4008-a852-7ee929af3d46)
![fpd_05](https://github.com/user-
[editavel_fpd.zip](https://github.com/user-attachments/files/17982115/editavel_fpd.zip)
attachments/assets/c07c9025-e790-4f86-ba83-85594c604332)


Também editável

**Comment by marcioalvessilva** [comment]
Seguem minhas sugestões

### 1
![1](https://github.com/user-attachments/assets/4d25cc1c-3815-4e39-9038-67d3ebdc9596)

### 2
![2](https://github.com/user-attachments/assets/814c6d45-cd0a-4fbb-8a2e-9bbe38d9102a)

### 3
![3](https://github.com/user-attachments/assets/94ccc5a2-d834-4155-ad5a-e7382fc37213)

**Comment by marcioalvessilva** [comment]
Finalizado!
