### ISSUE TITLE
Atualização dos dados do infográfico para DeCS/MeSH 2021

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#2]
Márcio, em nome do Arthur, peço que sejam atualizados os infográficos com os dados que lhe serão fornecidos posteriormente.

**Comment by marcioalvessilva** [comment]
Recebi os arquivos da @pierrima, fico no aguardo dos dados para atualizar os arquivos.

**Comment by acecampos** [comment]
@marcioalvessilva os dados para a atualização encontram-se no excel em anexo.
[infograficosDeCS2021_ing_esp_por_fra.xlsx](https://github.com/bireme/artes-graficas/files/6670514/infograficosDeCS2021_ing_esp_por_fra.xlsx)

**Comment by marcioalvessilva** [comment]
Bom dia!
@acecampos, @arthurtreuherz  por favor validar
https://github.com/bireme/artes-graficas/tree/main/decs-mesh/infograficos-2021/pdf
Aguardo para inserir no site DeCS/MeSH

**Comment by acecampos** [comment]
Bom dia, @marcioalvessilva! Na minha opinião, está muito bom e pronto para inserir no site. Validado. Agradecida!

**Comment by arthurtreuherz** [comment]
Concordo com a Ana. Está perfeito. Muito obrigado Márcio.

**Comment by marcioalvessilva** [comment]
Site atualizado

**Comment by renatomurasaki** [comment]
@arthurtreuherz @acecampos precisa deixar "beta version edition" no infográfico? Acho que os números não se alterarão, concordam?

**Comment by arthurtreuherz** [comment]
Renato, você tem toda razão. Ainda mais por serem números arredondados. 
Sinto muito Márcio. Por favor, altere para 
português: edição 2021
espanhol: edición 2021
inglês: 2021 edition
francês: édition 2021

**Comment by renatomurasaki** [comment]
@marcioalvessilva reabri para atualizar o texto da edição 2021

**Comment by marcioalvessilva** [comment]
Site e Imagens atualizadas!

**Comment by renatomurasaki** [comment]
Obrigado!
