### ISSUE TITLE
Desenvolver imagens Vitrine MTCI

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#21]
Marina, boa tarde!

Solicito criar imagens para a Vitrine da BVS MTCI, seguindo o modelo da seção "Temas Relevantes" da vitrine de Covid da BIREME.

Os "botões" não precisam ser exatamente iguais, mas seguir a ideia e manter a cor esverdeada da vitrine MTCI e se possível usar ícones antes do título para cada tema, seguindo o modelo de ícone que já está na aranha

![image](https://user-images.githubusercontent.com/13439949/131578283-dd55e66d-63cc-44e6-932e-251d49a53fab.png)

Seguem os temas:
2.1 Salud ocupacional y teletrabajo
2.2 Fortalecimiento del sistema inmunológico
2.3 Salud Mental
2.4 Autocuidado de los profesionales de la salud
2.5 Manejo del estrés
2.6 Contribuciones de las MTCI en el manejo complementario de los síntomas clínicos
2.7 Perspectiva para la salud espiritual de MTCI
2.8 Alimentos y nutrición para el fortalecimiento de la salud
2.9 Grupos étnicos de las Américas en el contexto e COVID-19
2.10 Iniciativas de investigación en curso en el contexto de la pandemia de COVID-19
2.11 Iniciativas Gubernamentales para el tratamiento complementario de la contingencia por COVID-19 con MTCI

![image](https://user-images.githubusercontent.com/13439949/131578352-71170150-d3f4-4f89-8332-eac7030e94f1.png)
modelo vitrine COVID BIREME

**Comment by pierrima** [comment]
Olá Juliana, boa tarde
Estou trabalhando no desenvolvimento dessa imagens porém é necessário reduzir muito o texto para que o conteúdo caiba no botão. Caso não seja possível, sugiro repensar a forma de apresentar esse conteúdo ou trabalhar somente com os ícones.
Abraços

**Comment by sousajul** [comment]
@pierrima ainda estou no aguardo do retorno da equipe da BVS MTCI, vamos ter outra reunião essa semana e veremos se conseguimos definir.

**Comment by sousajul** [comment]
@pierrima e equipe da BVS MTCI confirmou trabalharmos apenas com os icones e títulos ao lado. A ideia é que esta seção fique da seguinte forma, de acordo com a vitrine (https://bvsalud.org/vitrinas/post_vitrines/agenda-de-saude-sustentavel-para-as-americas-2030/).

Vai ser o ícone, título, talvez uma breve descrição, e o link para a busca na BVS

![image](https://user-images.githubusercontent.com/13439949/136081910-e09520cf-8e21-4034-acf8-3871b01509bb.png)
