### ISSUE TITLE
Global Evidence-to-Policy Summit - Flyer

### ISSUE THREAD

**Issue by pierrima** [bireme/artes-graficas#23]
Criação do flyer para Global Evidence-to-Policy Summit
@renatomurasaki Uma dúvida, como marco a Veronica? Obrigada

![modelo](https://user-images.githubusercontent.com/13052947/131736850-11611770-cba3-4c08-b920-3b6b0ddd0408.jpg)

**Comment by renatomurasaki** [comment]
@pierrima incluimos o usuário da Verônica no grupo da BIREME no Github para que apareça quando você digitar o arroba. Por enquanto, como sei qual é o usuário dela, dá para marcá-la usando @veronicaabdala

**Comment by renatomurasaki** [comment]
a @veronicaabdala precisa aceitar o convite que o github envia por e-mail para que o usuário dela apareça nas menções. Mesmo não sendo membro ainda, o usuário dela sempre aparecerá ao digitar arroba quando ela for a criadora do issue.

**Comment by pierrima** [comment]
Thank you very much for sharing this first idea with us. We have in the meantime developed the initial introductory/invitation text and a small programme preview, which we would lie to develop into a one pager (with size and format to be advised by you). We are still reviewing and validating the text today, but I am sharing the current, pre-final version already so you can start working on the design. We can then either replace the text or I can just highlight final changes to you.  

 

On your proposed logo and visual concept, there are a few points of feedback and things we would like to try and improve. We are planning to go with your idea to use the same visual theme/look and feel over the website, flyers, social media etc., so I am thinking that designing the invitation may provide additional information?

 

good idea to use a world map and the theme/illustrations of networks, but the current globe with the detached network looks more like a network of satellites or technology. Maybe there is a way to “show” that the network connects people/countries, rather than just surrounding the globe? As an idea, the shape of continents could also be more abstract (for instance using the dots you now have in the background. And if the globe is too limited for designing, maybe a two-dimensional, abstract world map would work better and could also fade over into the background? (Really just ideas, you may have a better one)
The current view of the globe is maybe a little too Americas focused, e.g. South America should of course be prominently visible, but maybe some more of Africa and the middle east, too?
The overall color theme and background appears a little too dark to me, and the mix of lines/dots in the background are visually too complex? Maybe we can go with the color shades/segments OR the dots (not both?)
make background less complex, e.g. just one light color
The yellow design and text elements stand out very strongly – maybe that can be softened, and I would here use lines OR dots, not both.
