### ISSUE TITLE
Flyer Save the Date - EVIPNet Global Meeting

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/artes-graficas#24]
desenvolver flyer de acordo com as indicações:
- Keep the design simple, clean, attractive
- Focus on the idea of a world interconnecting/global network with the key message rather focusing on KT in emergencies (than COVID-19 as such)

**Comment by renatomurasaki** [comment]
@pierrima este issue é duplicado do #23? Se sim, por favor, fechar este.

**Comment by pierrima** [comment]
Olá Veronica, bom dia
Segue a nova proposta considerando o feedback da contraparte.
Abraços
![modelo2](https://user-images.githubusercontent.com/13052947/132018875-ae8b7970-4b71-41d1-baff-00464c83575d.jpg)

**Comment by pierrima** [comment]
Olá Veronica,

Conforme reunião realizada segue mais uma proposta para o save the date
![modelo3](https://user-images.githubusercontent.com/13052947/132055340-bf46b0cc-4eb3-4c75-8396-9869cf5d2e1f.png)
