### ISSUE TITLE
Destaque portal regional da BVS - Mapa de Evidencias Leishmaniose Visceral

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/artes-graficas#25]
@pierrima Criação do banner para o destaque Mapa de leishmaniose visceral de acordo com o indicado na planilha - destaque para a semana de 6 setembro

**Comment by pierrima** [comment]
Olá Veronica, boa tarde
Seguem os banners para aprovação.
Abraços
![leishmaniose_pt](https://user-images.githubusercontent.com/13052947/131887950-46d0e095-53a4-4f8d-8191-25a67236fa87.jpg)
![leishmaniose_en](https://user-images.githubusercontent.com/13052947/131887956-f36c3ddb-bdab-4859-83b9-cc1318a1f09c.jpg)
![leishmaniose_es](https://user-images.githubusercontent.com/13052947/131887963-60262dcf-2b3d-47c2-8b2c-03c2878100c1.jpg)
