### ISSUE TITLE
Destaque Portal Regional da BVS - Terromoto Haiti

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/artes-graficas#26]
@pierrima Criar uma página intermediária entre o destaque e o resultado de busca, com itens de conteúdos. Rosemeire está trabalhando na proposta de página intermediária, que deve ter o mesmo banner aplicado na página principal do Portal BVS Regional. 
Publicar este destaque para a semana 6/set/2021

**Comment by pierrima** [comment]
Olá Veronica, boa tarde
Seguem os banners  nos 3 idiomas e aguardo o conteúdo para a criação da página.
Abraços
![haiti_es](https://user-images.githubusercontent.com/13052947/131883094-71286733-6b63-43c9-8c88-c158ac09c06c.jpg)
![haiti_en](https://user-images.githubusercontent.com/13052947/131883105-d7757b55-8918-4831-8764-524e2ea82673.jpg)
![haiti_pt](https://user-images.githubusercontent.com/13052947/131883117-ac4a4ff5-8cff-46b0-8aa4-10969db7400e.jpg)

**Comment by pintoros** [comment]
@pierrima por favor acessar o conteúdo da página em: https://paho.sharepoint.com/:w:/s/BIR/TC/Ebe8zNRlN-9Hox_iY_4PwPUBntkSiOHu5BryDJAJEVT-wQ?email=pintoros%40paho.org&e=4%3AA1qCms&at=9&CID=b941d50c-75f1-6b36-3408-72b0af740a0b

E a frase do banner na planilha de destaques em: https://paho.sharepoint.com/:x:/s/BIR/TC/EV0JmIhAsOpFvbREdS0rM6oBIx87TwGkFro3Exqfq7oozg?email=pintoros%40paho.org&e=4%3A13QSWi&at=9&CID=57b8f5e0-8bad-6a53-f1f7-253291e14d1b

**Comment by pierrima** [comment]
@pintoros A página foi criada. Por favor, verifique se está de acordo e se os links estão corretos:

https://bvsalud.org/2021/09/03/haiti-earthquake-seisme-haiti-terremoto-no-haiti-terremoto-de-haiti/

Abraços

**Comment by pintoros** [comment]
Marina favor corrigir link ingles do documento Field manual: PAHO/WHO regional disaster response team | Guía de campo: equipo regional de respuesta a desastres de la OPS/OMS

Ajustar a informação de link no  documento Caribbean Shelter Guide... é um único link para os 2 idiomas e não o mesmo link em cada ENG/SPA

**Comment by pierrima** [comment]
Rose, bom dia
Links corrigidos. Por favor, verificar se estão ok.

**Comment by pierrima** [comment]
Destaques publicados nos 3 idiomas. Por favor, validarem
@veronicaabdala e @pintoros
