### ISSUE TITLE
Vitrine PIE - Projeto DeCIT

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#29]
@pierrima solicito montar o mockup da vitrine de PIE  com base nas áreas pré-definidas (anexo) 

As áreas estão todas de acordo com o manual de vitrines. A primeira com os 8 links já é a aranha, as demais conteúdo, mideas, links, about e funding. (anexo)

Na próxima 4a feira a Verônica tem uma reunião com a equipe e gostaria de apresentar a proposta.

[Script for Window of Knowledge_09_09_21.docx](https://github.com/bireme/artes-graficas/files/7139783/Script.for.Window.of.Knowledge_09_09_21.docx)

**Comment by pierrima** [comment]
@pintoros Bom dia

Segue a proposta para a vitrine.
Abraços
![proposta](https://user-images.githubusercontent.com/13052947/133441030-6b7e5860-bd7b-4996-9df8-66110ca01fcb.png)

**Comment by pierrima** [comment]
Olá Rose, boa tarde

Segue a proposta com as modificações solicitadas. 
![proposta2](https://user-images.githubusercontent.com/13052947/134243158-4b8177c3-4b1b-4e99-b418-35453c106e2a.png)
@veronicaabdala

**Comment by veronicaabdala** [comment]
@pierrima @pintoros eu gosto muito do design, cores, etc... Mas acho que a imagem central está destacando muito um computador e neste processo de tomada de decisão, de formulação de políticas, seria mais interessante dar maior destaque para o processo, a articulação, a política... podemos usar também a ideia de aproximação da ciência às decisões em saúde. Acho que precisaria tirar o computador do destaque na imagem. Deu para captar a ideia??

**Comment by pierrima** [comment]
@pintoros Rose, boa tarde
Realizei as modificações indicadas na última reunião:
- Escureci o tom do laranja
- Retirei os números
- inclui os ícones na aranha
- inclui a área de cursos novamente

Abraços
![proposta3](https://user-images.githubusercontent.com/13052947/135509093-75cd791b-f0cc-46c6-b4cf-e273c9de81b5.png)

**Comment by pierrima** [comment]
Vitrine criada e publicada
