### ISSUE TITLE
Desenvolver proposta de banner, padrão e-BlueInfo, para as novas comunidades de El Salvador

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/artes-graficas#3]
Os banneres deverão ser baseados nas imagens enviadas pela equipe do Comitê Local de Conteúdos de El Salvador, de acordo com o e-mail "solicitud y consulta sobre e-blueInfo El Salvador". Neste e-mail há um link para download do arquivo ZIP, que possui a seguinte estrutura:

|__APS
|__Educación continua
|__Herramientas en salud
|__Investigación
|__Situación epidemiológica

O App manterá a comunidade COVID-19 atual e acrescentará estas 4 novas comunidades, cujos nomes são, respectivamente:

Atención primaria en salud
Educación continua
Herramientas en salud
Investigación y evidencia científica
Situación epidemiológica

**Comment by renatomurasaki** [comment]
@marcioalvessilva favor preparar a primeira proposta e versionar no Github. Solicitarei que a contraparte valide a partir dos links que enviarei deste repositório

**Comment by marcioalvessilva** [comment]
Segue link dos banners
https://github.com/bireme/artes-graficas/tree/main/eblueinfo/banner-app/jpg

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado, mensagem enviada para o Comitê Local de Conteúdos de El Salvador, solicitando aprovação. Aguardemos.

**Comment by marcioalvessilva** [comment]
Aprovado!
