### ISSUE TITLE
Destaque portal regional 20/09

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#31]
Marina, solicito desenvolver o banner para o destaque de 20/09 - tema Bem Estar nas Américas - Vitrine do Conhecimento. 
Informação na planilha.

**Comment by pierrima** [comment]
Olá Rose, boa tarde

Segue o destaque nos 3 idiomas. Por favor, veja se está de acordo.

Abraços
![semana_bem_estar_pt](https://user-images.githubusercontent.com/13052947/133658457-d977ad0c-d9d6-4c6a-b7c3-6bdbec3d4aad.png)
![semana_bem_estar_es](https://user-images.githubusercontent.com/13052947/133658462-28f22dc9-0948-4945-8966-80a054262989.png)
![semana_bem_estar_en](https://user-images.githubusercontent.com/13052947/133658466-be92dafd-c7ed-4619-ab35-2b8dbd520e72.png)

**Comment by pierrima** [comment]
@veronicaabdala Segue o destaque nos 3 idiomas. Por favor, veja se está de acordo.
