### ISSUE TITLE
Destaque portal regional BVS - 20 SET - Publicação

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/artes-graficas#32]
@pierrima solicito desenvolver o banner para o destaque de 20/09 - o destaque será uma publicação disponível em 3 idiomas:  "Orientações para a aplicação de medidas de saúde pública não farmacológicas a grupos populacionais em situação de vulnerabilidade no contexto da COVID-19" conforme indicado na planilha.

**Comment by pierrima** [comment]
Seguem os banners
![banner_es](https://user-images.githubusercontent.com/13052947/134005664-1724cc23-a35c-4b53-9816-0bbf35952c46.png)
![banner_en](https://user-images.githubusercontent.com/13052947/134005669-c42a9ead-2347-416e-bf5e-a2832d4fd69e.png)
![banner_pt](https://user-images.githubusercontent.com/13052947/134005671-72918d87-9a8e-4c91-b7da-4a0a53d07282.png)

**Comment by veronicaabdala** [comment]
@pierrima Marina, aprovado, por favor publicar nos destaques da BVS Regional
