### ISSUE TITLE
Vitrine DCDSS - OPAS BRA

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#36]
@pierrima solicito criar mockup para apresentação e aprovação da vitrine acima. Conteúdo de acordo com e-mail enviado.
Obrigada

**Comment by pierrima** [comment]
@pintoros e @veronicaabdala Segue a proposta para a vitrine.
![proposta](https://user-images.githubusercontent.com/13052947/134410429-b49f90cd-1f5c-4a77-9d5b-572e71b0ffea.png)

**Comment by pierrima** [comment]
Vitrine criada e publicada
