### ISSUE TITLE
Guias e manuais da LILACS

### ISSUE THREAD

**Issue by suelisuga** [bireme/artes-graficas#38]
Solicito customização da CSS da área de guias e manuais da LILACS implantada com plug-in DocPress.

Muito obrigda!

**Comment by pierrima** [comment]
@suelisuga Realizei as customizações solicitadas na  área de guias e manuais. Por favor, poderia verificar se estão ok?

https://lilacs.teste.bvsalud.org/guias-e-manuais/docs-2/guia-de-boas-praticas-para-periodicos-lilacs-2/gestao-de-periodicos-cientificos-etapas-acoes-e-participantes-dos-processos-editoriais/

Obrigada e abraços

**Comment by suelisuga** [comment]
@pierrima Alguns apontamentos:

Tamanho da imagem:
Ora as imagens são pequenas e tenho que colocá-las no tamanho inteiro
Ora as imagens são grandes demais. Nesse exemplo coloquei como tamanho 500 para diminuir:
![image](https://user-images.githubusercontent.com/13105683/137830055-bd9a2b23-5c91-413a-88c1-353c69fe226a.png)

https://lilacs.teste.bvsalud.org/guias-e-manuais/es/docs/guia-de-buenas-practicas-para-revistas-lilacs-2/comunicacion-cientifica-eficaz-en-las-ciencias-de-la-salud/

e Bullets não são aplicados. No aparece uma fonte desconfigurada:
![image](https://user-images.githubusercontent.com/13105683/137830275-9da003ae-12a2-481f-8d2a-eb5657e68249.png)

Era para ser assim:
![image](https://user-images.githubusercontent.com/13105683/137830321-4b91580b-f034-48c9-9585-8e218c462982.png)
Link:https://lilacs.teste.bvsalud.org/guias-e-manuais/es/docs/guia-de-buenas-practicas-para-revistas-lilacs-2/gestion-de-revistas-cientificas-etapas-acciones-y-participantes-de-los-procesos-editoriales/

Obrigada!

**Comment by suelisuga** [comment]
@pierrima Bullets numerados também não são apresentados, porém o texto indica essa numeração, então será necessário que as referências seja numeradas.
![image](https://user-images.githubusercontent.com/13105683/137841954-2f4ce382-de83-4fb4-85a1-26666a9c66bb.png)

No texto:
![image](https://user-images.githubusercontent.com/13105683/137842001-218958d9-0d0d-42f0-ac0a-839cb1fab5c2.png)

Obrigada

**Comment by suelisuga** [comment]
Fonte em itálico não está sendo aplicada, assim como o tipo de estilo
![image](https://user-images.githubusercontent.com/13105683/148129595-21add313-ff2e-47ab-b236-a7b6a2899bb3.png)

**Comment by suelisuga** [comment]
Revisando:

- Bullets: foi aplicado, porém a fonte continua desconfigurada

![image](https://user-images.githubusercontent.com/13105683/159976871-b2d3eb5d-f342-4801-90d2-3b721e0dc554.png)

Essa tabela com bullets ficou desconfigurada:
![image](https://user-images.githubusercontent.com/13105683/160115365-a2c4fd49-14a3-47a6-9868-215286c44a94.png)

- Imagens: me parecem bem ![bitmoji](https://sdk.bitmoji.com/render/panel/12f3a5e1-c85f-49cd-94f4-6dce9cb18ef1-b56af15d-58b6-4e02-b7ab-1fa892a3ef6a-v1.png?transparent=1&palette=1&width=246)

![image](https://user-images.githubusercontent.com/13105683/159981130-9f380e06-0c6f-4ec1-875e-0c79b5516732.png)

- Estilos e italicos ![bitmoji](https://sdk.bitmoji.com/render/panel/12f3a5e1-c85f-49cd-94f4-6dce9cb18ef1-b56af15d-58b6-4e02-b7ab-1fa892a3ef6a-v1.png?transparent=1&palette=1&width=246)
![image](https://user-images.githubusercontent.com/13105683/159981821-08679db1-488b-4c1e-aebe-d54ee1275feb.png)

Creio que seja isso.

Muito obrigada @pierrima

**Comment by suelisuga** [comment]
Tudo corrigido! Muitíssimo obrigada @pierrima ![bitmoji](https://sdk.bitmoji.com/render/panel/b6dbf504-c36d-498c-acf9-c7350b749221-b56af15d-58b6-4e02-b7ab-1fa892a3ef6a-v1.png?transparent=1&palette=1&width=246)
