### ISSUE TITLE
Imagens BVS Costa Rica

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#39]
@pierrima solicito criar as seguintes imagens para a BVS Costa Rica:

- Na seção Literatura Científica criar uma nova imagem com o título: Editorial Nacional de Salud y Seguridad Social (EDNASSS) para substituir a imagem Proyecto Cancer
![image](https://user-images.githubusercontent.com/13439949/134586190-1bb181bc-ba61-4d33-9940-886a6343fdc0.png)

- Na seção temas, enviar proposta de imagem para os temas: Salud mental y Tabaco
![image](https://user-images.githubusercontent.com/13439949/134586439-1ffb6b3d-c502-4667-9dc1-6ec63b519c0d.png)

**Comment by pierrima** [comment]
Olá @sousajul, boa tarde
Seguem as imagens solicitadas. Abraços
![tabaco](https://user-images.githubusercontent.com/13052947/134733228-8466df64-8612-47d2-a4c6-adb47485eaa4.png)
![saude_mental](https://user-images.githubusercontent.com/13052947/134733232-e682469b-b53a-4e6c-b1af-918f4e2b948d.png)
![EDNASSS](https://user-images.githubusercontent.com/13052947/134733233-9e5d2fe0-107b-4fd8-b62c-f4d1b395aef3.png)

**Comment by sousajul** [comment]
Obrigada Marina.

Abraços,
