### ISSUE TITLE
Envio de banner e link da BVS para Senac Pernambuco

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/artes-graficas#40]
Marina,
Recebemos uma solicitação através do Livezilla e transcrevo abaixo as mensagens trocadas:

![image](https://user-images.githubusercontent.com/38661168/134724515-486b2ab6-93e2-434b-9e6c-4f65fc9b8e0b.png)

![image](https://user-images.githubusercontent.com/38661168/134724454-91fa6e8a-625d-4a8f-a581-e25ed37a5f7f.png)

![image](https://user-images.githubusercontent.com/38661168/134724378-ea97ee0a-b73f-448f-bc47-610c568cb197.png)

![image](https://user-images.githubusercontent.com/38661168/134724186-c0fbaf95-eb47-4b8f-823f-24ea5381e133.png)

Enviei para seu e-mail cópia das mensagens trocadas com Dr. Diego e área legal da PAHO com respectiva autorização.

Aguardo posição.
Obrigada!
@pintoros
@veronicaabdala

**Comment by pierrima** [comment]
Olá @alvesmarilda,

Segue o logo nos formatos Adobe Illustrator | JPG | PNG | PSD | SVG 

[bvs_all 2.zip](https://github.com/bireme/artes-graficas/files/7228180/bvs_all.2.zip)
 
Abraços
