### ISSUE TITLE
Banner para carrossel sobre consulta pública - revisão SP

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#5]
Bom dia, Márcio!
Por favor, criar um componente do carrossel que contenha mais ou menos o modelo abaixo. Os links remeterão para páginas a serem criadas no Wordpress e no Google forms (ou outro formulário). 

Grata!

**Comment by acecampos** [comment]
![image](https://user-images.githubusercontent.com/35345406/128184385-25de38c0-9c78-48b5-8d09-1c5d2b31edd3.png)

**Comment by acecampos** [comment]
Agora, sim, com a imagem.

**Comment by renatomurasaki** [comment]
@acecampos creio que para o carrossel não precise do faça a sua contribuição aqui e nem do link para documento técnico, certo? Poderia ter um texto mais chamativo para pedir colaboração da rede, o que acha?

A estrutura que você mostra na imagem poderia estar em uma única página do WordPress, repetindo para cada uma das categorias de SP, juntamente com um texto introdutório. O que acha?

**Comment by marcioalvessilva** [comment]
Boa tarde! @renatomurasaki e @acecampos 
No banner não é possível inserir dois links diferentes, como o Renato informou isso deve estar dentro da página!
Fico a disposição para ajudar no que for necessário.

**Comment by renatomurasaki** [comment]
@marcioalvessilva sim, o link seria para a página com a informação técnica da consulta pública

**Comment by acecampos** [comment]
@renatomurasaki, grata; entendido. Então, serão 16 documentos (8 ES e 8 PT).
@marcioalvessilva, conforme conversado, seguem as sugestões para os banners para o carrossel no portal do DeCS, em português e espanhol:
![CP-banner-ES](https://user-images.githubusercontent.com/35345406/128234948-fc3ef297-9bf3-4fb6-bd2e-95f415ed29bb.jpg)
![CP-banner-PT](https://user-images.githubusercontent.com/35345406/128234952-12184ca2-30af-4f48-81df-8daaeee2d91a.jpg)
 Agradecida!

**Comment by renatomurasaki** [comment]
@acecampos na prática, teremos 2 páginas, uma em português e outra em espanhol. Nesta página teremos uma lista contendo os links para os 16 documentos técnicos e para o formulário do Google para receber os comentários e recomendações. Se tiverem dúvidas, por favor, agendem uma reunião.

**Comment by marcioalvessilva** [comment]
Segue imagem para banners
![image](https://user-images.githubusercontent.com/48724136/128527457-5deb51de-01bf-4aa9-b98e-203fbd2cd85d.png)

Link para versões em espanhol e mobile
https://github.com/bireme/artes-graficas/tree/main/banners-sites/decs/consulta-publica/jpg

**Comment by renatomurasaki** [comment]
@marcioalvessilva achei ótimo. @acecampos @arthurtreuherz o que acharam?

@acecampos vou criar um novo issue para elaboração da página que terá os links para os documentos técnicos de cada uma das subcategorias.

**Comment by acecampos** [comment]
@marcioalvessilva o layout está muito bonito! Por favor, retirar a crase da frente da data no banner em português. No banner em espanhol por favor, consertar nas datas a parte que está negritada aqui: **del** 06/**Sep**/2021 **al**24/**Oct**/2021. Grata!

**Comment by arthurtreuherz** [comment]
Muito bom Márcio, concordo com os comentários da Ana.

**Comment by marcioalvessilva** [comment]
Atualizados!
https://github.com/bireme/artes-graficas/tree/main/banners-sites/decs/consulta-publica/jpg

**Comment by arthurtreuherz** [comment]
Excelente Márcio. Apenas trocar Set para Sep no primeiro arquivo em espanhol. E sugiro tirar o hífen, já que tem "de ... a ..."

**Comment by marcioalvessilva** [comment]
Atualizados!

**Comment by acecampos** [comment]
Agradeço, @marcioalvessilva! Ficaram muito bonitos!

**Comment by arthurtreuherz** [comment]
Excelente @marcioalvessilva ! Obrigado.

**Comment by renatomurasaki** [comment]
@acecampos pode publicar o banner no carrossel com link para a página https://decs.bvsalud.org/vaga-analista-informacao-2021/

**Comment by acecampos** [comment]
@renatomurasaki Não entendi 100%. Não há um banner específico para a vaga de analista. Devo solicitar que @marcioalvessilva crie um? Ou devemos colocar a página da vaga de analista no banner sobre a Consulta Pública da revisão SP?

**Comment by renatomurasaki** [comment]
@acecampos perdão, me confundi no momento do copy&paste. Qdo criar a página com a informação dos documentos técnicos vcs podem publicar o banner e usar o link para está página. No caso da vaga, favor criar issue para o @marcioalvessilva fazer um banner

**Comment by acecampos** [comment]
@renatomurasaki ok, sem problemas!
