### ISSUE TITLE
Destaque BVS Regional - 18-10

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#51]
@pierrima por favor criar destaque no Portal Regional com link para página (mesmo modelo do terremoto no Haiti). O tema é Vacina contra Malária. Conteúdo em anexo.

Obrigada
[Malaria Vaccine Destaque.docx](https://github.com/bireme/artes-graficas/files/7355376/Malaria.Vaccine.Destaque.docx)

**Comment by pierrima** [comment]
Destaque criado e publicado
