### ISSUE TITLE
Customizar vitrina MTCI

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#52]
Marina, solicito seu apoio para customizar a Vitrine da BVS MTCI disponível em: https://mtci.bvsalud.org/vitrinas/post_vitrines/contribuciones-de-las-mtci-en-pandemia-por-covid-19/. 

Pode ser que peça uma senha para entrar pois está "protegida" e a senha é mtci. 
A senha de autenticação do WP é login: admin-mtc / senha: mtc@2019#
A senha do WP é: biradmin / Ver...

Itens a desenvolver:

1. Trabalhar as cores as seções e títulos no geral
2. A seção "Contribuciones relevantes de la MTCI en el contexto del COVID-19" deve ser desenvolvido de acordo com a issue #21
3. Ajustar a seção "Información de los países" que está muito próxima das margens
4. A seção "Videos, Simposios e Infográficos" tem que desenvolver imagens representativas para esses conteúdos
5. Incluir uma área para agradecimentos 

Qualquer dúvida me avise.
Obrigada.

**Comment by sousajul** [comment]
@pierrima a ideia é os títulos fiquem como texto, dai incluímos um ícone para cada um e e ter uma cor de fundo assim como no exemplo apresentado na issue Desenvolver imagens Vitrine MTCI #21. Você consegue fazer uma nova proposta?

**Comment by pierrima** [comment]
Juliana, boa tarde

As customizações foram realizadas. Por favor, verificar se está de acordo
