### ISSUE TITLE
Criar imagens para temas BVS Guatemala

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#53]
Marina, solicito seu apoio para definir imagens para os seguintes temas da BVS Guatemala (https://guatemala.teste.bvsalud.org/). As imagens serão aprovadas pela equipe da Guatemala. 
No aguardo.

seção:
![image](https://user-images.githubusercontent.com/13439949/138334118-ecc5d5d6-c37f-45c9-96d4-6b0f67776ca4.png)

        1) Enfermedades crónicas no transmisibles

        2) Salud mental

        3) Morbilidad y mortalidad materna y neonatal 

        4) Salud sexual y reproductiva

        5) Seguridad alimentaria y nutricional

        6) Recursos Naturales y Ambiente

        7) Asentamientos Humanos

        8) Salud pública y medicina preventiva

        9) Cambio climático

**Comment by pierrima** [comment]
Olá Juliana, boa tarde

Seguem as imagens solicitas
![Asentamientos-Humanos](https://user-images.githubusercontent.com/13052947/160903283-93b8409e-77c2-4030-ba4f-b90ae6e48f67.png)
![Cambio-climATIico](https://user-images.githubusercontent.com/13052947/160903292-1a7fac2b-4e03-4836-a231-89ac317b1ee9.png)
![Enfermedades-cronicas-no-transmisibles](https://user-images.githubusercontent.com/13052947/160903295-6d582366-36db-4801-ab92-7a306d7e2672.png)
![Morbilidad-y-mortalidad-materna-y-neonatal](https://user-images.githubusercontent.com/13052947/160903296-7888e1ac-e8e1-4027-99a6-f20bbc9f270f.png)
![Recursos-Naturales-y-Ambiente](https://user-images.githubusercontent.com/13052947/160903299-b5b8b65b-5be2-479e-a83d-4211dfde8c2f.png)
![Salud-mental](https://user-images.githubusercontent.com/13052947/160903300-3417d30e-fa82-470f-ad1b-5546814b7412.png)
![Salud-pública-y-medicina-preventiva](https://user-images.githubusercontent.com/13052947/160903304-2c9135e8-1fa6-4f1e-bc24-1edba70a4f03.png)
![Salud-sexual-y-reproductiva](https://user-images.githubusercontent.com/13052947/160903305-05691bfc-2bd4-4432-9355-a2a4a036772c.png)
![Seguridad-alimentaria-y-nutricional](https://user-images.githubusercontent.com/13052947/160903309-80dffe55-491a-47c1-80be-7d531687213f.png)
