### ISSUE TITLE
Incluir novo destaque no carrossel do GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/artes-graficas#55]
Título - WHO’s 7 policy recommendations on building resilient health systems
Imagem - 
![image](https://user-images.githubusercontent.com/1226218/139052319-b9d513ce-1586-402b-b6d9-bc9b70cb957a.png)

Link para YouTube - https://www.youtube.com/watch?v=K6JYGnwy2fw

**Comment by marcioalvessilva** [comment]
Concluído
