### ISSUE TITLE
Vitrine CNS - BVS Brasil

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#56]
@pierrima solicito a criação de uma Vitrine para o Conselho Nacional de Saúde. 

Para referÊncia de cor e imagens, sugiro o próprio site da CNS - http://conselho.saude.gov.br/ ou o mesmo padrão utilizado na Biblioteca que está sendo desenvolvida. 

Anexo a estrutura da Vitrine com os destaques e áreas. Serão 18 temas na parte de conteúdo, porém esses temas só contarão com o título, uma frase e um link para resultado de busca na BVS. 
[Vitrine CNS.docx](https://github.com/bireme/artes-graficas/files/7477229/Vitrine.CNS.docx)
![cns](https://user-images.githubusercontent.com/29313904/140396007-9da42834-2866-4390-a273-6c452e670788.jpg)

**Comment by pintoros** [comment]
@pierrima a vitrine do CNS foi publicada na BVS Brasil e está disponível em  https://brasil.bvs.br/vitrinas/post_vitrines/cns/
Como sugerido, a consultora publicou o conteúdo utilizando o formulário, porém precisa de customização de imagem e cores para harmonizar com o Portal CNS.
A área de publicações também não está aparecendo apesar de ter conteúdo.
Obrigada

**Comment by pierrima** [comment]
Olá Rose, boa tarde

Customização realizada. Por favor, veja se está de acordo
