### ISSUE TITLE
Flyer Webinarios sobre Buenas Prácticas en los Procesos Editoriales de Revistas Científicas para LILACS (2022)

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/artes-graficas#58]
Solicito criação de flyer para Webinarios sobre Buenas Prácticas en los Procesos Editoriales de Revistas Científicas para LILACS (2022)
O flyer será em espanhol.

Informações para incluir:

Logo da LILACS (ES)
Logo da BIREME (ES)

Título: Webinarios sobre Buenas Prácticas en los Procesos Editoriales de Revistas Científicas para LILACS (2022)
Horário: 12 PM (Brasília -3 GMT)

Fechas: El tercer miércoles del més

16 de marzo de 2022
20 de abril de 2022
18 de mayo de 2022
15 de junio de 2022
20 de julio de 2022
17 de agosto de 2022
21 de septiembre de 2022
19 de octubre de 2022
16 de noviembre de 2022

https://lilacs.bvsalud.org/es/sesiones-virtuales-lilacs/buenas-practicas-en-los-procesos-editoriales-de-revistas-cientificas-para-lilacs-2022/

Exemplos do ano passado:

![Buenas Prácticas 2021 (9)](https://user-images.githubusercontent.com/47643830/140756397-5cd7df37-ca1a-4c6d-9de0-378d6754609f.jpg)
![1](https://user-images.githubusercontent.com/47643830/140756482-e27f9e6f-00d8-42ea-b8f6-dabf8fe4ecce.jpg)
![2](https://user-images.githubusercontent.com/47643830/140756491-ddc9438b-0b3d-47b1-a53c-406f81333b4b.jpg)

Obrigada!

**Comment by suelisuga** [comment]
@AngelicaSAPaula conteúdo transferido para #59 pois a @pierrima informou ser melhor para ela gerir. Então os 5 flyers estão em um único chamado.

Obrigada!
