### ISSUE TITLE
Flyer Sesión virtual sobre Indización de documentos según la Metodología LILACS (2022)

### ISSUE THREAD

**Issue by suelisuga** [bireme/artes-graficas#59]
Solicito criação de flyer para Webinarios sobre Buenas Prácticas en los Procesos Editoriales de Revistas Científicas para LILACS (2022)
O flyer será em espanhol.

Informações para incluir:

Logo da LILACS (ES)
Logo da BIREME (ES)

Título: Sesión virtual sobre Indización de documentos según la Metodología LILACS (2022)
Horário: 12 PM (Brasília -3 GMT)

Fechas: El cuarto Jueves del més

24 de marzo de 2022
28 de abril de 2022
26 de mayo de 2022
23 de junio de 2022
28 de julio de 2022
25 de agosto de 2022
22 de septiembre de 2022
27 de octubre de 2022
24 de noviembre de 2022

https://lilacs.bvsalud.org/es/sesiones-virtuales-lilacs/indizacion-de-documentos-segun-la-metodologia-lilacs-2022/

Exemplo do ano passado:
![image](https://user-images.githubusercontent.com/13105683/140759273-d3f5fc51-c63a-4a37-a172-4bf8c8ff1e09.png)

**Comment by pierrima** [comment]
Bom dia Marina, tudo bem?

Preciso de três  Template e imagem para capacitações 2022 

Abaixo os dados para o 1º template

Capacitación sobre indización de documentos según la Metodología LILACS (2022)

 Las sesiones ocurren todo cuarto Jueves de cada mes a las 12h00 (Brasilia -3h00 GMT)

24 de Marzo
28 de Abril
26 de Mayo
23 de Junio
28 de Julio
25 de Agosto
22 de Septiembre
27 de Octubre
24 de Noviembre

Visite la página con toda la información: a pagina será criada

Segue exemplo abaixo:



-----------------------------------------------------------------------------------------------------------------------
 
2- template (espanhol)

Capacitación sobre las Fuentes de Información de la BVS para la Red Latinoamericana y del Caribe de Información en Ciencias de la Salud_2022

12:00	13:00	29 de marzo	Metodologia
 LILACS	Monográfico y no convencional
12:00	13:00	30 de marzo	Tesis y disertaciones
12:00	13:00	31 de marzo	Creación de registros bibliográficos y pestaña de indexación - CC
12:00	13:00	1 de abril	Creación de registros bibliográficos con Status LILACS-Express - Editor de revistas
12:00	13:00	4 de abril	Metodologia LIS	Localizador de información de salud: Creación de Recursos de Internet
12:00	13:00	5 de abril	Metodologia- DirEve
Directorio de eventos de salud: Creación de eventos de salud
12:00	13:00	6 de abril	Metodologia - Recursos Educacionales
Creación de Recursos Educativo
12:00	13:00	7 de abril	Metodologia Multimidia	Creación de documentos sobre Multimidia
12:00	13:00	8 de abril	Metodologia Leyes	Creación de documentos sobre legislación

Exemplo: 


____________________________________________________________________


3º  template em português


Capacitação sobre as Fontes de Informação da BVS para a Rede Brasileira de Informação em Ciências da Saúde – 2022
10:00	11:00	29 de março	Metodologia LILACS	Monograficos edocumentos não convencional 
10:00	11:00	30 de março	Teses e dissertações 
10:00	11:00	31 de março	Artigos de revistas - CC 
10:00	11:00	1 de abril	Registros com Status LILACS-Express - editores de revistas
10:00	11:00	4 de abril	Metodologia LIS	Localizador de Informação em Saúde ou Recursos de internet
10:00	11:00	5 de abril	Metodologia DirEve	Diretorio de eventos em Saúde
10:00	11:00	6 de abril	Metodologia Recusrsos Educacionais	Criação de Recursos Educacionais
10:00	11:00	7 de abril	Metodologia Multimidia	Criação de registros Multimidia
10:00	11:00	8 de abril	Metodologia Leyes	Criação de registros Legislação em Saúde

Exemplo: 




Caso necessite de mais informação estou a disposição



Obrigada

**Comment by pierrima** [comment]
Solicito criação de flyer para Webinarios sobre Buenas Prácticas en los Procesos Editoriales de Revistas Científicas para LILACS (2022)
O flyer será em espanhol.

Informações para incluir:

Logo da LILACS (ES)
Logo da BIREME (ES)

Título: Webinarios sobre Buenas Prácticas en los Procesos Editoriales de Revistas Científicas para LILACS (2022)
Horário: 12 PM (Brasília -3 GMT)

Fechas: El tercer miércoles del més

16 de marzo de 2022
20 de abril de 2022
18 de mayo de 2022
15 de junio de 2022
20 de julio de 2022
17 de agosto de 2022
21 de septiembre de 2022
19 de octubre de 2022
16 de noviembre de 2022

https://lilacs.bvsalud.org/es/sesiones-virtuales-lilacs/buenas-practicas-en-los-procesos-editoriales-de-revistas-cientificas-para-lilacs-2022/

Exemplos do ano passado:

Buenas Prácticas 2021 (9)
1
2

Obrigada!

**Comment by suelisuga** [comment]
@pierrima trouxe o conteúdo para cá #57  e encerrei esse chamado.

Solicito criação de flyer para reuniões de coordenação da rede LILACS.
O flyer será em espanhol.

Informações para incluir:

Logo da LILACS (ES)
Logo da BIREME (ES)

Título: Reunión de Coordinación LILACS 2022
Horário: A las 12pm (Brasília -3 GMT)

Fechas: El segundo Martes del més
8 de marzo de 2022
12 de abril de 2022
10 de mayo de 2022
14 de junio de 2022
12 de julio de 2022
9 de agosto de 2022
13 de septiembre de 2022
11 de octubre de 2022
8 de noviembre de 2022

https://lilacs.bvsalud.org/es/sesiones-virtuales-lilacs/sesiones-virtuales-reunion-de-coordinacion-de-la-red-lilacs-2022/

**Comment by pierrima** [comment]
Olá Sueli, boa tarde

Seguem as propostas para os Webinários. Os templates estão em ppt pois dessa maneira é possível editar os textos caso seja necessário. Por favor, vejam se estão de acordo.

[buenas_praticas.pptx](https://github.com/bireme/artes-graficas/files/7583150/buenas_praticas.pptx)
[BVSRedeBrasileira.pptx](https://github.com/bireme/artes-graficas/files/7583151/BVSRedeBrasileira.pptx)
[indizacion_documentos.pptx](https://github.com/bireme/artes-graficas/files/7583153/indizacion_documentos.pptx)
[informacio_Red_Latinoamericana.pptx](https://github.com/bireme/artes-graficas/files/7583155/informacio_Red_Latinoamericana.pptx)
[reuniao_coordenacao.pptx](https://github.com/bireme/artes-graficas/files/7583156/reuniao_coordenacao.pptx)

**Comment by suelisuga** [comment]
Muito obrigada @pierrima Ficou showw! bjks
