### ISSUE TITLE
Banner para vaga de analista da informação no carrossel do DeCS/MeSH

### ISSUE THREAD

**Issue by acecampos** [bireme/artes-graficas#6]
@marcioalvessilva Bom dia! Por favor, criar um banner para a vaga de analista para ser incluído no carrossel do DeCS com os seguintes dizeres:

Oportunidade de trabalho na BIREME com DeCS/MeSH
para informação, _clique aqui_

@arthurtreuherz e @renatomurasaki, acredito que esse banner só ficará na página em português do portal e, portanto, só precisaria fazer um banner no idioma português, certo?

**Comment by arthurtreuherz** [comment]
Eu diria que sim Ana.

**Comment by renatomurasaki** [comment]
Sim

**Comment by acecampos** [comment]
Obrigada, @marcioalvessilva! Está muito bom, na minha opinião. Adorei a tela com o portal do DeCS em perspectiva!

**Comment by renatomurasaki** [comment]
@acecampos @marcioalvessilva excelente! sigam em frente na publicação do banner com link para a página da vaga no site do DeCS.

**Comment by acecampos** [comment]
Grata, @marcioalvessilva
