### ISSUE TITLE
Imagens BVS Hanseníase

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#60]
https://hansen.bvs.br/

Marina produzir um banner para 
- Coleção Obras Raras em Hanseníase para usarmos na página inicial da BVS Hanseníase. Pode seguir a identidade visual dos banners da Coleção do Ministério da Saúde e do Cantinho do Cidadão.

![image](https://user-images.githubusercontent.com/13439949/141475915-5161bfca-fe1a-4807-a061-f18155f5a790.png)

- Aproveitando, poderia produzir também aquele banner azul de título da página, segue modelo:
- O TÍTULO DO BANNER DEVE SER: Coleção Obras Raras em Hanseníase

![image](https://user-images.githubusercontent.com/13439949/141476025-10b41a4f-66b9-4aaf-b4b1-bc1ffb37fb09.png)

**Comment by sousajul** [comment]
@pierrima a equipe da BVS Hanseníase, está no aguardo das imagens. 

Obrigada.

**Comment by pierrima** [comment]
Juliana, boa tarde

Seguem as imagens solicitadas
![obras_raras](https://user-images.githubusercontent.com/13052947/160894699-eb7c0985-f1b1-45bc-a9d8-f65d673e5807.png)
![obras_raras_img](https://user-images.githubusercontent.com/13052947/160894843-087bf427-6a58-4659-9b0c-8b47881f7bd7.png)

Abraços
