### ISSUE TITLE
Imagem para divulgação de vaga interna

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/artes-graficas#62]
Marcio, 

Favor criar imagem (mini-banner) para divulgação da vaga:

Gerente de Metodologia e Tecnologia da Informação

Esta imagem será utilizada no Portal RedDes e também nas comunicações em redes sociais.

Obrigado

**Comment by marcioalvessilva** [comment]
Boa tarde @viniciusandrade, segue banners para o portal RedDes
https://github.com/bireme/artes-graficas/blob/main/banners-sites/reddes/jpg/vaga-gerente.jpg

![image](https://user-images.githubusercontent.com/48724136/145461392-349691d8-fec9-45a0-992e-212d3064c924.png)

**Comment by viniciusandrade** [comment]
Muito obrigado @marcioalvessilva ... já utilizei o banner para divulgar a vaga no [Portal RedDes](https://reddes.bvsalud.org/) e enviei para ADM para ser utilizado nas divulgaçõs em redes sociais.
