### ISSUE TITLE
Criar imagem para destaque curso Google Anlytics

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#65]
Criar imagem para destaque curso Google Anlytics para os canais de comunicação da BIREME (Portal Rede BVS, facebook, twitter).

Link geral: https://www.youtube.com/playlist?list=PLZkQ-JIKvi_1McLfWrEFX-o-fT8Cq_1s3 e pode ser visualizado por módulos.
Módulo 1: https://www.youtube.com/playlist?list=PLZkQ-JIKvi_2I5yQ3wSfueMMFnlU33jK5
Módulo 2: https://www.youtube.com/playlist?list=PLZkQ-JIKvi_0jJ8Lk9q85XZzApmeW8M3-
Módulo 3: https://www.youtube.com/playlist?list=PLZkQ-JIKvi_2xfOrBoIDqumdtD3hKFmSl
Módulo 4: https://www.youtube.com/playlist?list=PLZkQ-JIKvi_2zjMLRxRrKJj3FVnjOdedw
Módulo 5: https://www.youtube.com/playlist?list=PLZkQ-JIKvi_3Ud2WpC6MAq4IHFdfIOdyZ
Módulo 6: https://www.youtube.com/playlist?list=PLZkQ-JIKvi_1NxN6_Pro3AsRK4CcWGfiO
Módulo 7: https://www.youtube.com/playlist?list=PLZkQ-JIKvi_0xydMy49gtDELp_VLvJI9n

**Comment by pierrima** [comment]
Juliana, boa tarde

Segue a imagem solicitada.
![cuso_google](https://user-images.githubusercontent.com/13052947/160671687-99b881d7-0adb-4c36-8c00-b0096931046d.png)

**Comment by sousajul** [comment]
Marina a imagem ficou ótima. Obrigada.
