### ISSUE TITLE
Criar um flyer para divulgar o lançamento do mapa e da vitrine no Seminário 

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/artes-graficas#67]
Bom dia Márcio, 

Muito obrigada pelo envio do material, vou lhe chamar por teams para comentar.

Sobre o material de divulgação dos produtos de nutrição, estou enviando em anexo já copiando a Lilian para contribuições e acompanhamento. 

Também podemos nos reunir e conversar para tirar dúvidas e melhor entendimento da necessidade.

Um abraço, 

________________________________
Material: [material divulgar produtos nutricao.docx](https://github.com/bireme/artes-graficas/files/7996959/material.divulgar.produtos.nutricao.docx)

**Comment by pintoros** [comment]
@marcioalvessilva seguem os links para apontar os destaques:

https://public.tableau.com/app/profile/bireme/viz/ma-nutricao-aps-pt/evidence-map - mapa de evidências

https://brasil.bvs.br/vitrinas/post_vitrines/alimentacao-e-nutricao-em-saude-publica/ - Vitrine do Conhecimento

Somente disponível em PT

**Comment by marcioalvessilva** [comment]
Publicados por favor validar!
