### ISSUE TITLE
Elaborar logo de comemoração dos 35 anos do DeCS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/artes-graficas#7]
Márcio, vamos utilizar este logo para incluir no site do DeCS, em ações de comunicação etc

**Comment by marcioalvessilva** [comment]
@renatomurasaki segue propostas para logo

**Modelo 1** 
![image](https://user-images.githubusercontent.com/48724136/129612093-f0bb8b17-e7dc-4c09-8b4f-a0af68c7e233.png)


**Modelo 2**
![image](https://user-images.githubusercontent.com/48724136/129612117-a1d68d85-8d89-4019-9126-dcc08903ca4a.png)


**Modelo 3**
![image](https://user-images.githubusercontent.com/48724136/129612172-d61ce625-0aee-4153-9bff-c145a9e89d09.png)

**Comment by marcioalvessilva** [comment]
@renatomurasaki com base no voto da maioria, fiz a versão em espanhol para o logo de 35 anos do DeCS/MeSH

https://github.com/bireme/artes-graficas/tree/main/decs-mesh/logo%2035%20anos/jpg

Versão png - Sem fundo e Versão com texto branco
https://github.com/bireme/artes-graficas/tree/main/decs-mesh/logo%2035%20anos/png

**Comment by renatomurasaki** [comment]
@marcioalvessilva perfeito! Muito obrigado!
@acecampos @arthurtreuherz favor compartilhar o logo com a Lilian Hendrix

**Comment by marcioalvessilva** [comment]
@renatomurasaki, @acecampos e @arthurtreuherz 

Segue link para o logo de 35 anos do DeCS/MeSH Versão Aprovada

**JPG**
https://github.com/bireme/artes-graficas/blob/main/decs-mesh/logo%2035%20anos/jpg/logo-ES.jpg

**PNG - Sem fundo** 
https://github.com/bireme/artes-graficas/blob/main/decs-mesh/logo%2035%20anos/png/Logo-Sem-Fundo-ES.png

**PNG - Sem fundo com o texto branco** 
https://github.com/bireme/artes-graficas/blob/main/decs-mesh/logo%2035%20anos/png/Logo-branco-Sem-Fundo-ES.png

![image](https://user-images.githubusercontent.com/48724136/130075831-05592513-2155-407f-88c6-cfdce8a9de28.png)
