### ISSUE TITLE
Criar imagens página reuniões da Rede e imagem de destaque

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#74]
Marina, criar imagens para:

1) Entradas/destaques em PT, EN e ES que ficarão disponíveis na página: http://red.bvsalud.org/fortalecimento-das-redes-de-informacao-em-saude-na-alc/, conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/13439949/156794047-5f76e5bf-0757-407a-8521-d1a3ddb49430.png)

- Para as imagens, pode usar elementos, ícones, figuras, background de acordo com os temas das reuniões.

Títulos:

- Reuniões de Coordenação BVS e LILACS
- Reuniones de Coordinación BVS y LILACS
- VHL and LILACS Coordinations Meetings

- Buenas Prácticas en los Procesos Editoriales
- Boas Práticas nos Processos Editoriais
- Best Practices in Editorial Processes

- Acesso e Uso da Informação 
- Acceso y Uso de la Información
- Access to and Use of Information

2) Imagem para destacar o calendário geral das reuniões que ficar no carrossel do portal da Rede BVS, LILACS, Twitter e para chegar até a página http://red.bvsalud.org/fortalecimento-das-redes-de-informacao-em-saude-na-alc/.

Título PT
Fortalecimento das Redes de Informação em Saúde na AL&C
Subtítulo: Calendário de reuniões 2022
- Incluir selo 55 anos

Título ES
Fortalecimiento de las Redes de Información de Salud en AL&C
Subtítulo: Calendario de reuniones 2022
- Incluir selo 55 anos

Título EN
Strengthening Health Information Networks in AL&C
Subtítulo: Calendar of meetings 2022
- Incluir selo 55 anos

**Comment by pierrima** [comment]
Juliana, boa tarde

Seguem as imagens referentes ao item 1
![Acesso_Uso_EN](https://user-images.githubusercontent.com/13052947/157111366-acbdf9bd-4c30-4664-b096-8d041ea58314.png)
![Acesso_Uso_es](https://user-images.githubusercontent.com/13052947/157111370-013f9910-51b2-4ece-a6f7-bcd8da2271c8.png)
![Acesso_Uso_PT](https://user-images.githubusercontent.com/13052947/157111372-4f0e3e1f-40af-4f12-8dc2-ae93801d764a.png)
![buenas_praticas](https://user-images.githubusercontent.com/13052947/157111376-fcf698f3-8a09-4fdd-8ed8-8ebbf05eb656.png)
![buenas_praticas_en](https://user-images.githubusercontent.com/13052947/157111378-7c27026a-8046-45cc-8bdc-bc38b5655479.png)
![buenas_praticas_es](https://user-images.githubusercontent.com/13052947/157111380-91202f8f-4e2e-4581-96ce-77996aedd8f9.png)
![buenas_praticas_pt](https://user-images.githubusercontent.com/13052947/157111382-66a82f1f-420e-48c4-9adb-96af1b4e7889.png)
![reuniao_coord_en](https://user-images.githubusercontent.com/13052947/157111383-5ae26f37-c7a1-4b40-b5e2-ff95f2d6e942.png)
![reuniao_coord_es](https://user-images.githubusercontent.com/13052947/157111384-f65e2a1a-ee78-4962-8246-41eaf5a88ea3.png)
![reuniao_coord_pt](https://user-images.githubusercontent.com/13052947/157111387-7131fbe7-23cd-4973-81b8-0de22fe62a15.png)

**Comment by sousajul** [comment]
Imagens criadas e aprovadas.
