### ISSUE TITLE
Template para área de Acesso e Uso

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#77]
@pierrima 
Poderia por favor desenvolver o template acima para promoção da Rede de Referencistas na página Acesso e Uso da Informação na página da Red BVS.
Atualmente estou aplicando o layout desenvolvido para indexação enquanto não tem um próprio. 
Será aplicado no link de acesso a àrea em http://red.bvsalud.org/fortalecimento-das-redes-de-informacao-em-saude-na-alc/
E na página de Acesso e Uso - http://red.bvsalud.org/fortalecimento-das-redes-de-informacao-em-saude-na-alc/acesso-e-uso-da-informacao/
Naquele padrãozinho ;-)

**Comment by pierrima** [comment]
Olá Rose, boa tarde

Segue o template solicitado.

Abraços
[AcessoUsoInformacao.pptx](https://github.com/bireme/artes-graficas/files/8365148/AcessoUsoInformacao.pptx)

**Comment by pierrima** [comment]
Rose,
Favor considerar o anexo dessa mensagem
[AcessoUsoInformacao.pptx](https://github.com/bireme/artes-graficas/files/8365151/AcessoUsoInformacao.pptx)

**Comment by pierrima** [comment]
Rose, 
Segue o template solicitado.

Abraços
[AcessoUsoInformacao.pptx](https://github.com/bireme/artes-graficas/files/8365162/AcessoUsoInformacao.pptx)

**Comment by pintoros** [comment]
Obrigada!!!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:43c08c3c-1207-48a3-bc7d-f23483cc785e]

________________________________
De: Marina Pierri ***@***.***>
Enviado: segunda-feira, 28 de março de 2022 15:10
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Template para área de Acesso e Uso (Issue #77)


Rose,
Segue o template solicitado.

Abraços
AcessoUsoInformacao.pptx<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Ffiles%2F8365162%2FAcessoUsoInformacao.pptx&data=04%7C01%7Cpintoros%40paho.org%7C6dd01b05b6b84ef043e208da10e62e79%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637840878043973839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CHnUi3VTvzZHASnzcLNuiFWZbO%2FFagJcOlKg8jusa6o%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F77%23issuecomment-1080978555&data=04%7C01%7Cpintoros%40paho.org%7C6dd01b05b6b84ef043e208da10e62e79%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637840878043973839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R2wrZQ6LpfBx%2Brv1jwpgPr3jtIadhzIQj0Ru3qHn6ZU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4CACILVKMGR3GRPRVLVCHYXVANCNFSM5RI6F7ZQ&data=04%7C01%7Cpintoros%40paho.org%7C6dd01b05b6b84ef043e208da10e62e79%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637840878043973839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u1pNjOUlRTEDcQKXh27CuP6B%2F3wgIa%2BOpExD1XEbeZ4%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
