### ISSUE TITLE
Destaque Portal Regional - 28/03

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#80]
@pierrima eu havia colocado no formulário semana passada. Pf poderia publicar essa semana?

Atualizado -  Curso Virtual Introdutório de Políticas Informadas por Evidências (PIE) - em espanhol
Updated -  Introductory Virtual Course on Evidence-Informed Policies (EIP) - in spanish
Actualizado -  Curso Virtual Introductorio de Políticas Informadas por Evidencias (PIE)

pt / en/  es - https://bit.ly/CVOPAS-PIE

**Comment by pierrima** [comment]
Rose, boa tarde

Esse destaque já está publicado no regional. Favor verificar

**Comment by pintoros** [comment]
Marina, como vc não havia publicado, eu atualizei a chamada, tem alguns erros nos labels. Poderia corrigir?
Tb coloquei a palavra atualizado em destaque, fora do nome do curso.

**Comment by pierrima** [comment]
Rose,
Conforme foi acordado em reunião, a planilha deve ser atualizada até sexta-feira e o destaque será sempre atualizado nas segundas-feiras. O destaque mencionado acima foi publicado hoje pela manhã e seguindo o texto que estava na planilha hoje pela manhã.
Assim que possível farei a atualização na imagem.

**Comment by pintoros** [comment]
Ok Marina, mas está com erro. Eu vi quando fui colocar o chamado no Github hoje.

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:28bfd779-0429-4a57-9796-9476fa478ca2]

________________________________
De: Marina Pierri ***@***.***>
Enviado: segunda-feira, 28 de março de 2022 15:39
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Destaque Portal Regional - 28/03 (Issue #80)


Rose,
Conforme foi acordado em reunião, a planilha deve ser atualizada até sexta-feira e o destaque será sempre atualizado nas segundas-feiras. O destaque mencionado acima foi publicado hoje pela manhã e seguindo o texto que estava na planilha hoje pela manhã.
Assim que possível farei a atualização na imagem.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F80%23issuecomment-1081007295&data=04%7C01%7Cpintoros%40paho.org%7C78cd57df38ed4c2fb24c08da10ea57fb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637840895933576861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Sny98nmFOMO3AtqMLLci8paB2lJ7z7ObNStHqnxQeZc%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4EONCZ3E4S3ZMZ3TE3VCH4HNANCNFSM5R36372A&data=04%7C01%7Cpintoros%40paho.org%7C78cd57df38ed4c2fb24c08da10ea57fb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637840895933576861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DV%2ByEl1jSVI26LBGXCcvb2XB6zCZCa24UuaSCeDkuvU%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
