### ISSUE TITLE
Imagem para Vitrine - Dia mundial da saúde

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#81]
@pierrima será que conseguimos ajustar essa imagem para usar como central na aranha da Vitrine para o Dia Mundial da Saúde?
Ela tb está presente no site nos 3 idiomas no site da paho:  https://www.paho.org/pt/campaigns/dia-mundial-saude-2022, mas melhor se for só a imagem, sem a frase.

[whd-a3-poster-print-white-es.pdf](https://github.com/bireme/artes-graficas/files/8366508/whd-a3-poster-print-white-es.pdf)

**Comment by pierrima** [comment]
Rose, boa tarde

Segue a imagem solicitada.

Abraços

![dia_mundial](https://user-images.githubusercontent.com/13052947/160898076-2402205f-64c2-4b67-894f-9d60f80a85f7.png)
