### ISSUE TITLE
Ajustes BVS Honduras 

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#82]
Marina, solicito seu apoio para realizar alguns ajustes na BVS Honduras (https://honduras.teste.bvsalud.org/):

1. Diminuir um pouco o tamanho do banner e ajustar o logo da BVS que está desfocado
![image](https://user-images.githubusercontent.com/13439949/161112548-1ef7488f-233c-4d3e-9d10-307f82b08cf7.png)

2. Ajustar a resolução das imagens da seção Literatura cientifica que estão esticadas
![image](https://user-images.githubusercontent.com/13439949/161112668-81062d16-945a-43aa-9a65-093dee4d8116.png)

3. Diminuir um pouco o tamanho dos títulos das seções
![image](https://user-images.githubusercontent.com/13439949/161112925-556b40b2-0010-4856-8a93-b70bcb306f26.png)

4. Padronizar o tamanho dos logos das instituições no rodapé (as imagens já estão carregadas no WP)
![image](https://user-images.githubusercontent.com/13439949/161113044-6d7c7478-6596-4494-8342-41e08030b42f.png)

**Comment by pierrima** [comment]
Juliana, boa tarde
Informo que os ajustes solicitados foram realizados. Favor validar.
Abraços Marina

**Comment by sousajul** [comment]
Validado.
