### ISSUE TITLE
Portal Vitrines do Conhecimento - ajustes

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#84]
@marcioalvessilva como conversamos, solicito ajustar as imagens no portal referente a coleção de vitrines destacadas, retirando o nome BVS, mantendo o nome do país ou tema da BVS em que a coleção está e, se possível incluir imagens que remetem ao país (menos a bandeira) ou ao tema da coleção de vitrines (caso da enfermagem).

Solicito ainda que no RSS em pt e es, a exemplo do in, apareçam 5 ocorrências ao invés de 4, pois fica um espaço sem conteúdo no final da página.
Obrigada

**Comment by marcioalvessilva** [comment]
Bom dia @pintoros !
Segue imagens, aguardo aprovação para publicar!

![brasil](https://user-images.githubusercontent.com/48724136/162981593-224e05df-84d7-419c-98fd-18e3588a5a73.jpg)
![brasil-en](https://user-images.githubusercontent.com/48724136/162981596-2a49ee59-2a00-43e8-ad38-1023ef119761.jpg)


![colombia-es](https://user-images.githubusercontent.com/48724136/162981598-f000aaac-7ba5-4d91-9abc-bdfb9b2252c3.jpg)
![colombia-pt](https://user-images.githubusercontent.com/48724136/162981600-353314d6-691b-4434-aa90-2ba2808168f8.jpg)


![enfermeria-pt](https://user-images.githubusercontent.com/48724136/162981601-4a091dd4-b22e-4e04-a2b4-9899426e1345.jpg)
![infermeria-en](https://user-images.githubusercontent.com/48724136/162981602-293ad3f0-6769-446f-b392-64f948ccdf67.jpg)


![paraguai-pt](https://user-images.githubusercontent.com/48724136/162981603-9a9078a5-c026-48b7-9957-e5bbd3ad573b.jpg)

![paraguay-en](https://user-images.githubusercontent.com/48724136/162981588-4933acd6-0e5a-421b-a9a6-15c78d085d71.jpg)

**Comment by pintoros** [comment]
Oi Márcio,

Gostei bastante das imagens!
Pode implementar.



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:ce8c9bf9-5845-48d9-b655-421dfdb57378]

________________________________
De: Márcio Alves ***@***.***>
Enviado: terça-feira, 12 de abril de 2022 11:11
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/artes-graficas] Portal Vitrines do Conhecimento - ajustes (Issue #84)


Bom dia @pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wab5tPHk%2Bb6KnZ8TpC10Fk1wIkTRKSHr%2FQLejlG6lDY%3D&reserved=0> !
Segue imagens, aguardo aprovação para publicar!

[brasil]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F162981593-224e05df-84d7-419c-98fd-18e3588a5a73.jpg&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XhCs8ja80R31OpNPCqfaODn2bX%2BiG2RL4REzuuHY%2FSk%3D&reserved=0>
[brasil-en]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F162981596-2a49ee59-2a00-43e8-ad38-1023ef119761.jpg&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pPjXO1I2FNjzKDP5Izk%2FCvMSDzbUvcBuIogAUIM03Fw%3D&reserved=0>

[colombia-es]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F162981598-f000aaac-7ba5-4d91-9abc-bdfb9b2252c3.jpg&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=155VGqfy7JhhKerpzRp4311pYiUBAkYL7Bk32D31DgM%3D&reserved=0>
[colombia-pt]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F162981600-353314d6-691b-4434-aa90-2ba2808168f8.jpg&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9q7khxaw3jxJPo4HixQuKqt%2FeGTuUnx5UMbJTNeCNvo%3D&reserved=0>

[enfermeria-pt]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F162981601-4a091dd4-b22e-4e04-a2b4-9899426e1345.jpg&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=esS4HNiyD9myHatqMtiy%2BWr%2F%2BgP6Zwli88pz3%2BkmM%2BQ%3D&reserved=0>
[infermeria-en]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F162981602-293ad3f0-6769-446f-b392-64f948ccdf67.jpg&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6Udw3H6QIC7zydbrPMAUE3ZOYX215Fz9ZOqJCgLpfeU%3D&reserved=0>

[paraguai-pt]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F162981603-9a9078a5-c026-48b7-9957-e5bbd3ad573b.jpg&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=js3EqJxLoa1Zf%2B%2F6SDAIiP2Il32tHkrG2hbBTnTrb0o%3D&reserved=0>

[paraguay-en]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F162981588-4933acd6-0e5a-421b-a9a6-15c78d085d71.jpg&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MYYbNwkLE9HLl5A5mkcAIkWcpKpfK3QBI8VUhwS%2FWK8%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F84%23issuecomment-1096782164&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7dkpmGrXLainxBULua6ynk7Ys%2FlEYo%2B2pvAWQQk2IQQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4GZFAGK3AWGDRHODYTVEWAARANCNFSM5SPV5LIA&data=04%7C01%7Cpintoros%40paho.org%7C721fcb612b5f4ee609b308da1c8e51e1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637853694845668687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=epUGKnSptHE91ziXxJAwoFph7vd8LCTkO912gaBHJes%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Boa tarde!
Imagens alteradas, por favor validar
