### ISSUE TITLE
Vitrine Gestão do SUS - Ajustes

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#85]
@pierrima  poderia fazer esses ajustes na vitrine  para a próxima reunião do dia 13, por favor?

[Ajuste layout vitrine SUS.pptx](https://github.com/bireme/artes-graficas/files/8420214/Ajuste.layout.vitrine.SUS.pptx)

**Comment by pierrima** [comment]
Olá Rose, boa tarde

Modificações realizadas. Por favor, confirmar se podemos usar somente o logo do SUS ou temos que usar a composição ms+ SUS
