### ISSUE TITLE
Publicação de Mapas de EvidÊncias na Vitrine Historia Natural da Covid

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#86]
@pierrima solicito publicar, o mapa de evidÊncias citado abaixo na Vitrine:

https://brasil.bvs.br/vitrinas/post_vitrines/historia-natural-da-covid-19/

Na área - Infográficos e materiais de comunicação, logo abaixo.

Título:  Mapa de Evidência - Sequelas da COVID-19 Pós-Aguda

https://public.tableau.com/app/profile/bireme/viz/sequelas-covid-pos-aguda-pt/evidence-map

**Comment by pierrima** [comment]
Olá Rose, boa tarde

Mapa publicado conforme indicado.
Abraços

**Comment by pintoros** [comment]
Aguarda validação da contraparte, favor acompanhar a orientação via Trello https://trello.com/c/pPPwz5jD/47-vitrine-do-conhecimento-hist%C3%B3ria-natural-da-covid-19

Obrigada


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:a5a77753-a5dd-468c-9a33-b425cdb4ec4e]

________________________________
De: Marina Pierri ***@***.***>
Enviado: sexta-feira, 8 de abril de 2022 14:21
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Publicação de Mapas de EvidÊncias na Vitrine Historia Natural da Covid (Issue #86)


Olá Rose, boa tarde

Mapa publicado conforme indicado.
Abraços

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F86%23issuecomment-1093108598&data=04%7C01%7Cpintoros%40paho.org%7C65084234ee594333d5f808da19842ffd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637850352779664782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BGpSO2FfUyIYIF82RqBoULKFVn9jI9KLjJOlTi7teho%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4B7KSG6LZ3T27LFYHLVEBTIXANCNFSM5S422B5A&data=04%7C01%7Cpintoros%40paho.org%7C65084234ee594333d5f808da19842ffd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637850352779664782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dlgoa06Q1MqbSUELh1Fsd9%2BmfmwVKE9bK%2BpOnj9jHwQ%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
