### ISSUE TITLE
Incluir infometria na Vitrine de Nutrição

### ISSUE THREAD

**Issue by pintoros** [bireme/artes-graficas#87]
@pierrima  favor incluir a infometria na Vitrine de Nutrição

https://brasil.bvs.br/vitrinas/post_vitrines/alimentacao-e-nutricao-em-saude-publica/

Titulo: Indicadores de produção técnica e científica latinoamericana

https://public.tableau.com/app/profile/bireme/viz/infometria-lilacs-CGAN-es/Histria1

**Comment by pierrima** [comment]
Rose, boa tarde

Criei e publiquei uma página para os mapas de evidências. Por favor, veja se está de acordo,
*clique na imagem mapas de evidências
Abraços

**Comment by pintoros** [comment]
@pierrima um é mapa de evidências, mas o outro é infometria, são diferentes fontes de informação, com diferentes objetivos. Não dá para misturar os dois na mesma página.

**Comment by pintoros** [comment]
@pierrima vc tem previsão para esse ajuste?
Obrigada

**Comment by marcioalvessilva** [comment]
Caso necessário, abrir novo issue
