### ISSUE TITLE
Desenvolver proposta de Mockup para a BVS Uruguay Nacional

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#88]
[AI-BVS-UY-BVS_febr2022.pdf](https://github.com/bireme/artes-graficas/files/8453824/AI-BVS-UY-BVS_febr2022.pdf)

**Comment by pierrima** [comment]
Olá Juliana, boa tarde
Segue a proposta para a BVS Uruguai.
Abraços
![proposta](https://user-images.githubusercontent.com/13052947/166804973-4a63b585-6f1f-4469-be5a-6e5a8e0f56b6.png)

**Comment by sousajul** [comment]
Marina, obrigada.

Enviado para aprovação da equipe do Uruguai.


Abraços,

•••••
Juliana Sousa
Supervisora
MIP<http://red.bvsalud.org/> | Monitoramento de Instâncias e Projetos BVS -
BIREME<https://www.paho.org/pt/bireme>/OPAS/OMS<https://www.paho.org/pt> | Departamento de Evidência e Inteligência para Ação em Saúde – EIH/AD

<https://www.paho.org/bra/>

Tel: +55 11 5576-9833 | VoIP: 44872

 [cid:86b05fc7-366b-4bb2-9b3a-538c49787c2c]
Siga-nos [1499085958495_face.png] <https://www.facebook.com/BIREME/>  [1499085967518_twitter.png] <https://twitter.com/bireme>  [1499085977102_youtube.png] <http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>
________________________________
De: Marina Pierri ***@***.***>
Enviado: quarta-feira, 4 de maio de 2022 15:48
Para: bireme/artes-graficas ***@***.***>
Cc: Sousa, Juliana (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/artes-graficas] Desenvolver proposta de Mockup para a BVS Uruguay Nacional (Issue #88)


Olá Juliana, boa tarde
Segue a proposta para a BVS Uruguai.
Abraços
[proposta]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13052947%2F166804973-4a63b585-6f1f-4469-be5a-6e5a8e0f56b6.png&data=05%7C01%7Csousajul%40paho.org%7Cebf197f2a5b44bcaa0d208da2dfeb1f2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637872869176594791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=39%2FgySC%2BslZO0GFF42D5B1lIlZctA97ngxunidYBGYc%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F88%23issuecomment-1117686267&data=05%7C01%7Csousajul%40paho.org%7Cebf197f2a5b44bcaa0d208da2dfeb1f2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637872869176751031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Sz1SlI8f5d19OruFgnH7yyJWBuE8pcverRIobw%2BBG50%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADGRHTKCNYN7GHDFXDTLMCDVILBAHANCNFSM5S5CKKJA&data=05%7C01%7Csousajul%40paho.org%7Cebf197f2a5b44bcaa0d208da2dfeb1f2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637872869176751031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oCgBed%2Fix79sNsEnvdCoRSLACglko%2FspaMNvAKU4qvk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by sousajul** [comment]
Aprovado.
