### ISSUE TITLE
Criar imagem para Mapa de Evidencias Efetividad Clínica de las Plantas Medicinales Brasileñas

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#89]
Marina criar imagem para Mapa de Evidencias Efetividad Clínica de las Plantas Medicinales Brasileñas seguindo o modelo das demais em: https://mtci.bvsalud.org/mapas-de-evidencia/.

**Comment by pierrima** [comment]
Olá Juliana, boa tarde

Segue a imagem.
![plantas_medicinais](https://user-images.githubusercontent.com/13052947/163862460-a96200a7-9692-4544-b8de-c390cbb62ce2.png)

**Comment by sousajul** [comment]
Ok
