### ISSUE TITLE
Elaborar banner para destacar oportunidade de trabalho como Analista de Dados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/artes-graficas#9]
@marcioalvessilva por favor, baseando-se no que foi feito para o DeCS, usar a frase "Oportunidade de trabalho na BIREME com análise das fontes de informação da BVS"

@marcoslmori assim que o Márcio elaborar o banner, por favor, pode publicá-lo na homepage da RedDes apontando para o link 

https://reddes.bvsalud.org/vaga-analista-de-dados-2021/

**Comment by marcioalvessilva** [comment]
@renatomurasaki e @marcoslmori 
Segue imagem 
https://github.com/bireme/artes-graficas/blob/main/banners-sites/reddes/jpg/vaga-analista-fontes-informacao.jpg

![image](https://user-images.githubusercontent.com/48724136/130107098-05a48de7-bb29-4b71-ae8c-4d3658a3edb1.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva excelente. Aprovado
@marcoslmori pode utilizar, por favor, para colocar no portal da RedDes

**Comment by marcoslmori** [comment]
feito em https://reddes.bvsalud.org/
