### ISSUE TITLE
Desenvolver imagem de destaque para o Instrumento de Maturidade da BVS

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#90]
Marina, solicito Desenvolver imagem de destaque para o Instrumento de Maturidade da BVS para divulgação nos nossos portais, twitter, redes sociais etc. para ser enviada para a rede BVS dia 02/05 pela manhã.

Para inspirar veja o que é: http://red.bvsalud.org/modelo-bvs/pt/instrumento-de-maturidade-da-bvs/
Outros elementos que podem ser usados na imagem: Maturidade, Avaliação, Evolução, Crescimento, fortalecimento, autoavaliação
=> Pode usar o bonequinho com a escada e a seta (sem o texto que está escrito em cada degrau), mesclando talvez com os hexágonos

Conteúdo:
PT
Título: Instrumento de Maturidade da BVS
Subtítulo: um processo de melhoria contínua para o fortalecimento das Instâncias da Rede BVS

ES
Título: Instrumento de Madurez de la BVS
Subtítulo: un proceso de mejora continua para el fortalecimiento de las Instancias de la Red BVS

Pensei também em criarmos um logo, algumas ideias de modelo (este é para outro momento), mas pensei na possibilidade:

![image](https://user-images.githubusercontent.com/13439949/165856314-d4b9f240-8066-477d-b0e1-1cb74555320e.png)

![image](https://user-images.githubusercontent.com/13439949/165856451-8c5e6111-1b2d-4c96-b1b3-54b61acc0e4a.png)

![image](https://user-images.githubusercontent.com/13439949/165856652-bfd19173-d76c-41c3-ac4a-a47244f1aeb8.png)

![image](https://user-images.githubusercontent.com/13439949/165856702-55a114c1-12c2-40ff-9255-47cf15c9b80a.png)

**Comment by pierrima** [comment]
Olá Juliana, bom dia
Segue a proposta.
ABraços
![modelo_es](https://user-images.githubusercontent.com/13052947/166234492-42b79cd6-2f97-4eee-85f1-5de93b47d31a.png)
![modelo_pt](https://user-images.githubusercontent.com/13052947/166234505-66c5fd5c-32e3-4ced-8476-9c2b53246765.png)

**Comment by sousajul** [comment]
Marina, imagens Ok. Sobre o logo vou falar com a Veronica e se necessário abro outra issue. ;-)
