### ISSUE TITLE
Desenvolver Logo para o Instrumento de Maturidade da BVS

### ISSUE THREAD

**Issue by sousajul** [bireme/artes-graficas#91]
Marina, visando fortalecer o Instrumento de Maturidade da BVS, pensamos em criar um Logo para o reforçar a divulgação e criar uma identidade visual para o Instrumento de Maturidade da BV que apoia na avalição e desenvolvimento contínuo das BVS.

Para inspirar veja o que é: http://red.bvsalud.org/modelo-bvs/pt/instrumento-de-maturidade-da-bvs/

=> Como ícone, talvez você possa aproveitar a imagem do bonequinho com a escada e a seta (sem o texto que está escrito em cada degrau), representando análise, maturidade, avaliação, evolução, crescimento, fortalecimento, autoavaliação. etc.

Você pode fazer algumas propostas para aprovação da Veronica e equipe?

Titulo:
PT: Instrumento de Maturidade da BVS
ES: Instrumento de Madurez de la BVS
EN: VHL Maturity Instrument

Algumas ideias:

![image](https://user-images.githubusercontent.com/13439949/166568653-c19f944a-a69c-4c52-b9f3-9dd7a36a40de.png)

**Comment by pierrima** [comment]
Olá, Juliana. Boa tarde.

Seguem as propostas para o logo.

Abraços
![logo2](https://user-images.githubusercontent.com/13052947/168653440-d38e60b2-800e-4b42-8764-3fdf47f46acd.png)
![logo3](https://user-images.githubusercontent.com/13052947/168653445-689420e1-48f0-4277-b77d-570ece445a6c.png)
![proposta1](https://user-images.githubusercontent.com/13052947/168653448-0687facb-8adc-4fb7-a086-c541be9da688.png)

**Comment by sousajul** [comment]
@pierrima o logo aprovado foi o que tem o hexágono com as linhas dentro.
https://user-images.githubusercontent.com/13052947/168653445-689420e1-48f0-4277-b77d-570ece445a6c.png.

![image](https://user-images.githubusercontent.com/13439949/171696396-0ee51bb6-571d-42d4-a82a-05aac0ed6424.png)


Mas é preciso fazer alguns ajustes:

- Inverter o posicionamento do hexágono, deixando a base reta para baixo.
- Considerando que o instrumento de maturidade tem 4 níveis, e para representar isso, poderia incluir mais uma linha dentro do hexágono com a bolinha.
- Colocar a palavra "Maturidade" em maiúscula.

**Comment by sousajul** [comment]
@marcioalvessilva segue issue sobre o logo de maturidade.

**Comment by marcioalvessilva** [comment]
Olá @sousajul segue minha versão do logo com as modificações, como não encontrei os originais eu precisei refazer, também não tenho as mesma fontes. qualquer coisa me avisa para eu continuar procurando.

![image](https://user-images.githubusercontent.com/48724136/178593943-a227ac84-a364-47a8-9bf4-786a1da6fbce.png)

**Comment by sousajul** [comment]
@marcioalvessilva proposta de logo aprovada. Por favor, enviar os arquivos originais.

**Comment by marcioalvessilva** [comment]
Logo publicados no github

https://github.com/bireme/artes-graficas/tree/main/logos/bvs/maturidade

**Comment by marcioalvessilva** [comment]
Logos em PT, ES e EN

**Logo - JPG**
https://github.com/bireme/artes-graficas/tree/main/logos/bvs/maturidade/JPG

**Logos - Sem fundo**
https://github.com/bireme/artes-graficas/tree/main/logos/bvs/maturidade/PNG

**Todos**
https://github.com/bireme/artes-graficas/tree/main/logos/bvs/maturidade
